### ISSUE TITLE
3 Thess.

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#1]
Lf538c6ae235d4f9baed168c70ee34652

has a unique citation reference as in title

**Comment by PietroLiuzzo** [comment]
no idea what this is. ideas @thea-m @eu-genia @MassimoVilla ?

**Comment by MassimoVilla** [comment]
Could you please indicate the unique citation reference where 3 Thess is employed @fitawari  ? I only can read a sequence of letters and numbers.

**Comment by PietroLiuzzo** [comment]
Massimo, you can use that in the link: http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Lf538c6ae235d4f9baed168c70ee34652

**Comment by eu-genia** [comment]
it this retyped correctly from dillmann? actually there are only two epistles to thessalonians as far as i know...

**Comment by MassimoVilla** [comment]
it's a missprint for 2 Thess (http://www.tau.ac.il/~hacohen/NT/NTp%20572.html)

**Comment by MassimoVilla** [comment]
second line, ወይሰባሕ፡
