### ISSUE TITLE
ስንዱን, ስንዶን፡ , ሰንዱን፡ , ሰንዶን

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#134]
http://betamasaheft.aai.uni-hamburg.de/Dillmann/?mode=fuzzy&q=%E1%88%B4%E1%8A%96%E1%8B%B6%E1%88%B5&id=Lf94a167f75f74fc9bda8b2aace271710

what's actually meant here? variants? should they be in the heading or are they fine in the body as they are?

**Comment by abausi** [comment]
these are variants of one "unstable" entry, for which no "main form" can be determined; thexy would be at best represented ALSO in the heading, but we can also live with the display as it is at present
