### ISSUE TITLE
online DL: "Ap." - no ID because ambigue? 

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#14]
- the abbr. "Ap." is used in different citations; it usually refers to "Apostolorum", as in: (1) "Stat. Ap." - Statuta Apostolorum (part of Senodos), (2) "Const. Ap." - Constitutiones Apostolorum, (3) "Can. Ap." - Canones Apostolorum; these are different works therefore no ID No to be assigned to "Ap." 
- it appears that capital letter "Ap." is contrasted with "ap." = apocryphus; application in DL is far from consistent, it seems;

**Comment by PietroLiuzzo** [comment]
the 6 entries where Ap. is wrongly marked need to be fixed
https://betamasaheft.eu/Dillmann/search.html?ref=ref&q=Ap.
