### ISSUE TITLE
Coloumn break

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#143]
(written with @PietroLiuzzo )
 The last available coloumn break is 1392, and therefore all the following terms (around 2000 from 10135 to 12220) excluded the ND terms, carry this column break link to the pdf.  What do we do with the following coloumn breaks? are the Nomina propria and following additions already there? and in which order? 

adding column breaks is possible in the editor but the current order is that of the entries as they where in the txt.

**Comment by AndreasEllwardt** [comment]
We can still use the original doc-files with the original column  
breaks, if we want to.



Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
sure, but here the issue is related to the app, not to the doc file. the txt used to generate this app had column breaks till 1392. do we need / want to add also the following? does it make sense? I remember that from 1425 are addenda which have been added into the respective entries. We spoke about this before and we postponed this small point to a later point.

**Comment by AndreasEllwardt** [comment]
as fair it is not <nd>, it is still Dillmann, so it still has column  
breaks which we might want to use as reliquiae



Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
ok. then to add the column breaks for columns from 1392 to 1425 I think we need to know if the entries are already there and if yes in which order were they in the txt file. 
if they were not there, then they can be added and the cb can be contextually added to the new entries.
if they are already there we could add the column breaks but as far as i can tell checking on the pdf, the order will be faulty.

**Comment by abausi** [comment]
We will discuss it on the 8th. A technical solution will be found. It is 
however essential that we give priority to the files which are the 
sources for the app and that these at this point are used as "master"

Il 26.07.2017 14:04, Pietro Liuzzo ha scritto:
