### ISSUE TITLE
pdf export of single entries

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#149]
the pdf export for individual entries is now available. please let me know if it is ok, I invented the layout which can be entirely modified (xslfo).
a pdf export of all dillmann is also possible off course. 
@wdickhut

**Comment by abausi** [comment]
I think it works well. Also a PDF of all Dillmann / our Lexicon could be considered, of course. It remains to be decided if this has to be made available to whom outside of the project

**Comment by PietroLiuzzo** [comment]
a pdf export has been prepared and is available for inspection (with 500 random entries).

this works, but clashes against some data issues:
- #76 is not yet completely done, although getting better and better. this means invalid data which is often cause of problems anyway
- some column breaks are assigned twice.

**Comment by PietroLiuzzo** [comment]
the script generating this PDF is restricted to dba execution.

**Comment by PietroLiuzzo** [comment]
I am downloading and validating all the files to see how the situation looks like.

**Comment by PietroLiuzzo** [comment]
the data is in very good shape. after updating the schema to TEI 3.2.0 and including linking module only 4 files do not validate

**Comment by PietroLiuzzo** [comment]
all files validate

**Comment by PietroLiuzzo** [comment]
all column breaks have been checked and fixed.
there where some mis matches, some missing, some added twice, some typed wrong. 
all these have been corrected

**Comment by PietroLiuzzo** [comment]
This specific issue and derivate consideration are now completed and #76 remains open till further notice
