### ISSUE TITLE
online DL Abbre.: please unify 5 different abbre. to one: "Asc. Jes." (LIT1671Isaiah)

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#15]
- there are five different abbre. in use to denote one work cited in DL: Ascension of Isaiah = Asc. Jes. (= DL Sigla); 
- no ID will be assigned to any one of the other abbreviations found in the printed DL: (1) Asc., (2) Asc. JEs., (3) Asc. Jes, (4) Asc. Jes. p. 
- for the last, please change/correct mark-up (only 1 sample): 
L05b60bf99176473185b2bccc9405edfd

**Comment by PietroLiuzzo** [comment]
Are all those on the abbreviation file?
