### ISSUE TITLE
enter encoded link to bm entities

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#154]
when referring to a mss, a person, a place, a literary work (by title, not by citation) enter reference to correct bm entity and produce link in visualization and pdf

**Comment by PietroLiuzzo** [comment]
is this still a requirement? @vitagrazia81 @wdickhut @SusanneHummel @AndreasEllwardt

**Comment by SusanneHummel** [comment]
Alessandro did not want to have a bm link to a specific person within a lexicon entry
