### ISSUE TITLE
create testing suite for editor

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#156]
before submitting the result from the editor add function to test visualization of the xml entered.

**Comment by PietroLiuzzo** [comment]
before doing this move guidelines to the side of the screen with a toogle function

**Comment by PietroLiuzzo** [comment]
@SusanneHummel @vitagrazia81 what do you think about this?

**Comment by PietroLiuzzo** [comment]
originally requested by @AndreasEllwardt

**Comment by SusanneHummel** [comment]
@AndreasEllwardt @vitagrazia81 
As we have the possibility to edit the entry again and again (until we have it righlty done:), I don't think it is an urgent, important issue (sorry, Andreas!). The more we work on it the less we need attempts - thats my humble hope!
