### ISSUE TITLE
personal name

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#158]
add notation [[+n.pr.+]] in xml or editor for all of those without notation

**Comment by PietroLiuzzo** [comment]
I am still not sure if this needs to be done or not. there are 140 entry containing personal name. I can do this with other operations to close of earlier unsolved issues about the abbreviations, for example, but I will need to block the editor for some hours and then reload the app with the substitutions. If you could please group a list of these changes I can do that.

**Comment by AndreasEllwardt** [comment]
hä?

**Comment by PietroLiuzzo** [comment]
closing because probably not relevant anymore
