### ISSUE TITLE
Online DL Abbre.: change current entries "Atk. f."/"Atq. f."/"Chron. L. Atq." to only "Chr. L. Atq."

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#16]
- Sigla in printed DL: Chr. L. Atq = Chronica Liq. Atqu (not to be found in online list of abbre. of online DL) 
- change all: "Atq. f." - "Chron. L. Atq." > "Chr. L. Atq."
- add: "Chr. L. Atq." to the list of abbreviations of the online DL 
- liq = church scholar or royal court judge, At'qu = personal name (ID: PRS2182Asqu (?)), see EAE Vol. 1, p. 382-383.
- Ms.-Basis? - vgl. Katalog UB Frankfurt, L. Goldschmidt:  http://sammlungen.ub.uni-frankfurt.de/kataloge/content/titleinfo/1551833

**Comment by PietroLiuzzo** [comment]
Is this a literary work?  We are not fixing dillmann we just need to pair it's abbreviations to work records. Which are the attested abbreviations used? The two after "change all:"? I will tag them as references so you will have them in the abbreviations  list. Are they in your xml file?

**Comment by PietroLiuzzo** [comment]
@thea-m because you have worked on the Frankfurt manuscripts and have created this record
https://betamasaheft.eu/works/LIT4864ChronAtqu/main do you happen to know in which of the frankfurt manuscripts it is contained? the BM data seems not to know about this.

**Comment by PietroLiuzzo** [comment]
data has been updated offline. point 4 possibly more relevant for Beta Masaheft.
