### ISSUE TITLE
Keyboard missing

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#163]
If we add a new Meaning to an existing Dilmmann entry, in the string with all symbols for the new sense the keyboard is missing. Anyway,  for the moment  we can open the Keyboard in Dillmann Sense and then to copy and  paste.

**Comment by PietroLiuzzo** [comment]
please, add the meaning, confirm and edit again to have the keyboard

**Comment by PietroLiuzzo** [comment]
the workaround is easy enough in relation to the amount of times this function is used, so I will not do this change until it is really needed
