### ISSUE TITLE
Verweise innerhalb der Dillmann-App

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#167]
Derzeit wird nur bei "vid. sub" innerhalb der Dillmann-App querverwiesen, dies sollte jedoch auch nach "i.q." oder vor "q.v." geschehen.

**Comment by PietroLiuzzo** [comment]
i.q. behaves now in the visualization like vid. and vid. sub.
q.v. behaves like HINC if at the end of the entry, like vid. but changing the link of the PREVIOUS word if in the middle of the string
