### ISSUE TITLE
Online DL Abbr.: "Bar." = Paralipomena of Jeremiah (LIT2167Parali)?

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#17]
- printed DL has abbrev.: "Bar." for "Baruchi liber apocryphus" which corresponds to Paralipomena of Jeremiah = 4 Baruch = Liber Baruch (LIT2167Parali), correct? 
- in general it would be nice to have a Latin/Greek work title reference in the B.M. database OR (where applicable) the respective "Corpus Christianorum - Clavis ..." reference no.

**Comment by PietroLiuzzo** [comment]
if we had a latin title in the record you would see it in BM list view under titles. there isn't any in the record has far as I can see. on the correctness of the identification, I don't know!

**Comment by eu-genia** [comment]
I believe it is LIT1202Bookof (1 Baruch).
We are going through Works adding all possible titles, but it will take time. For the moment you have what you have, in case of doubt consult the Index of the EAE (vol. 5) as the current Work list has been elicited from the Index.

**Comment by fitawari** [comment]
Update on works & abbreviations in regard to "Baruch" in Ethiopic literature and Dillmann's terminology: 
(printed DL Sigla - DL explanation - BM referenced LIT no. - English reference title) 
Bar. - Baruchi liber apocryphus - LIT1202Bookof - Book of Baruch (Biblical book EOTC; apocryph to prot. DL)
Rel. Bar. - Reliquiae Baruch - LIT2167Parali - The Rest of the Words of Baruch/Paralipomena of Jeremiah 
Vis. Bar. - Visio Baruchi ficticia - LIT1120Apocal - Ethiopic Apocalypse of Baruch
