### ISSUE TITLE
ሠለሠ

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#171]
this should find multiple results but find nothing. should find ሠለሰ

**Comment by PietroLiuzzo** [comment]
This is now solved by an additional function in the search code.
the options returned for the example ሠለሠ are now: ሠለሠ ሰለሠ ሰለሰ ሠለሰ
This works also for multiple occurrences. 
entering ሠሠሠ will search for ሠሠሠ ሰሠሠ ሰሰሠ ሰሰሰ ሰሠሰ ሠሰሠ ሠሰሰ ሠሠሰ
entering ሠህሠህ will search for ሠህሠህ ሠሕሠህ ሠሕሠሕ ሠህሠሕ ሠኅሠህ ሠኅሠኅ ሠህሠኅ ሰህሠህ ሰህሰህ ሠህሰህ ሰሕሠህ ሰሕሰህ ሠሕሰህ ሰሕሠሕ ሰሕሰሕ ሠሕሰሕ ሰህሠሕ ሰህሰሕ ሠህሰሕ ሰኅሠህ ሰኅሰህ ሠኅሰህ ሰኅሠኅ ሰኅሰኅ ሠኅሰኅ ሰህሠኅ ሰህሰኅ ሠህሰኅ
