### ISSUE TITLE
header of the entry: two different fonts?

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#172]
ዓምደ፡ ጽዮን፡
the word (Ethiopic Unicode) and the word divider (Nyala) are dispalyed in two different fonts?

**Comment by PietroLiuzzo** [comment]
quite possible. please install NOTO for a unified experience. I cannot know what fonts you are using and what code you associate with them. If it is not finding the divider in the first set then it will fallback.
