### ISSUE TITLE
Seitenzahlen der neuen Referenz fehlen in PDF

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#173]
Im Eintrag steht  http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/Lf927504e7be5499d878ffbb77cc18326

Deutsch
ተላህያ፡ ለባሕር። Meeresbrandung Kebr. Nag. 62a l.11-12. Bezold 1905, page XXIIa 

in PDF
TraCES de ተላህያ፡ ለባሕር።
Meeresbrandung Kebr. Nag. 62a l.11-12.
bm:Bezold1905KebraN

**Comment by PietroLiuzzo** [comment]
I have modified the PDF to print the full entry for the bibliographic record from the zotero group library. Please let me know how you would like to have this

**Comment by PietroLiuzzo** [comment]
We want to print in the PDF on each `bibl` element author and year and the page reference in  `citedRange`. at the end add a further fo:flow section with Bibliography and take distinct-values of each `ptr/@target` and print the full record entry from Zotero.

**Comment by PietroLiuzzo** [comment]
this has now the desired behavious
