### ISSUE TITLE
F.N.

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#179]
http://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8C%BB%E1%88%95%E1%89%85&id=L042a72e502404c549014e9e2915bf6f6

F.N. ist hier nicht als Referenz erkannt.

**Comment by PietroLiuzzo** [comment]
Die nicht erkannte Referenzen sind viele, aber insgesamt eine kleine Teile. Bitte korrigieren sie ins editor.
