### ISSUE TITLE
Online DL Abbr.: Vit. (hagiographies cited by Ludolph, used by Dillmann) 

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#18]
- some abbr. are missing in the current online DL list of abbreviations, e.g. "Barb." = "Vit. S. Barb." - "Vita S. Barbarae (in Cod. Berolinensi, a Ludolfo lecta)." > please add abbreviations online (e.g. all "Vit." abbreviations)

on this example: 
- under "Barbara" there is no hit in the B.M. database (only PRS entries, no LIT) 
- see: Dillmann, Katalog ... Berlin, ms. no. 66, text no. 4, [Ms. or. fol. 117] - this is a codex containing homilies to be read in the month of Tahsas; Ludolf used it, DL labelled it in his Sigla: "Codex Berolinensi"; description online: https://archive.org/stream/diehandschriften03preu#page/56/mode/2up/search/B%C3%A4rbara 
- please create new LIT entry

**Comment by thea-m** [comment]
I can create new LIT entries, but I don't know how to add abbreviations online - can you show it to us?

**Comment by thea-m** [comment]
created LIT4510GadlaBa and LIT4509GadlaBarb

**Comment by fitawari** [comment]
Thanks, I'll make use of them. 
On adding new abbreviations in the online DL edition: I need to discuss this with Pietro.


      Von: thea-m <notifications@github.com>
 An: SChAth/dillmann <dillmann@noreply.github.com> 
CC: fitawari <fitawari@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 14:54 Donnerstag, 16.Februar 2017
 Betreff: Re: [SChAth/dillmann] Online DL Abbr.: Vit. (hagiographies cited by Ludolph, used by Dillmann) (#18)
   
created LIT4510GadlaBa and LIT4509GadlaBarb—

**Comment by PietroLiuzzo** [comment]
I will not create new abbreviations in Dillmann, I have no authority to do that!  but I can mark up those as references and will do!

**Comment by PietroLiuzzo** [comment]
please @fitawari add a section like this in your file:

```xml
<abbreviatur>
        <reference>Vit. Barb.</reference>
        <dillmanProposedAbk>F.M.</dillmanProposedAbk>
        <dillmanAttestedAbk/>
        <dillmanExplanation>Vita S. Barbarae (in Cod. Berolinensi, a Ludolfo lecta).</dillmanExplanation>
        <normalization/>
        <bmID/>
    </abbreviatur>
```

**Comment by fitawari** [comment]
Thanks a lot, I'll include that (and attend to the other feedback - on many points, my remarks refer to issues on which I only point out potential problems, without being able/authorized to do changes in the respective databases)


      Von: Pietro Liuzzo <notifications@github.com>
 An: SChAth/dillmann <dillmann@noreply.github.com> 
CC: fitawari <fitawari@yahoo.de>; Mention <mention@noreply.github.com>
 Gesendet: 15:44 Montag, 20.Februar 2017
 Betreff: Re: [SChAth/dillmann] Online DL Abbr.: Vit. (hagiographies cited by Ludolph, used by Dillmann) (#18)
   
please @fitawari add a section like this in your file:<abbreviatur>
        <reference>Vit. Barb.</reference>
        <dillmanProposedAbk>F.M.</dillmanProposedAbk>
        <dillmanAttestedAbk/>
        <dillmanExplanation>Vita S. Barbarae (in Cod. Berolinensi, a Ludolfo lecta).</dillmanExplanation>
        <normalization/>
        <bmID/>
    </abbreviatur>—
