### ISSUE TITLE
references with f.

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#182]
`<ref cRef="Kid. " loc="23.">Kid.  f. 23.</ref>`
becomes in editor
 *Kid. |23.*f.| 

check that it does not inferfere with the correct content on save and why pipe is wrongly added

**Comment by PietroLiuzzo** [comment]
ACTHUNG @AndreasEllwardt !!! 

please see the guidelines, where they say: 

> you might find also this notation *Kuf. |35*p.|, this is for where a unit is specified by Dillmann.

the above is correct and should be left as it is. cases like 
*Clem. |115 f.*|

are also fine and should be left as they are.
