### ISSUE TITLE
Search terms are not highlighted in the entry

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#185]
http://betamasaheft.eu/Dillmann/?mode=none&q=%22%E1%8A%A5%E1%8A%95%E1%89%B0%E1%8D%A1%20%E1%8B%AD%E1%89%A4%22&id=L3b4d830677ef46c0beaf9f1c172d2d24

**Comment by PietroLiuzzo** [comment]
this is now fixed, please test and close issue if ok.
