### ISSUE TITLE
Tag for Arabic Language displayed

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#187]
http://betamasaheft.eu/Dillmann/lemma/L79193c3ea1204939939fc26d00fb48c2

**Comment by SusanneHummel** [comment]
it happened again,
http://betamasaheft.eu/Dillmann/lemma/L79193c3ea1204939939fc26d00fb48c2

SORRY 

in the pdf, the arabic is not displayed
file:///C:/Users/EAE-Admin/Downloads/L79193c3ea1204939939fc26d00fb48c2%20(4).pdf

**Comment by PietroLiuzzo** [comment]
There seams to be a problem with the input method you used for the arabic. other arabic text in unicode is correctly detected and the markup correctly added. that is also the reason why the arabic is not recognized in the pdf
