### ISSUE TITLE
ed.

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#194]
@SusanneHummel  what does 173a l.12 (ed.) means?

**Comment by PietroLiuzzo** [comment]
e.g.  here http://betamasaheft.eu/Dillmann/lemma/L6114389d5d4e4801b49cb126eb97c6fc

**Comment by SusanneHummel** [comment]
Es bedeutete "Edition" im Gegensatz zu "Transl" = "Überstetzung"
Die Unterschiedung ist notwendig, da die Seitenzahlen in diesen beiden teilen wieder von vorn anfangen; es gibt als Seite 20 sowohl in Ed. als auch in transl.
