### ISSUE TITLE
zotero record for Kidāna Wald Keflē and Dasstā Takla Wald am

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#196]
In the entry ሰይ the bibliographical data "Kidāna Wald Keflē and Dasstā Takla Wald am  (1955/1956, 860-61 "
does not appear properly: one bracket is missing.

**Comment by PietroLiuzzo** [comment]
the data is wrongly entered in Zotero. 
https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/7JIVFQ8W/tag/bm%3AKidaneW%C3%A4ldGeezGramDict

please follow guidelines here to fix it.
https://github.com/BetaMasaheft/Documentation/wiki/zoteroguidelines

**Comment by MagdaKrzyz** [comment]
Ok! Thank you!
m

2017-12-06 12:14 GMT+01:00 Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
as discussed also with @FrancescaPanini  the record in Zotero is now correct and the visualization is has expected and documented here https://betamasaheft.github.io/bibliography/#fixes
for publications the result is as expected but please note the known issues section where it is stated that you cannot have the double date in the citation of this type of records.
**PLEASE do not corrupt the zotero bibliography to try and get it look like you think it should.**

**Comment by MagdaKrzyz** [comment]
Dear Pietro,

I have not corrupted it. I don't understand what you mean. Have I changed
sth.?
m

2017-12-06 14:05 GMT+01:00 Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
I know, it was just to prevent further changes. its all good!

**Comment by MagdaKrzyz** [comment]
I see! I am studying the guidlines....
All the best!
And have a good trip!
m

2017-12-06 16:21 GMT+01:00 Pietro Liuzzo <notifications@github.com>:

**Comment by FrancescaPanini** [comment]
Hi Magda,
Do no worry, I believe it was meant as a general reminder: sometimes, when
one does not get the expected output from Zotero, one could be tempted to
put information in other fields to have an apparently better result. But
this must not be done.

Hope it makes sense
Francesca

**Comment by MagdaKrzyz** [comment]
I see. I was just wondering if I didn't remove sth. and have not noticed
it.

Have a good evening.

2017-12-06 17:46 GMT+01:00 FrancescaPanini <notifications@github.com>:

> Hi Magda,
> Do no worry, I believe it was meant as a general reminder: sometimes, when
> one does not get the expected output from Zotero, one could be tempted to
> put information in other fields to have an apparently better result. But
> this must not be done.
>
> Hope it makes sense
> Francesca
>
