### ISSUE TITLE
((vid.)) \*gez*ገብር፡\*, \*gez*መስቀል፡\*

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#197]
@SusanneHummel @wdickhut @AndreasEllwardt @abausi  @vitagrazia81 

- [x] We will document for cases as the one above, where vid. points to a list of values in geez the use of **comma** as a separator. 
- [x] I will change the behaviour of vid. to make of EACH following geez value separated by comma a link to the corresponding lemma in the app

**Comment by PietroLiuzzo** [comment]
please check if this meets the requirement http://betamasaheft.eu/Dillmann/lemma/L9db555b4672341b0a6ca4932ea56d8c4

**Comment by vitagrazia81** [comment]
I have checked: if I click on ገብር፡ it works, if I do on the second it does not. It does not go to the specific entry for መስቀል፡
