### ISSUE TITLE
language in pdf

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#199]
Wäre es möglich die jeweiige Sparche nicht nur in der Webansicht sondern auch in der PDF anzuzeigen?

z.B.
http://betamasaheft.eu/Dillmann/lemma/Le3e8291f4ff74e178cd6223a86c22a99

**Comment by PietroLiuzzo** [comment]
mmmm... wie soll es aussehen? Meiner Meinung nach den Apex ist OK in website aber nicht zu drucken...
