### ISSUE TITLE
Warning of an already existing entry when creating a "new" one

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#203]
Wäre es möglich, dass die App den User, der ein neues Lemma anlegen möchte, darauf aufmerksam macht, dass dieses Lemma schon existiert? So könnten doppelte Lemmata verhindert werden;. Der User muss dann entschieden, ob er trotzdem ein weiteres Lemma mit dem gleichen Wort/Wurzel anlegen möchte

**Comment by PietroLiuzzo** [comment]
on keyup of the lemma popup search result and warning message if a lemma as this one exists already

**Comment by PietroLiuzzo** [comment]
#205

**Comment by PietroLiuzzo** [comment]
this function is now implemented
