### ISSUE TITLE
Reihenfolge im Eintrag umkehren

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#204]
http://betamasaheft.eu/Dillmann/lemma/Ld13ede78d0ac40e995e71bf0d9aa7a17

Ich konnte nicht die Reihenfolge ändern von 
1. TraCES > 1. Dillmann
2. Dillmann > 2.- TraCES

**Comment by SusanneHummel** [comment]
Dillmann sollte immer an erster Stelle stehen

**Comment by PietroLiuzzo** [comment]
close issue if it is now ok
