### ISSUE TITLE
complete list of new lemmata

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#205]
Is there a way to get the list of our own (or of the others) new lemmata? if I go to my name I get only those which have been revised.

**Comment by PietroLiuzzo** [comment]
could you please point me to an example lemma which you do not find in the list of your changes?

**Comment by PietroLiuzzo** [comment]
For the time being I have added a label NEW beside the lemma to mark those that are not in Dillmann also in the revisions list (which should include everything you have added or edited)

**Comment by PietroLiuzzo** [comment]
this is a derivate requirement from #203

**Comment by PietroLiuzzo** [comment]
please test in the NEW ENTRY view the new function available.
http://betamasaheft.eu/Dillmann/newentry.html
The check will be performed on keyup and paste.
The presence of matches will not prevent creation of lemmas. 
You can click on the matches to see what is the match.
