### ISSUE TITLE
missing ደብረ፡ and ሊባኖስ ?

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#207]
At the end of [page 1422](http://www.tau.ac.il/~hacohen/Lexicon/pp1421.html) there is a Monasteria (?) section, but after [ደፍራ](http://betamasaheft.eu/Dillmann/lemma/L0ff3a517be70416b9488111af3a7d8d5) from the previous section I find in the app directly [ማህው](http://betamasaheft.eu/Dillmann/lemma/Lcdc2a2e67b8b413eb6aa787a0eb89aa3).

Shouldn't there be (ደብረ፡) ሃሌሉያ and (ደብረ፡)ሊባኖስ? I don't find them.
As several others indeed which I would expect to be here.

**Comment by abausi** [comment]
These might still have to be entered: they were not originally planned. We discussed already this

**Comment by PietroLiuzzo** [comment]
I will leave it then to you to enter them when it is the time

**Comment by MagdaKrzyz** [comment]
I will introduce the entry

**Comment by MagdaKrzyz** [comment]
This is not the only entry that is missing from the list of proper names. It seems to me that all compound proper names (with the first component in status constructus) are missing. I have checked ያፍቅረነ፡ እግዚ,  ዐምደ ኢየሱስ and a few more --- none of them is there in the app. Could you check if I am right?

**Comment by MagdaKrzyz** [comment]
That is right, under ʿamd there is a cross reference to Amda Seyon. But there are missing entries from the section with proper names –- these that are compounds with the first component in status constructus.
