### ISSUE TITLE
column breaks 1412, 1416, 1419, 1423

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#208]
Konntest du bitte hier gucken was los ist?http://betamasaheft.eu/Dillmann/lemma/L497e392acbaf4bda8fbe7e417897ee86

mit die Spaltenumbruchen 1412, 1416, 1419, 1423 sollte ich ein bestes Ort nehmen, weil ich find nicht alles die ins  PDF steht.

**Comment by PietroLiuzzo** [comment]
#207

**Comment by eu-genia** [comment]
@MagdaKrzyz maybe add translation "Antiochian"? Dillmann did not need it as it is a continuation of entry Anṣokiya ->kiyawi (1418 bottom) but possibly in such cases the records could be completed?

**Comment by MagdaKrzyz** [comment]
done
