### ISSUE TITLE
entry ተመይጠ to correct

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Dillmann#209]
I have tried to correct through Dillmann App the structurie iof the entry: ተመይጠ፡ where there were 1, 3, 3, instead of 1, 2, 3.

At the end of 2, there is:

"በከመ፡ ተመይጦትከ፡ κατὰ τὴν ἐπίκειάν σου Or. Az. (Dan. 3) 18." (probably a difficulot sequence!)

And here comes 3:

3) reverti

In the attempt of correcting, I think I made it worse.

**Comment by PietroLiuzzo** [comment]
indeed it was not in a very good shape! please [have a look at the entry](http://betamasaheft.eu/Dillmann/lemma/Lc818b61b516745bf94bda22905dbd887) and close the issue if it is now fine

**Comment by abausi** [comment]
OK!
