### ISSUE TITLE
Falsche Ran-HaCohen Pdf-link wird angezeigt

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#213]
http://betamasaheft.eu/Dillmann/lemma/L494088bffc4b474fae23709ffa0386b2

Im Lexicon steht 495, aber die Weiterleitung geht richtig zu 493/494

**Comment by SusanneHummel** [comment]
es muss  im lexocon stehen: 494

**Comment by PietroLiuzzo** [comment]
die Spalteumbruch 495 ist da, man könnte es am Anfang des folgendes Lemma eingeben.
