### ISSUE TITLE
something is very wrong

### ISSUE THREAD

**Issue by palaspi** [BetaMasaheft/Dillmann#215]
Under the entry of "sam'a" (= to hear) the Arabic word سَمَعَ should be vocalised سَمِعَ

**Comment by PietroLiuzzo** [comment]
thank you @palaspi was this issue created by mistake or closed by mistake?

**Comment by palaspi** [comment]
Ciao PietroHo provato a creare un messaggio. Ma non so se ho capito bene come si fa. In ogni caso non è stato creato per errore. L'errore nel Dillmann c'è e va corretto.A prestoPaolo


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Pietro Liuzzo <notifications@github.com> Data: 27/01/18  05:44  (GMT+01:00) A: BetaMasaheft/Dillmann <Dillmann@noreply.github.com> Cc: palaspi <palaspi@gmail.com>, Mention <mention@noreply.github.com> Oggetto: Re: [BetaMasaheft/Dillmann] something is very wrong (#215) 
thank you @palaspi was this issue created by mistake or closed by mistake?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BetaMasaheft/Dillmann","title":"BetaMasaheft/Dillmann","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BetaMasaheft/Dillmann"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PietroLiuzzo in #215: thank you @palaspi was this issue created by mistake or closed by mistake?"}],"action":{"name":"View Issue","url":"https://github.com/BetaMasaheft/Dillmann/issues/215#issuecomment-360959860"}}}

**Comment by PietroLiuzzo** [comment]
Benissimo, grazie, allora riapro la issue, grazie ancora!

**Comment by PietroLiuzzo** [comment]
@palaspi che font e che browser usi? io qui http://betamasaheft.eu/Dillmann/?mode=none&q=audire&id=Lb42c0eb5dfd84352b0b9ce08627d65fe
vedo questo che mi pare sia come la versione corretta
<img width="788" alt="schermata 2018-01-27 alle 11 22 26" src="https://user-images.githubusercontent.com/508012/35471047-6d01c0c6-0354-11e8-8c80-8bcb9767c645.png">

**Comment by PietroLiuzzo** [comment]
thanks @AndreasEllwardt !

**Comment by palaspi** [comment]
Io uso Firefox, anyway... vielen danke Andreas!
