### ISSUE TITLE
some edits are saved with dba account instead of user

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#216]
Pietro,  I had the same problem in Dillmann as last week: some of the entries created or revised today appear under your name. If I go in fact on "Hy Vitagrazia" , the changes from today are not displayed at all and also the notifications via mail report that they have been made by you.

**Comment by PietroLiuzzo** [comment]
I have already updated on, but I am flying back to hamburg, I will not be able to fix the others. I would suggest completely clearing the cache of your browser.

**Comment by PietroLiuzzo** [comment]
btw: I see on your user page 5 changes from today. if you could point out the ids of the missing ones you would spare me to go through the mails when I am back to manually fix them. thanks

**Comment by vitagrazia81** [comment]
Ok, I have seen that you updated already some of them. 
There is still the following one: http://betamasaheft.eu/Dillmann/lemma/L3adec9dca49a4ca585a2c253d39b4d1d

**Comment by PietroLiuzzo** [comment]
I managed to fix this just before boarding, let me know if there are others. please consider clearing the cache of your browser to see if the problem is there.
