### ISSUE TITLE
Benachrichtigungen via E-Mail

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#217]
Auf einer TraCES-Sitzung hatten wir das Problem der großen Menge an Benachrichtigungen besprochen. Viele dieser Benachrichtigungen enthalten keine substantiellen Veränderungen im Lexikon, sondern Korrekturen von Schreibfehlern, Kommata etc. 
Bei den meiste von uns ist es daher so, dass die Benachrichtigungen unbesehen gelöscht werden, und sie daher ihre Funktion verlieren. 
Es wäre daher sehr sinnvoll, wenn man als Bearbeiter selbst entscheiden könnte, ob man seine Kollegen über seine Änderungen informieren möchte. Alle Änderungen stehen ja ohenhin unter der Rubrik "Revisions".
So könnten auch die super vielen Benachrichtigungen von Leo wegfallen, die das Postfach extrem füllen und ein Bemerken anderer wichtiger Änderungen unmöglich macht. 

Konnte Magda nicht "assignen".

**Comment by PietroLiuzzo** [comment]
bitte entscheiden Sie zusammen was ihr mochtet als Nachrichten bekommen. @AndreasEllwardt kriegt keine. Die Freiheit an die Benutzer zu lassen halte ich als sehr gefährlich. Meiner Meinung nach es ist viel einfacher in eure eigene email software eine kleine Regel hinzufügen mit die Filter wie ihr es mochtet.

**Comment by SusanneHummel** [comment]
Ich denke, @AndreasEllwardt hat genau aus diesen gründen auch die Benachrichtigungen abgestellt (nicht weil er sie nicht lesen möchte)

**Comment by PietroLiuzzo** [comment]
bitte entscheidet ihr wie soll es gehen. Ich halte nur als sehr wichtig das es gibt Notifizierungen und das jemand kann die angucken.

**Comment by PietroLiuzzo** [comment]
The notifications have been removed for everyone. They will be sent to my account where they doo not disturb. You will only get thank you messages for your contributions. please use revisions to see what has been done on an entry.

**Comment by SusanneHummel** [comment]
This was not the change we intended. Because substantial notifacations are indeed important, also for consistency of the lexicon. I had it again on the agenda for our next TraCES Meeting. Lets just wait until next week.

**Comment by PietroLiuzzo** [comment]
exactely. This was the change to relief you all from so many emails. then when you will have a proper decision, then I will do my best to implement it starting from a reasonably clear description of the expected behaviour

**Comment by PietroLiuzzo** [comment]
please note that there is now in all events of update, creation and deletion a checkbox which will allow you to decide if to send a notification or not. This is of course a very dangerous behaviour which takes out of your control the edits being done by users, so by default I keep receiving everything. 

in your user page you will also find a link to the changes log as requested yesterday. unfortunately there was a bug in the logging which does not allow for past entries to be displayed in this table, but the future ones will with the correct link.
