### ISSUE TITLE
something is wrong with my Ethiopic transcription in 

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#223]
http://betamasaheft.eu/Dillmann/lemma/Lc5df1d93d73146d39aa6c28c8fee1772

Cannot solve it. Sorry!!!!

<Sen< >gez! taḥta > +praep.+, +adv.+ >en> below >, >en> under >, >en> beneath > >en> underneath >; with suffix pronouns the base is \*gez*ታሕቴ\* >gez! taḥte- > [page,572b]bm:leslau1987dic ((vid.)) \*gez*ታሕት፡\* B <1< >en>subject>, >en> subordinate> 
*gez*ወአዘዘት፡\* 
*gez*ለኵሉ፡\* 
*gez*መኳንንቲሃ፡\* 
*gez* እለ፡\* 
*gez*እምታሕቴሃ፡\*
>de>und> >de>gebot> >de>allen> >de>ihren> >de>untergebenen> >de>Würdenträgern> *Kebr. Nag.|23,21* [page, 15a l.9(ed.), 13 (transl.)]bm:Bezold1905KebraN
*gez*ከመ፡\* 
*gez*ናምልካ፡\* 
*gez*ኪያሃ፡\* 
*gez*ንሕነ፡\* 
*gez*ወእለ፡\* 
*gez*እምታሕቴነ፡\* 
>de>damit> >de>wir> >de>sie> >de>göttlich> >de>verehren>, >de>wir>, >de>unsere> >de>Untertanen> *Kebr. Nag.|51,7* [page, 55b l.12, (ed.) 44 (transl.)]bm:Bezold1905KebraN >1> {ND} >S>

**Comment by PietroLiuzzo** [comment]
Bitte guckmal ob es ist jetzt in ordnung

**Comment by SusanneHummel** [comment]
Danke! Ge'ez ist nun perfekt!
Aber nun kann ich leider nicht die Codierung für die deutsche Überstzung rausnehmen:

ich habe folgendes:

<Sen< >gez! taḥta > [[praep.+,+adv.+]] >en> below >, >en> under >, >en> beneath > >en> underneath >; with suffix pronouns the base is \*gez*ታሕቴ\* >gez! taḥte- > [page,572b]bm:leslau1987dic ((vid.)) \*gez*ታሕት፡\* B 
<1< >en>subject>, >en> subordinate>
 \*gez*ወአዘዘት፡\* \*gez*ለኵሉ፡\* \*gez*መኳንንቲሃ፡\* \*gez*እለ፡\* \*gez*እምታሕቴሃ፡\*
und gebot allen ihren untergebenen Würdenträgern *Kebr. Nag.|23,21* [page, 15a l.9(ed.), 13 (transl.)]bm:Bezold1905KebraN 
\*gez*ከመ፡\* \*gez*ናምልካ፡\* \*gez*ኪያሃ፡\* \*gez*ንሕነ፡\* \*gez*ወእለ፡\* \*gez*እምታሕቴነ፡\*
damit wir sie göttlich verehren, wir, unsere Untertanen
*Kebr. Nag.|51,7* [page, 55b l.12, (ed.) 44 (transl.)]bm:Bezold1905KebraN 

>1> {ND} >S>

und ich bekomme folgende Fehlermeldung:
<exception><path>/db/apps/gez-en/edit/edit.xq</path><message>exerr:ERROR Could not locate collection: /db/apps/gez-en/EditorBackups [at line 55, column 15]</message></exception>
