### ISSUE TITLE
concerning the new entry የአክል

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Dillmann#224]
This entry should not exist by itself; it should be under the verb አከለ, that has already the right and expected meaning ("b) etiam impersonaliter አከለ፡ vel የአክል፡ ( es beträgt )"); moreover, is there anyway to mark the transcritpion as non-Latin, so that there is no re-direction to the Latin dictionary, that does not make any sense? and again: the German translations in various places of this entry should be correctly marked and encoded; and the hierarchy/sructure of the entry is still to be adjusted.

**Comment by PietroLiuzzo** [comment]
this entry was already in the initial txt last year, but it can be easily removed and the changes you mentioned can all be done in the editor (there is no mark up for the transcription at the moment, that is why it links to the latin dictionary). all others are known issues which are being fixed as people meet them.

**Comment by PietroLiuzzo** [comment]
I fixed the nesting but I will let @vitagrazia81 do the rest (deleting the entry, moving its content to the existing one etc. this will have to be in a traces meaning added to the existing one rather than in the main Dillmann entry IMHO, but it is for you to decide of course.

**Comment by vitagrazia81** [comment]
Yes, Alessandro, as Pietro said already, this entry was imported as it was from the initial txt list. It needed to be revised.  I did it now. In Marrassini, the word የአክል፡, together with ጋዳ፡ is a personal name. So, now, in Dillmann, there is the new entry (TraCES) where as lemma there are both words together የአክል፡ ጋዳ፡ : http://betamasaheft.eu/Dillmann/lemma/L8d7a3e3121ae418d81913cb36b342df3 .  Then, under the already existing lemma አከለ (1, b), as you suggested, I added a new meaning from TraCES where I said that this word, in Marrassini, is part of a personal name and I gave the link to the new lemma የአክል፡ ጋዳ፡ http://betamasaheft.eu/Dillmann/lemma/L5533b41e9c4d417db72b8b620c99dd53.  Also under the already existing lemma ጋዳ I added a new TraCES meaning where there is the link to the new lemma የአክል፡ ጋዳ፡ http://betamasaheft.eu/Dillmann/lemma/L19e13824b9f44815a976f218cde631c3.

**Comment by abausi** [comment]
thank you, Vitagrazia,

we can close this issue.

Il 05.03.2018 14:21, vitagrazia81 ha scritto:
