### ISSUE TITLE
links to perseus latin word study tool contain ] and ;

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Dillmann#226]
first in the translation, after the Latin word "vestis]" needs to be a space between vestis and ], Second after
 "vestis;" needs to be a space between vestis and semicolon

http://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8C%BD%E1%8A%95%E1%8D%88&id=Lbde5a52089154f60b7a9c92dd8cd8495

**Comment by PietroLiuzzo** [comment]
why?

**Comment by SophiaD-M** [comment]
because if you click on the words, the Latin dictionary shows no result - I thought it is because the space is missing?

**Comment by SophiaD-M** [comment]
"Sorry, no information was found for vestis]."

**Comment by PietroLiuzzo** [comment]
then the issue is different.

**Comment by SophiaD-M** [comment]
well, I am not the expert

**Comment by PietroLiuzzo** [comment]
just renamed it, thanks for the notification!

**Comment by SophiaD-M** [comment]
sounds much more fancy now! Thank you

**Comment by PietroLiuzzo** [comment]
also in item view

**Comment by PietroLiuzzo** [comment]
auch comma
