### ISSUE TITLE
some guidelines for editing in  Dillmann app

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#227]
Since Pietro asks us to provide guidelines for Dillmann, I collected and reformulated some of them in the document which I send you here.   Before he uses and he integrates them in the dictionary, it would be better if you have a look, in case you find something to be corrected, etc.  Anyway, most of the guidelines written have been already discussed in previous meetings and were already present in a document with the Minutes (created by Susanne, put on Agora, and updated after each meeting on Dillmann). 

N.B. On the document, you find some parts in red: these are some points which need (among many others) to be discussed.  For instance, about the terminology, as we agreed that we can use "personal name" and "place name", to specify a n.pr., we would need to agree also on the label to use for other nomina propria. In some of my entries, I used for instance: "name of regiment", "role name" "name of plant", the first two already used in Beta Masaheft. 

[Rules for the guidelines.docx](https://github.com/BetaMasaheft/Dillmann/files/1807112/Rules.for.the.guidelines.docx)

**Comment by vitagrazia81** [comment]
Correction:  "role name" and "name of plant" have not been  used after n. pr., so not as nomina propria.

As an example of "role name" and "name of  plant", see e.g. the entries,  ማእከል (http://betamasaheft.eu/Dillmann/lemma/L2ffdf5c9580545c9a8b89a10165e18c3) and ጫት፡(http://betamasaheft.eu/Dillmann/lemma/Lbb9ee30da369427bb6e02ed09e53f5ee).

**Comment by abausi** [comment]
At best: provide a positive proposal for whatever has to be discussed: in a way, do not pose any question, without suggesting a preliminary proposal how to solve the issue. We will then discuss the case if this proposal is not accpeted by others or if if you do not absolutely have any proposal at all. Again, at best, as you did, have a look at what has been done in BM and let's avoid to pose the same question several times. Most important is that someone (maybe you at this point) takes care of orgaqnizing all guidelines in a coherent way.

**Comment by vitagrazia81** [comment]
I send you the guidelines for editing in Dillmann app updated: 
[Rules for the guidelines.docx](https://github.com/BetaMasaheft/Dillmann/files/1855581/Rules.for.the.guidelines.docx)

**Comment by PietroLiuzzo** [comment]
- [ ] Add guidelines to wiki
- [ ] Add link from the app to the editorial guidelines only for editors

**Comment by PietroLiuzzo** [comment]
@vitagrazia81 please have a look in the wiki, I have copied there the text of the latest doc. In the conversion to markdown (the synthax used by the wiki) I had to do a bit of tidying up of the structure moving from top level nested lists to sections, I also included all the examples in the numeration, thus including those in section I.2 . I have the feeling that the word guidelines might be ambiguous and it could be specified if it is refering to the editor guidelines, which have been renamed "Data entry support" exactly to avoid this confusion, or to the "tutorial". 

Where should I add in the app the link to this guidelines?

**Comment by vitagrazia81** [comment]
You did well. Thank you Pietro. I don't know where to add the link in the guidelines. Can it be put under "Tutorial"?
