### ISSUE TITLE
online DL Abbrev.: underspecified abbrev. "Cyr." = Qerellos (LIT3309Qerellos)?

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#23]
- in the Sigla of printed DL there is: "Cyr." - "Cyrilli Alexandrini scripta (de recta fide; ad Reginas; ad Theodosium; colloquium cum Palladio; Homiliae; Epistolae)" > this is a too broad reference as their are lot's of Cyrillians writings and compilations of writings attributed to him (18 writings in the standard Qerellos collection, not all listed by DL Sigla; same texts found in other compiled theological works of Ethiopian Lit.); 
- I opted simply for: "Cyr." = LIT3309Qerellos; is this correct? 
reason: one section mentioned in the Sigla list is: "Dialogue with Palladius on the Unity of Christ" (LIT3312Unity), which is one part of the Qerellos compilation(s) 
(- the alternative could be the "Testimonies by Cyril of Alexandria" from the Hāymānota ʾabaw (LIT3410Cyril))

**Comment by MassimoVilla** [comment]
Your assumption is right, "Cyr" indicates the Qerǝllos = LIT3309Qerellos (cp. col. VII, first lines, in the Prolegomena of Dillmann's Lexicon).
For the Hāymānota ʾabaw, which is indicated as "H.A.", see col. IX, d.)
