### ISSUE TITLE
ምጕንጳ

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#230]
Liebe rPietro,

kannst du für diesen Eintrag bitte die Version von gestern wieder herstellen?

Danke

Liebe Grüße

Susanne

**Comment by PietroLiuzzo** [comment]
There are three revisions from 14.3, which one do you want to restore?

**Comment by SusanneHummel** [comment]
Somehow my answer to your question was not delivered; hiwever, could you please restore the last version of that day?
