### ISSUE TITLE
Seitenumbruch

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#231]
http://betamasaheft.eu/Dillmann/lemma/Lbcd379039f96460a9639447e739e3293

Der Seitenumbruch ist für dieses Lemma nicht richtig, obgleich die Marker alle richtig gesetzt sind

**Comment by PietroLiuzzo** [comment]
ich verstehe nichts was du meinst. was soll anders aussehen?

**Comment by SusanneHummel** [comment]
schauen wir uns dann einfach zusammen an.

Am 15.03.2018 um 20:51 schrieb Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
noch relevant  @SusanneHummel ?
