### ISSUE TITLE
links to Lane Lexicon

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#235]
@abausi  wrote:

There is also the online Lexicon of Lane:

http://lexicon.quranic-research.net/

We should think of linking the Arabic in our TraCES Lexicon to Lane, as we do for the other languages.

**Comment by PietroLiuzzo** [comment]
@abausi unfortunately I do not see any immediate way to do this. there is no search taking a simple parameter which I can use as for perseus. this might become possible when this feature will be developed

**Comment by abausi** [comment]
Just let's keep this in mind for the future
