### ISSUE TITLE
bm:tag pointers

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#239]
There are still several bibliographic ids used in the data which are wrong. This is potentially damaging also all other users of the zotero library.

**_Please fix them as soon as possible updating the data and the Zotero library._**

- bm:LittmannHöfner1962Tigre
- bm:Yaqob1927Säwasew
- bm:Getachew2005Gwǝnṣ
- bm:AläqaTayyä1965MSäwasew
- bm:KidaneWäldGeezGramDict
- bm:Käśate1957DictAmh
- bm:Dästa1969AmhDict

I have clarified this point in the data entry guidelines for your reference, [see point 31 here](https://github.com/BetaMasaheft/Documentation/wiki/zoteroguidelines)

**Comment by MagdaKrzyz** [comment]
Dear Pietro,
Thanks!
 I have changed all of them in Zotero and will chenhged them in the entries


2018-03-16 12:27 GMT+01:00 Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
Thanks, please this needs to happen really as soon as possible.

**Comment by PietroLiuzzo** [comment]
<ul>
    <li>bm:LittmannHöfner1962Tigre occurs in
<ul>
            <li>L6e59df67af524323a15864ae178a5765</li>
            <li>L75c5c27373774bef89f1be47f7f93d59</li>
            <li>L75c5c27373774bef89f1be47f7f93d59</li>
        </ul>
    </li>
    <li>bm:Yaqob1927Säwasew occurs in
<ul>
            <li>Lef92de76e6aa46838abe6eda300cd4b1</li>
        </ul>
    </li>
    <li>bm:Getachew2005Gwǝnṣ occurs in
<ul/>
    </li>
    <li>bm:AläqaTayyä1965MSäwasew occurs in
<ul>
            <li>L85b3c4f6c76249c18d244c9c5471ba1d</li>
            <li>L41f0c9ea209d4ab1a537ea170dcbbd2f</li>
            <li>Lef92de76e6aa46838abe6eda300cd4b1</li>
        </ul>
    </li>
    <li>bm:KidaneWäldGeezGramDict occurs in
<ul>
            <li>L9a198aea21904af98ff36bdf9f5a7717</li>
            <li>L85b3c4f6c76249c18d244c9c5471ba1d</li>
            <li>L9a28815369f946a3b9f06f7d44ea08da</li>
            <li>Le1f641d24d4e4550a967b7e9e6403f31</li>
            <li>Lf894d5d9d6094d5ca7cab30328db41ad</li>
            <li>Lc3932a36362f4d12a8b74221fee77543</li>
            <li>Laf1a9e0ea873446abdecfc63e6471a96</li>
            <li>L079ff94690e74d26ba8d2cf34de0de62</li>
            <li>Lbb2780fee3854308acc711e2960c8e88</li>
            <li>L09ab91707730434391f9ecccddeef99a</li>
        </ul>
    </li>
    <li>bm:Käśate1957DictAmh occurs in
<ul>
            <li>Lf42de30c0e9246fc9a08a2f82cce98f9</li>
        </ul>
    </li>
    <li>bm:Dästa1969AmhDict occurs in
<ul>
            <li>L6e59df67af524323a15864ae178a5765</li>
        </ul>
    </li>
</ul>

**Comment by MagdaKrzyz** [comment]
These links are invalid. The rest is done.

L6e59df67af524323a15864ae178a5765

L9a198aea21904af98ff36bdf9f5a7717

Le1f641d24d4e4550a967b7e9e6403f31

Lc3932a36362f4d12a8b74221fee77543
Laf1a9e0ea873446abdecfc63e6471a96
Lbb2780fee3854308acc711e2960c8e88
L09ab91707730434391f9ecccddeef99a
L6e59df67af524323a15864ae178a5765


2018-03-16 13:08 GMT+01:00 Pietro Liuzzo <notifications@github.com>:

**Comment by MagdaKrzyz** [comment]
Pietro,
all is done.
m

2018-03-16 13:50 GMT+01:00 Magdalena Krzyżanowska <magdalena.krzyz@gmail.com

**Comment by PietroLiuzzo** [comment]
Thank you very much Magda!
