### ISSUE TITLE
problem in the cross reference 

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#241]
In the entry የአክል፡ ጋዳ፡, as cross reference I give the words II አከለ፡ , ጋዳ, but if I click on the first it does not  go to the right entry II አከለ፡, but to II ራኩብ፡, and if I click on the second it goes again to the entry  የአክል፡ ጋዳ፡

link for የአክል፡ ጋዳ፡:
http://betamasaheft.eu/Dillmann/lemma/L8d7a3e3121ae418d81913cb36b342df3

**Comment by vitagrazia81** [comment]
The cross reference to II አከለ፡ is now correct; the second is still mistaken. It goes to  የአክል፡ ጋዳ፡ and not the single entry. The problem can be that there are two  Dillmann entries for ጋዳ፡, and one single for TraCES (which, by the way, since I added a Traces meaning with this word to the one to Dillmann, I deleted several times, but still appears)?

**Comment by PietroLiuzzo** [comment]
I don't understand.
- please provide the id of the lemma which should not be there (the one you have tried to delete)
- in the lemma above, the link from ጋዳ፡ goes to http://betamasaheft.eu/Dillmann/lemma/L92358dd642c44c289e7772e92d9815c5 is this not fine?

**Comment by vitagrazia81** [comment]
This is the one that has to be removed:
L92358dd642c44c289e7772e92d9815c5

**Comment by vitagrazia81** [comment]
this is a partial entry 
http://betamasaheft.eu/Dillmann/lemma/L9f503afee28349fd816e24b0f32f6ac9
equal to the first part of 
http://betamasaheft.eu/Dillmann/lemma/L19e13824b9f44815a976f218cde631c3
