### ISSUE TITLE
Dillmann: two entries for the same lemma.

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#242]
two separated Dillmann entries for ጋዳ፡ 
http://betamasaheft.eu/Dillmann/search.html?q=%E1%8C%8B%E1%8B%B3%E1%8D%A1

**Comment by AndreasEllwardt** [comment]
http://betamasaheft.eu/Dillmann/lemma/L9f503afee28349fd816e24b0f32f6ac9 ist  
ein Querverweis



Zitat von vitagrazia81 <notifications@github.com>:

**Comment by vitagrazia81** [comment]
yes, you are right. Now I have seen it on the printed Dillmann. But, on line, if you go on the word ገደወ፡ the word ጋዳ፡ is not there, but considered another lemma (the next one).

**Comment by AndreasEllwardt** [comment]
that is how it works... throughout the whole app... I'm sorry!


Zitat von vitagrazia81 <notifications@github.com>:

**Comment by vitagrazia81** [comment]
@PietroLiuzzo asks what is the difference between

http://betamasaheft.eu/Dillmann/lemma/L9f503afee28349fd816e24b0f32f6ac9
 and
http://betamasaheft.eu/Dillmann/lemma/L19e13824b9f44815a976f218cde631c3

He would expect the first not to be there at all

**Comment by PietroLiuzzo** [comment]
I was one click away.... now I have understood L9f503afee28349fd816e24b0f32f6ac9
