### ISSUE TITLE
Absätze in der PDF

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#245]
Wäre es möglich in der PDf eines LexiconEintrags Absätze einzufügen?

z.B. TRaCES en
oder nun auch Leslau "L" sollen einen eigenen Absatz haben, damit der Eintrag übersichtlich ist.

**Comment by SusanneHummel** [comment]
Hier als Beispiel
http://betamasaheft.eu/Dillmann/lemma/L774fc8992be94e4eacc122303fe6a315

**Comment by PietroLiuzzo** [comment]
nach issue #230, dieses ist eines besseres Beispiel http://betamasaheft.eu/Dillmann/lemma/L177552431ad04d80b233f540f4cae270
geht es so?

**Comment by SusanneHummel** [comment]
schon fast perfekt! Wäre es möglich, noch etwas mehr Platz zwischen den Absätzen einzubauen?

**Comment by PietroLiuzzo** [comment]
ich hab 3mm eingegeben, ich kann es einfach ändern

**Comment by SusanneHummel** [comment]
das wäre toll

**Comment by PietroLiuzzo** [comment]
ich meine es ist schon so, bitte guckmal ob du brauchst mehr und lass mich wissen wie viel.

**Comment by SusanneHummel** [comment]
perfekt. Danke!!!
