### ISSUE TITLE
Suche nach zotero tag

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#246]
Ich wollte nach einem falschen Zozero Tag suchen und habe 

"Bezold", "1909" und sogar beides zusammen "Bezold 1909" gesucht, aber nciht gefunden. Es ist nicht möglich, nach den zotero-Tags zu suchen?

**Comment by PietroLiuzzo** [comment]
nein, das braucht eine neue index und eine neue suche Funktion. braucht ihr wirklich das? bitte entscheidet ihr morgen zusammen und lass mich hier wissen.

**Comment by SusanneHummel** [comment]
ich denke schon; es ist sehr wichtig.
Aber ich frage morgen in der Sitzung

**Comment by PietroLiuzzo** [comment]
Im Moment das Total von bibliographische Referenzen spricht nicht für diese Bedürfnis, aber vermutlich wird dieses Total erhöhen, und auch die Moglichkeit geben nur was eine bestimmte Quelle hat zu sammeln. 
Hier du willst für eine citate suchen. ich kann 
- eine liste von alle bibliographische Referenzen machen, und die möglichkeit geben alle lemmas wo das benutzt ist anbieten 
ODER
- die möglichkeit ins tags zu suchen anbieten.
Die erste scheint mir besser zu sein. 
Trotzdem, genau deine probe hier wurde nicht möglich werden, denn "Bezold 1909" ist nur in dein browser visualisiert.

**Comment by PietroLiuzzo** [comment]
see the new http://betamasaheft.eu/Dillmann/bibl.html
