### ISSUE TITLE
the bibliographical tagging is still very confused

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#251]
Please look at the list below, which is also printed in the data entry help section of the editor page, which contains all the zotero tags used in the Dillmann.

There are some double, triple, or quadruple entries which are seemingly wrong. e.g. Ludolfus1691Commentarius.

Somebody has to check which one in this list are actually the correct tags. I will then give you a list of the entries where the wrong ones occur so that you can fix them.

bm:DaBassano1918DictTgr
bm:Yohannis1955TigrAmhDict
bm:Guidi1901Vocabolario
bm:Kane1990DictAmhVol2
bm:Lusini1996AbsadiII
bm:Ludolf1691Commentarius
bm:Dillmann1857Gramm
bm:daMag1953
bm:Bezold1905KebraN
bm:Getatchew2011EstifanosTr
bm:Marrassini1993AmdaSeyon
bm:Tedros2009TawaldaMadehnVittore
bm:Ludolf1691Commentariusp
bm:Leslau1987dic
bm:leslau1987dic
bm:Dillmann1865Lexicon
bm:Missal1995
bm:Kane1990DictAmhVol1
bm:Perruchon1893Zarayaeqob
bm:Wendt1963MiladT
bm:Getachew1991EpistleOfHumanityV
bm:Kane2000DictTgrVol1
bm:Getachew2006EstifanosT
bm:Getachew2006EstifanosV
bm:Getatchew2011EstifanosEd
bm:Getachew2005Gwǝnṣ
bm:Kur1968SamuelT
bm:ContiRossini1910Abakerazun
bm:Getachew2006Estifanos
bm:Caquot1961EzraGundaGunde
bm:Ludolf1691Commentariusad
bm:ContiRossini1964BerhanT
bm:ContiRossini1965BerhanITrad
bm:Ludolf1681Historia
bm:MunzingeriVocabTigr
bm:Raineri2000Comb
bm:Tedros2007Demyanos
bm:Ludolf1691Commentariushist
bm:Marrassini1983Matyas
bm:Perruchon1889Amda
bm:Lusini1996Absadi
bm:Ludolf1681HistoriaAe
bm:Ludolf1681HistoriaAeth
bm:Perier1912Canons
bm:Dillmann1866Chrestomathia
bm:ContiRossini1937YafqerannaEgzi
bm:Ricci1954Enbaqom
bm:Ricci1955Enbaqom
bm:Ludolf1681Historiacomm
bm:Ludolf1681HistoriaI
bm:Turaev1902Filipos
bm:Wendt1963MiladV
bm:KidaneWaldGeezGramDict
bm:AlaqaTayya1965MSawasew
bm:Girmatsion1983DictTgr
bm:Marrassini1986IyasusMoa
bm:Bassano1922BiluyKidan
bm:Colin2002Bsoy
bm:Strelcyn1973Medecine
bm:Grebaut1952SuppLexicon
bm:Cerulli1956KrestosSamraV
bm:Cerulli1956KrestosSamraT
bm:ContiRossini1938BurukAmlak

**Comment by eu-genia** [comment]
at least for Ludolf must be

bm:Ludolf1691Commentariushist ---> bm:Ludolf1691Commentarius
bm:Ludolf1691Commentariusp ---> bm:Ludolf1691Commentarius
bm:Ludolf1681HistoriaAe ---> bm:Ludolf1681Historia
bm:Ludolf1681HistoriaAeth ----> bm:Ludolf1681Historia
bm:Ludolf1681HistoriaI ----> bm:Ludolf1681Historia
bm:Ludolf1681Historiacomm ----> bm:Ludolf1691Commentarius
bm:Ludolf1691Commentariushist ----> bm:Ludolf1691Commentarius


bm:leslau1987dic --->bm:Leslau1987dic

**Comment by eu-genia** [comment]
bm:Getachew2005Gwǝnṣ ----> bm:Getachew2005Gwents

**Comment by SusanneHummel** [comment]
thanks Zhenia. Sibylla will check the l.ist. There are some more wrong tags.

**Comment by wdickhut** [comment]
The tags are correct, except the following:

bm:Ludolf1691Commentariusp   => bm:Ludolf1691Commentarius
bm:leslau1987dic   =>   bm:Leslau1987dic
bm:Wendt1963MiladT   [=>   Der Tag führt immoment zu drei Bänden, ist zu differenzieren nach T und V und Bd. 1 und Bd. 2]
bm:Getatchew2011EstifanosEd   OK   [=> Der Tag ist ggf. zu ändern in bm:Getatchew2011EstifanosT, entsprechend auch beim Versio-Bd.?]
bm:Getachew2005Gwǝnṣ   =>   bm:Getachew2005Gwǝnts   [oder zu korrigieren?]
bm:ContiRossini1910Abakerazun   OK   [aber dem Tag fehlt das V; vgl. auch bm:ContiRossini1910TaklaHawaryat]
bm:Getachew2006Estifanos   => bm:Getachew2006EstifanosT oder bm:Getachew2006EstifanosV
bm:Ludolf1691Commentariusad   =>   Ludolf1691Commentarius
bm:ContiRossini1965BerhanITrad   OK   [Trad => V?]
bm:Ludolf1691Commentariushist   =>   bm:Ludolf1691Commentarius
bm:Lusini1996Absadi   OK   [ggf. der Tag zu ändern?, vgl. auch bm:Lusini1996AbsadiII]
bm:Ludolf1681HistoriaAe   =>   bm:Ludolf1681Historia
bm:Ludolf1681HistoriaAeth   =>   bm:Ludolf1681Historia
bm:Ludolf1681Historiacomm   =>   bm:Ludolf1681Historia
bm:Ludolf1681HistoriaI   =>   bm:Ludolf1681Historia

**Comment by wdickhut** [comment]
(But probably Zhenia is right in correcting
bm:Ludolf1681Historiacomm   =>   bm:Ludolf1691Commentarius!)

**Comment by PietroLiuzzo** [comment]
I need a list of the wrong ones, so that AS SOON AS POSSIBLE someone of you can go through all of them and fix them

**Comment by PietroLiuzzo** [comment]
A kind but strongly felt (hence the upper case) reminder/warning about the use of Zotero tags:

https://betamasaheft.github.io/bibliography/

ES IST NOTWENDIG DAS BEIM ARBEITEN MIT BIBLIOGRAPHY ALLE DIE REGELN HIER GESAMMELT SIND GANZ GENAU BEACHTET. 
https://betamasaheft.github.io/bibliography/

IT IS EXTREMELY IMPORTANT THAT WORKING WITH THE BIBLIOGRAPHY ALL THE RULES WHICH ARE COLLECTED HERE ARE CAREFULLY FOLLOWED.
https://betamasaheft.github.io/bibliography/

Especially for this issue:
CHANGING TAGS RESULTS IN PROBLEMS ALSO FOR BETAMASAHEFT and AETHIOPICA, NOT ONLY FOR DILLMANN. 

TAGS ASSIGNED IN THE ZOTERO GROUP LIBRARY SHOULD BE CHANGED ONLY IF THERE IS A DOUBLE or IF SOME WRONG CHARACTER HAS BEEN USED.

TRYING TO HOMOLOGATE THE FORMAT OF THE TAGS IS ONE OF SUCH CHANGES AND BRINGS NO GOOD. THE ONLY POINT WHICH MATTERS IS THAT THOSE TAGS ARE UNIQUE IN THE GROUP LIBRARY. 

PLEASE ASK IF THERE ARE THINGS WHICH ARE NOT CLEAR IN THIS PART OF WORKFLOW. 

**_PLEASE DO NOT CHANGE TAGS IN THE ZOTERO LIBRARY UNLESS YOU HAVE FULL CONFIDENCE IN WHAT YOU ARE DOING AND YOU ARE ABLE TO UPDATE ALL THE DATA ACCORDINGLY BOTH IN DILLMANN AND BETAMASAHEFT._** AS SOON AS YOU DO THAT.

**Comment by PietroLiuzzo** [comment]
The wrong tag <b>bm:Ludolf1691Commentariusp</b> occurs in
- Lf0b49c72a671465bb6b5de41be113b18
- L46836496ad7b4239855ba274c5a77199
- L5b251504c85d447eb2502bcd272fd0d5

The wrong tag <b>bm:leslau1987dic</b> occurs in
- L2862c77046e54fb1923a433bec85ab5e
- L807c7a0603ba4808b969b119f942987f
- Lb498a1bb1c7542f9a7e34e7c2c73b087
- Lcee74f62cdf844529933422afab03f04
- Lf2ffe98c78934781a46398b498a5d6cc
- Lc98b14bfa0f14cd1883f2ef5b32c2bd6
- L774fc8992be94e4eacc122303fe6a315
- L412f367b57104bfe9b119ec34ee566da
- Lbe6365dd79194ec6bce6963cb12856bd
- Lba0dac4ee7f54f28910b8f2947a21c38
- L60fbb31402294242b8033bf4ce25e73c
- L0bc6ac11ab2c41fd8026fe90ad3cd405
- L3fbaf81d2fd64843ac39106c379160b4
- L8b5ca93bbeff41c9b96fcefdb3f161d5
- Lc5df1d93d73146d39aa6c28c8fee1772
- L41bfd7bdaf604144a529eedba46767f4
- Ld62a16964c344d679f0cc5bd27f364e4
- L52d4bf12a5a741c2af7d744df2193391
- Lbcd379039f96460a9639447e739e3293
- L79193c3ea1204939939fc26d00fb48c2
- Lf4bbf4ddc232463c9dabfb6b2a5c9a7d
- L7ecf22f11a7d47f8ac3da911eab58005
- L85b3c4f6c76249c18d244c9c5471ba1d
- L0607cf958ff44efeaba93961c88daeb4
- L5be2bca03c6e43f4a81dce4d9b85a641

The wrong tag <b>bm:Wendt1963MiladT</b> occurs in
- Laf1a9e0ea873446abdecfc63e6471a96
- Lc05794d6eb2d4b768267a998a9f600ae

The wrong tag <b>bm:Getatchew2011EstifanosEd</b> occurs in
- L6b9e5ecc5fc742d48a9061bb5cfdec42
- L65ae0746b7f9428da90682226ae6cc75
- L55c235440de4412580899f827f7a7d26

The wrong tag <b>bm:Getachew2005Gwǝnṣ</b> occurs in

The wrong tag <b>bm:ContiRossini1910Abakerazun</b> occurs in
- L65ae0746b7f9428da90682226ae6cc75

The wrong tag <b>bm:Getachew2006Estifanos</b> occurs in

The wrong tag <b>bm:Ludolf1691Commentariusad</b> occurs in
- L230e643ed04947658c9dbbf44df1cc7d
- L2bc8a52fb41542338699de2ae18556aa

The wrong tag <b>bm:Ludolf1691Commentariushist</b> occurs in
- L29c62053004c428a8c9a4c9c6ba458ab
- L60c086f9374a4ebabffa5f33109328d0
- L57b10f54a15e4ab9810cd59bcfca0f21
- L024c24a7a48941b996cab11bc2174dd6
- L90dc82bb08574bc286cfab16be49ce04
- L5cffa7d4165b421a87a932e037becffc
- L97d697c4e39c4cb8b020d7ee01642982
- Lcba810f55ab849d3adf1dd7a62deb266
- La377804ce5694f77bbe460d23d19fd70
- Lff31c3a797a3443698090ff81bf16c38
- L4092f9096746407682a6e709316e7e9f

The wrong tag <b>bm:Ludolf1681HistoriaAe</b> occurs in
- Lc09e89f3e0b2440994c64ac361db2ba4
- L13eef6307c854945bc2b383014286391
- L015fb11cc2a74db1816932c3e52e2874
- L08d1a717fdd34f71be37b31b6aaf0c49
- L05890b81ae90463aacac5c2cf7a048b2
- Lb397a79ff4b342d1a186f55c1e10917c
- L634bb47d7c144e9aaf5d8babff99d8ab

The wrong tag <b>bm:Ludolf1681HistoriaAeth</b> occurs in
- L8a725dbded5f4a1c9f69005cc0e363f2

The wrong tag <b>bm:Ludolf1681Historiacomm</b> occurs in
- Ld6b825418be3449294c090c4c475a0cc

The wrong tag <b>bm:Ludolf1681HistoriaI</b> occurs in
- Ld4613007a13b408995953f0425a46e02
- L9f789a5affed4e16ab5c95e881875e13
- Lc4c20ba1cc4f46e29067eada5f1c04fd
