### ISSUE TITLE
((vid.)) linking to the first option if two are available

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#255]
This message concerns the entry በረከት 
http://betamasaheft.eu/Dillmann/lemma/L4b9b4dfc2fbf4553b23412c6d8f455e9

I want to give a cross-reference to the word ኅብስት፡. Because there are two entries ኅብስት፡ 
http://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%85%E1%89%A5%E1%88%B5%E1%89%B5%E1%8D%A1&id=L8e6e9263080a421bbe0b05e0f0b0bbd1 (the right one)

http://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%85%E1%89%A5%E1%88%B5%E1%89%B5%E1%8D%A1&id=L77587dad34b943e6985926cf6b4925df (that which I don't want)

the app directs the user to the second one, which is not required. How this can be changed? Thank you for your help.
Magda

**Comment by PietroLiuzzo** [comment]
this is a known issue see e.g. 122 
once I will add the possibility to add a direct link (part of what is also in #82 ), you will use vid only as a short cut and will be able to provide a direct link in the data, at the moment this is not possible
