### ISSUE TITLE
Automatische Verlinkung bei "Hinc"

### ISSUE THREAD

**Issue by wdickhut** [BetaMasaheft/Dillmann#258]
Derzeit wird bei "Hinc" (aber nicht "hinc") automatisch der folgende entry verlinkt, was teilweise zu Fehlern führt, e.g.: http://betamasaheft.eu/Dillmann/lemma/L8c903bae21a9467587a937c5e1adc53e

**Comment by PietroLiuzzo** [comment]
I need some explanation of the error which occurrs
