### ISSUE TITLE
comparison printed DL Sigla & online DL: abbrev. "Epist. Zar'a Jac." - add new abbrev. & LIT ?

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#26]
- in printed DL, there is the abbrev.: "Epist. Zar'a Jac." = Epistola Zar’a Jacobi regis, in Ludolfi Comm. Hist. p. 301 seq.; however, in online DL I did not find a lemma with a reference to it; 
- as it is a reference to a printed text, should it get a LIT reference no.? (text of course coming from a ms. source) 
- I could not find a reference to this particular work attributed to emperor Zär'a Ya'eqob. Could it be added, please?

**Comment by fitawari** [comment]
- the incipit is: [after doxology and invocation] ተጽሕፈት ፡ ዛቲ ፡ መልእክት ፡ ውስተ ፡ ዛቲ ፡ መጽሐፈ ፡ ሴኖዶስ ፡ አምኀቤነ ፡ ዘርአ ፡ ያዕቆብ ፡ ወስመ ፡ መንግሥትነ ፡ ቈስጠንጢኖስ ። "Inscripta est haec epistola huic libro Canonum per nos Zera-Jacobum, & nomen regni nostri (est) Constantinus." (Ludolf, Ad suam ..., pp. 301-304, = No. XXX. De Codice Conciliorum & Canonum Aethiopico.) 
- manuscript base: Frankfurt Ethiopian mss. collection, Ms. 23 in Goldschmidt Catalogue, sub text no. 16 "Brief des Kaisers Zara Jacob, der mit dem das äthiop. Concilienbuch beginnt." = Ms. Ff. H. Ludolf II 22 - Collectanea Aethiopica 
http://sammlungen.ub.uni-frankfurt.de/msorient/content/titleinfo/5411278 (cf. pag. 290)

**Comment by MassimoVilla** [comment]
I would tentatively link this work to the Ṭomāra tǝsbǝʾǝt (= LIT2474tomara). This work has been edited more or less 25 years ago by Getatchew Haile:  Getatchew Haile (ed., tr.), The Epistle of Humanity of Emperor Zärʾa Ya'ǝqob (Tomarä Tǝsbǝʾt), Louvain 1991 (CSCO 522, 523 [SAe 95, 96]). I do not have it at hand to check the incipit, but it is in the library.

**Comment by MassimoVilla** [comment]
Anyway, there is a long contribution by Dillmann on Zärʾa Ya'ǝqob's writings. It might be illuminating:
A. Dillmann, _Ueber die Regierung insbesondere die Kirchenordnung des Königs Zar´a Ya´qob_. Berlin, 1884 ("Abhandl. d. K. Akademie d. Wissensch.").

**Comment by MassimoVilla** [comment]
Contrary to my previous comment, I now believe the work is to be added to the BM database.
I just read on Ludolf's Commentarius (http://reader.digitale-sammlungen.de/de/fs1/object/goToPage/bsb10867109.html?pageNo=388) that the manuscript was inspected in Rome "in hospitio Habessinorum" (= Santo Stefano dei Mori) and that it should be still preserved in the Vatican Library. So, the question is to identify the current shelfmark of the manuscript in the BAV.
I think we can use **LIT4544Epistle**. I am creating the record.

**Comment by PietroLiuzzo** [comment]
heads up on creating new records: https://github.com/SChAth/ScAthiop/issues/341
