### ISSUE TITLE
or.

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#261]
@AndreasEllwardt has written me via skype:

im Dillmann kommt 12 Mal "or." vor, aber die Suche findet kein einziges.

**Comment by PietroLiuzzo** [comment]
@AndreasEllwardt or. wie in Az. Or.? welches or. ? Hast du ein Beispiel bitte, wo "or." sein sollte?

**Comment by AndreasEllwardt** [comment]
Ich korrigiere grad die Abkürzungsliste, und da kommen verschiedene  
"or." vor, Or. Az. hab ich über Az. gefunden, aber Or. Jon. nicht, und  
all die anderen...



Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by AndreasEllwardt** [comment]
Also: in Deiner Abkürzungsliste findet sich eine Reihe von Abkürzungen  
im Stile von Or._xxx. Interessanterweise führt Dillmann diese in  
seinem Abkürzungsverzeichnis jedoch nicht auf. Sie sind aber durchaus  
da, wie eine Suche in der txt-Datei beweist. Eigenartig ist halt eben,  
daß diese Suche in der App erfolglos bleibt. Das ist vielleicht völlig  
egal, mir aber als Kuriosum aufgefallen, was ich mir nicht erklären  
kann, daher meine Meldung an Dich. Ich dachte an Omikron für O, aber  
eine Testersetzung brachte kein Ergebnis.




Zitat von Pietro Liuzzo <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
@abausi do you know what these abbreviations may stand for?
 - Or. Az.
 - Or. Man.
 - Or. Jonae
 - Or. Jon.

**Comment by abausi** [comment]
"Prayer of", see below (so-called "Canticles of the Old Testament"):

Or. Az. = Oratio Azariae
Or. Man. = Oratio Manasse
Or. Jonae = Oratio Jonae
Or. Jon. = Oratio Jonae (the same as above)

("Explanatio brevior, potior")
