### ISSUE TITLE
Some corrections to Dillmann's Prolegomena

### ISSUE THREAD

**Issue by wdickhut** [BetaMasaheft/Dillmann#263]
– not urgent –

Following a number of corrections to the Prolegomena:

quae omium literarum
quae omnium literarum

Pachomii vocamus ( ሥርዐት፡
Pachomii vocamus (ሥርዐት፡

in N.T. Acthiopico
in N.T. Aethiopico

e nostro apograpbo codicis
e nostro apographo codicis

sub initium saeculi XVI i
sub initium saeculi XVIi

exegeticam ( ድርሳን፡ ), et paraeneticam ( ተግሣጽ፡ );
exegeticam (ድርሳን፡), et paraeneticam (ተግሣጽ፡);

allegarvit
allegavit

sub rege quodam ጺሩጻ ይ ዳን፡ (i.e. Tyro et Sidone)
sub rege quodam ጺሩጻይዳን፡ (i.e. Tyro et Sidone)

Ma ſsḥafa Faus
Maſsḥafa Faus

( መጽሐፈ፡ ግንዘት፡ )
(መጽሐፈ፡ ግንዘት፡)

ቄድር፡ ( de quo
ቄድር፡ (de quo

cum a ማኅበረ፡ ም እ መናን፡ incipiat
cum a ማኅበረ፡ ምእመናን፡ incipiat

**Comment by wdickhut** [comment]
Perhaps it's possible that we ourselves are able to correct the text?

**Comment by PietroLiuzzo** [comment]
done. it takes me much longer to provide you an ad hoc editor then to fix these few things. it was marked as not urgent, now I have done it. sorry for the wait.

**Comment by wdickhut** [comment]
Thank you!
(A proposito: it would be a nice extra to link all the words in the Prolegomena to the Perseus Latin Word Study Tool, wouldn't it?)

**Comment by wdickhut** [comment]
— not urgent —

typis cxcusae exstant
typis excusae exstant

Genzat (መጽሐፈ፡ ግንዘት፡ ) i.e.
Genzat (መጽሐፈ፡ ግንዘት፡) i.e.
