### ISSUE TITLE
Links from words

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Dillmann#264]
It seems that whenever I click on an Ethiopic word inside a lemma text (an example or similar) I am sent to the search on betamasaheft and not on Dillmann (I am so to say kicked out of the dictionary app). 
Unless this is the intended behaviour possibly the links should be resolved not as `"http://betamasaheft.eu/search.html?query=..."` but as `"http://betamasaheft.eu/Dillmann/?mode=fuzzy&q=..."`?

**Comment by PietroLiuzzo** [comment]
That was indeed the requested behaviour....

**Comment by eu-genia** [comment]
on cross-checking with project members: the desired behaviour would be once in the dictionary to stay inside the dictionary, the links should be inside the dictionary app

**Comment by PietroLiuzzo** [comment]
As you know, I do not particularly like changing back and forth the behaviour of the application according to who has expressed the last opinion. In one month somebody else will come back and ask to have a search of attestations of that word in the corpus of BM. We can have both, if you want, but of course a link needs to be attached to something. 
I can make a popup with options on click, then you will choose where to go. I can add an icon with a link to another option compared to the link in the text, etc. Please, find an agreement and let me know.

**Comment by eu-genia** [comment]
The attestations in the BM corpus are visualized anyway under the lemma (or are supposed to, sometimes they are not shown), this issue was concerning not the main lemma but the quotations and examples within.
Just as in BM clicking on a Ge'ez word leads to the dictionary, even more so inside of the dictionary the click should lead to the dictionary.

**Comment by PietroLiuzzo** [comment]
I had clearly understood. We are speaking about the same thing. The opinion which made me change it to search bm, was that, If I am in the dictionary there is no added value in clicking to search, when the search box is already there, whereas if I click and search attestation of that word I have added value. 
as I said. there are many more option than one or the other, and I have also made another proposal. please consider them and let me know.

**Comment by SusanneHummel** [comment]
I would propose to discuss this issue on our next TraCES meeting on 27 June.

**Comment by eu-genia** [comment]
the links should lead within Dillmann app (`"http://betamasaheft.eu/Dillmann/?mode=fuzzy&q=..."`)

**Comment by PietroLiuzzo** [comment]
done

**Comment by PietroLiuzzo** [comment]
you might have to refresh the page you are loading, just hold Upper case and click on reload
