### ISSUE TITLE
online DL Abbrev.: "Esth. apocr." - not in printed DL Sigla - clarification?

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#27]
- in the B.M. database there is only 1 entry for the Biblical O.T. "Book of Esther" (LIT1362Esther);
- there also only one Biblical book by this title, isn't it? also in the Ethiopian Bible (ዘአስቴር, Zä-Ester)
- there is a distinction between the "short Esther" (i.a. protestant Bible) and the "Esther with additions"; the Lutheran Bible has "Stücke zu Ester" as apocryphal texts, maybe Dillmann refered to this when coining "Esth. apocr." ?...
- as DL uses two distinct abbreviations (1. "Esth." & 2. "Esth. apocr."), shall there be two distinct LIT references here? (i.e. even though the Ethiopic Bible may not demand such a distinction?) 
[the general rule, as Pietro pointed out, is: 1 abbrev. = 1 LIT or no LIT (but not 2 abbrev. sharing 1 LIT reference)]

**Comment by MassimoVilla** [comment]
One single LIT reference is enough: DL abbreviations with "Esth.", with chapter and verse, point to the short Esther; DL abbreviations with "Esth. apocr." (containing one single number) point to the portions of text added in the Greek (Septuagint) version of Esther, which is the Vorlage of the Ethiopic text. But in the Ethiopic they both form one continuous text.
So, for instance, on DL col. 41 ሉብስ፡ ውእቱ፡ ኵሎ፡ አልባሰ፡ ግርማሁ፡ Esth. ap. 5 corresponds to addition D, 6 in Esteves Pereira's edition of the book of Esther (_Le livre d'Esther: version éthiopienne_, Patrologia Orientalis IX.1, Paris, 1913). Again, on DL col. 13 ቃል፡ ውሁከት፡ Esth. apocr. 1 corresponds to addition A, 4 in Pereira's edition.
