### ISSUE TITLE
Fehlermeldung Lexicon

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#270]
Ich wollte in dem Eintrag ድኅረ etwas ändern und erhalte diese Fehlermldung 
<exception>
<path>/db/apps/gez-en/edit/edit.xq</path>
<message>
exerr:ERROR Could not locate collection: /db/apps/gez-en/EditorBackups [at line 55, column 15]
</message>
</exception>

**Comment by SusanneHummel** [comment]
Ich wollte gerne dieses hier hinzufügen:

<Sen< 
+adv.+ 
\*gez*ወይትነሣእ፡ ወየሐውር፡ ይምነ፡ ወፅግመ፡ ቅድመ፡ ወድኅረ፡\* 
>de> Er pflegte sich zu erheben, nach rechts und links, nach vorn und hinten zu gehn.>
*Kebr. Nag.|25,12*
 [page,17b l. 22 (ed.), 15 (tr.)]bm:Bezold1905KebraN 
>S>

"What have you done": Added new PoS +Adv.+

**Comment by SusanneHummel** [comment]
Danach wollte ich dich bitten, die neue "Traces"-Bedeutung mit III) zu strukturieren 
Es gibt bisher "I) Praep" und "II) Conj"

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/Dillmann/lemma/L42d96d0518834126988ce37d21ff899d
