### ISSUE TITLE
Missing Emperors of Ethiopia

### ISSUE THREAD

**Issue by MargaretheJenner** [BetaMasaheft/Dillmann#273]
Missing on Beta maṣāḥǝft:

Wedem Arad

**Comment by thea-m** [comment]
that's him: http://betamasaheft.eu/persons/PRS10111WedemR/main
thank you!

**Comment by MargaretheJenner** [comment]
Thank you!

**Comment by MargaretheJenner** [comment]
There are about 3 Amda Seyon and I can' identifiy which one is supossed to be:
 Amda Seyon I (https://en.wikipedia.org/wiki/Amda_Seyon_I)

**Comment by thea-m** [comment]
it's PRS1854Amdase
should be identifiable when comparing the dates and biographical data? Or do we actually have two records for the same person? (that has happened before...)

**Comment by thea-m** [comment]
this actually isn't an issue for Dillmann, when you have finished your work on Wədəm ʾArʿad and ʿAmda Ṣəyon, could you close it and for any new questions open an issue in beta masaheft? https://github.com/BetaMasaheft/Documentation/issues
Thank you :)
