### ISSUE TITLE
something could be better

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#277]
Dear Pietro,

I wnat to make a cross-refference from one entry to another, which has many homographs. I would like that my ((vid.  ዕዳ፡)) from http://betamasaheft.eu/Dillmann/lemma/L30864ad021594009b466f1e38f639316
 goes here http://betamasaheft.eu/Dillmann/lemma/L15fb245ba05148cabf30693667b0afe6. Now, it takes me to a false entry
Is that possible? Thank you!
magda

**Comment by PietroLiuzzo** [comment]
Yes, that is entirely possible. there might be more than one entry with that lemma and it will take the first it finds.
There is not at the moment a way to enter a link directly, but there will be soon.
#82

**Comment by PietroLiuzzo** [comment]
Also @AndreasEllwardt recently requested the same thing, so I will raise the priority of this requirement

**Comment by PietroLiuzzo** [comment]
I have started adding a feature to have links encoded as here in github with `(link)[http://dasda]`.
needs support for <foreign> inside the link part
needs checking that the vid.sub javascript query avoids playing with spaces around it

**Comment by PietroLiuzzo** [comment]
the link problem is solved in the vid. sub spacing before links

**Comment by PietroLiuzzo** [comment]
it is now possible to mark up language in the first part, the link text.

**Comment by PietroLiuzzo** [comment]
@MagdaKrzyz please try to add after ((vid.)) the following

`(\*gez*ዕዳ፡\*)[http://betamasaheft.eu/Dillmann/lemma/L15fb245ba05148cabf30693667b0afe6]`

it should insert the correct link.
let me know if ok.

**Comment by MagdaKrzyz** [comment]
Dear Pietro,
no idesn't work. And the link is displayed.

pon., 29 paź 2018 o 14:13 Pietro Liuzzo <notifications@github.com>
napisał(a):

**Comment by PietroLiuzzo** [comment]
could you please check now?
the first pair of () paranthesis were omitted
