### ISSUE TITLE
RIE entries  / something is very wrong

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#284]
Dear Pietro, 

entries from RIE (contained in inscriptions) are coded under "Dillmann" and not "TraCES" should it be like this.
Here one example http://betamasaheft.eu/Dillmann/update.html?id=L22d9d8c8ec544b7b8b7ca8e0c9b1fe11&new=false&sourcela=dillmann
Best
Magda

**Comment by PietroLiuzzo** [comment]
Dear Magda, I do not think that this is a question for me...

**Comment by MagdaKrzyz** [comment]
Dear Pietro,
Pardon! All these entries, as far as I know, where entered automatically,
so I thought it was you asked by someone to do it.
Have a good evening and then morning!
M

śr., 14 lis 2018 o 21:19 Pietro Liuzzo <notifications@github.com>
napisał(a):

**Comment by PietroLiuzzo** [comment]
it is certainly me that did that, but it is not up to me to decide if that is dillmann or traces, I was given the data and I entered it. if this is from an early stage there was no TraCES option yet possibly. you can still change it, up to you to decide if and what to do. personally I do not think it is a high priority.

**Comment by PietroLiuzzo** [comment]
all entries with references to RIE are now with source="#traces".
most of this had already been done, I had to change just a few.
