### ISSUE TITLE
Bibliografische Angaben des Lexicons auf der Startseite der App

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Dillmann#293]
Ich denke, es fehlen auf der Startseite der App die bibliografischen Angaben des Lexikons zu geben: bm:Dillmann1865Lexicon

**Comment by PietroLiuzzo** [comment]
Tut mir leid, ich verstehe nicht wo ist das Problem und wie soll ich es korrigieren. Meinst du einfach das es sollte irgendwo da eine bibliographische Angabe an Lexikon geben? wo genau?

**Comment by SusanneHummel** [comment]
Ich kann gerne auf der nä chsten Sitzung fragen. Mich hat es gewundert, dass auf der Startseite der app (http://betamasaheft.eu/Dillmann/ ) keinen HInweis auf die Grundlage des Onlinelexicons, nämlich Dillmanns Lexiskons, gibt. Aber vielleicht soll das nicht sein? ich frage nochmal am Dienstag

**Comment by PietroLiuzzo** [comment]
Ich hab es ins footer hinzugefügt, so dass es ist auf jede Seite
