### ISSUE TITLE
Names of peoples 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#303]
Dear All, 

I am just revising the entries form RIE where I often encounter names of peoples. For the moment these names are labelled as "name of a tribe". Example: 
kāsu – name of a tribe; in RIÉ 187.3, RIÉ 188.4, RIÉ 189.4, RIÉ 189.28, RIÉ 189.36 
I have serious doubts if we should use the term "tribe" because of two reasons: anthropologists writing in English do not use this term any more as it acquired negative connonations in the colonial context. Secondly, even in AEa this term is avoided, for instance it does not appear in the entry for "Noba" (labelled "tribe" in our lexicon). 
If we leave "tribe" in reference to the names occuring in RIE what do we do with similar names appearing  Kibre Negest, for instance "Moabites" and "Philistines". Finally what do we do with more contemporary peoples, e.g. Felasha? 
I suggest that we use as a specification of the proper name either "ethnic group" or simply and maybe even better "people". 
What do you think?

**Comment by vitagrazia81** [comment]
Dear Magda,
in some of the entries from Amda Seyon, I have used for instance "Ethnic name" (see e.g. https://betamasaheft.eu/Dillmann/lemma/L9c9efaa6d7be40a68d2ccf4e63d70afd). I would use rather this then "ethnic group", to keep uniformity with what we name "personal name" or "place name", for which we don´t use "person" or "place".

**Comment by MagdaKrzyz** [comment]
Dear All,
thank you for your feedback. 
I can see that perhaps some of you have not received my second note with another proposal: ethnonym. This word is the best because it is the most neutral, lexicographically oriented and can refer to both a whole ethnic group as well as to a representative thereof. 
I suggest that we use this label (with Alessandro's support).
Vita suggests "ethnic name" due to the parallelism with "personal name", but this is not a good choice. In English "ethnic name" has the following meaning:
ETHNIC NAME, also ethnic label and, when pejorative, ethnic slur. A nickname for someone from a particular nationality, race, community, or culture. The spectrum of ethnic names in English ranges from more or less affectionate nicknames (such as Jock for a Scotsman, as used in England) through relatively neutral terms (such as Brit for someone British) through the use in affectionate abuse of terms that can otherwise be offensive (such as Limey and Yank between American and British friends), to highly offensive racial and/or religious slurs used without restraint, such as dago for someone of Spanish, Portuguese, or Latin American background, and Yid/yid for someone Jewish.

In the Traces meeting on 12.03. I would like to discuss with you a few points concerning the lexicon:
1) what do we treat as a proper name
2) labels that specify the kind of proper name (personal name etc.)
3) labels that specify the kind of proper noun (rank etc.)
4) capitalizing or not transcription of proper names
5) inserting compounds
6) RIE - bibliographical info. 

Have a good evening!
Magda

**Comment by abausi** [comment]
Dear Magda,

many thanks, as we discussed, I also support "ethnonym".

We will discuss this in a TraCES meeting, but on 12 March: our next 
dates are 5 and 19 March.

Many thanks,
Yours

Alessandro

Il 26.02.2019 18:03, MagdaKrzyz ha scritto:

**Comment by abausi** [comment]
Dear Magda,

many thanks, as we discussed, I also support "ethnonym".

We will discuss this in a TraCES meeting, but NOT on 12 March: our next 
dates are 5 and 19 March.

Many thanks,
Yours

Alessandro

Il 26.02.2019 18:03, MagdaKrzyz ha scritto:
