### ISSUE TITLE
Another proposal

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#304]
I think the best label is "ethnonym".

**Comment by MagdaKrzyz** [comment]
I think the best label is "ethnonym".

**Comment by PietroLiuzzo** [comment]
Dear @MagdaKrzyz : for what? where? how?

**Comment by MagdaKrzyz** [comment]
Pietro,
I am sorry. I wanted to send the message to the editors of the lexicon.
Disregard it.
Have a good day!
Magda

Pietro Liuzzo <notifications@github.com> schrieb am Fr., 22. Feb. 2019,
06:11:
