### ISSUE TITLE
question about link

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#306]
Pietro
is this link ok? It contains Ethiopic script

https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%88%B8%E1%8B%8B%E1%8D%A1%20%E1%88%A8%E1%8B%93%E1%8B%B5&id=L6e2320e5d930433a98793eb1a0fb5dbb

This is the entry ሸዋ፡ ረዓድ፡

**Comment by PietroLiuzzo** [comment]
this should be fine, but actually to link to a lemma you don't need the part with the query, so, better just 
https://betamasaheft.eu/Dillmann/lemma/L6e2320e5d930433a98793eb1a0fb5dbb
