### ISSUE TITLE
part of speech

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#311]
Dear Editors,
could you help me with determining which part of speech it is? A particle? - a term which is typically given to anything we cannot properly pin down? 

https://betamasaheft.eu/Dillmann/lemma/Ld6f18b9910d54128b589d47fdd3a01b9

Magda

**Comment by abausi** [comment]
For the moment being, the most convenient solution is to relate it, with 
an entry of its own (as already done here), under the relative pronoun - 
even though opinions vary and Kropp is an example of this. There is more 
bibliography on this.

Il 22.03.2019 12:01, MagdaKrzyz ha scritto:

**Comment by MagdaKrzyz** [comment]
Dillmann has alread the entry with እለ as Pl. rel. pron. cross-referencing
to ዘ. Here is the link:
https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%A5%E1%88%88&id=Ldbcd9df387794613b6e6ba62a0c8e2dc

So you suggest I introduce it under the Dillmann's እለ?

pt., 22 mar 2019 o 12:05 Alessandro Bausi <notifications@github.com>
napisał(a):

**Comment by abausi** [comment]
No, that's not the right place; it should be under the main entry where 
the relative pronoun is; crossreferencing for facilitating search does 
not count. So, it should be a SECTION of its own, under ዘ relative 
pronoun, here: 
https://betamasaheft.eu/Dillmann/lemma/L6d2f800ae7f04a77815a6dacb546cb54

Il 22.03.2019 12:11, MagdaKrzyz ha scritto:

**Comment by abausi** [comment]
It could be placed as an A, 3 new section (between A, 2 and B).

Il 22.03.2019 12:18, Alessandro Bausi ha scritto:

**Comment by MagdaKrzyz** [comment]
Good!


pt., 22 mar 2019 o 12:18 Alessandro Bausi <notifications@github.com>
napisał(a):

**Comment by eu-genia** [comment]
@MagdaKrzyz can one close the issue? 
Please close all issues you received a satisfactory answer to.  Thank you!
