### ISSUE TITLE
Cross reference

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#312]
Dear Pietro, I have a problem with the cross reference in the entry የአክል፡ ጋዳ፡ (https://betamasaheft.eu/Dillmann/lemma/L8d7a3e3121ae418d81913cb36b342df3:): 
if I click on the word ጋዳ፡ at the end I don`t go to the specific entry for  ጋዳ፡ (https://betamasaheft.eu/Dillmann/lemma/L19e13824b9f44815a976f218cde631c3), but again on the entry for  የአክል፡ ጋዳ፡. 
I don't understand why. 
Thank you.

**Comment by PietroLiuzzo** [comment]
closing issue, please fix as discuss in person
