### ISSUE TITLE
Personal names

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#314]
Dear All, 

I have come across entries with personal names from RIE where it is said whether it is a female or male name. I suggest that we mark only if the name is for a woman and if there is no additional marking the name is male by default.
Here a link to a fem personal name:
https://betamasaheft.eu/Dillmann/lemma/L1d268de0f99f47699304afd08e321be8

What do you think?
Magda

**Comment by abausi** [comment]
Dear Magda,

(does this betray your Catholic background?) actually, if we mark the 
gender, we should ALWAYS mark the gender, provided we know (or is only 
feminine "marked"?)

Yours,

Alessandro

Il 25.03.2019 15:55, MagdaKrzyz ha scritto:

**Comment by MagdaKrzyz** [comment]
Dear Alessandro,
I didn't think about my Catholic convictions (at least not consciously) but
rather about the space and work. There are not many female personal names,
but many male (which we have not indicated as such).
I thought it is good to incorporate the info. that Masha gave us.
Yours
Magda

pon., 25 mar 2019 o 15:58 Alessandro Bausi <notifications@github.com>
napisał(a):

**Comment by abausi** [comment]
I understand, Magda, I was joking: but you raised an important question, 
in fact! should we then (a "Pietro-Macro task") mark all personal names 
so far as masculine? that would be too much, and for sure we have also, 
not only "Mary", but many other female personal names. But I think it 
would be good, starting from now, to mark all new names entered either 
as feminine or masculine (if it is possible to realize).

Yours,

Alessandro

Il 25.03.2019 16:04, MagdaKrzyz ha scritto:

**Comment by MagdaKrzyz** [comment]
Dear Alesandro,

good, we can do it.  It is a matter of one word after n.pr.

Yours,
Magda

pon., 25 mar 2019 o 16:09 Alessandro Bausi <notifications@github.com>
napisał(a):

**Comment by abausi** [comment]
But please: "fem." with dot! (not "fem").

Dots count!

Il 25.03.2019 16:14, MagdaKrzyz ha scritto:

**Comment by MagdaKrzyz** [comment]
Right!
Done.
Magda

pon., 25 mar 2019 o 17:38 Alessandro Bausi <notifications@github.com>
napisał(a):
