### ISSUE TITLE
Title for the text "Chronique of ʿAmda Ṣǝyon”

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Dillmann#315]
Dear all, 
yesterday in the meeting there was a small debate on the word ታሪክ used in the title for the “Chronicle of ʿAmda Ṣǝyon” which you read in BM, that is, if it is correct to use this word, if it is used in the text or not, etc…
This ታሪክ in the title comes from a metadata on the text of the Chronicle of ʿAmda Ṣǝyon”, which I preliminary provided some time ago and which has been then encoded by Zhenia. I checked it and, infact, as title for this text I gave “Chronicle of ʿAmda Ṣǝyon” but also ታሪከ፡ ዓምደ፡ ጽዮን. I wanted probably to use also an Ethiopic title for this text, using therefore the word ታሪክ, which is also the one traditionally used for this kind of Chronicles (see EAE III, p. 41).
I checked in the text and, infact, as it has been rightly doubted yesterday, the word ታሪክ does not appear at all.
So, most probably it is reasonable to remove ታሪክ from the title and to have only “Chronicle of ʿAmda Ṣǝyon”, althought also this last may be not the right one. As Marrassini underlines in the Introduction of his edition (Marrassini 1993, p. 1, pp. 43-46), even though the story narrated in this text is commonly called “Chronicle” (e.g., see Cerulli in the Storia della letteratura etiopica” 1961, p. 37), the word Chronicle is not completely satisfying and should be avoided as far as possible. About the genre of this text, his hypothesis is that it can be considered not a real historical work, but a homily to read in the church, with a propagandist purpose (pp. 43-46).
Anyway, in the text, there is any evident title, neither at the beginning nor at the end, used by the author. In the incipit we read : በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ፡ ንጽሕፍ፡ በረድኤተ፡ እግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ ኀይለ፡ ወመዊአ፡ ዘገብረ፡ እግዚአብሔር፡ በእደዊሁ፡ ለዓምደ፡ ጽዮን፡ , “… scriveremo la forza e la vittoria…”, …  ንጽሕፍኬ፡ ዘንተ፡ መጽሐፈ፡ እንዘ፡ ንትአመን፡, “scriveremo dunque questo libro avendo fede…” (Marrassini 1993, pp. 50, 51).
At the end, the word ነገር is used a few times to define the history narrated in the text:  ወላዕለ፡ ሰራዊቱ፡ በምድረ፡ ተንባላት፡ መዓልተ፡ ወሌሊተ፡ ኅዳጠ፡ ነገርነ፡ ወኢወሰክነ፡ ከመ፡ ኢይኑኅ፡ ነገር፡ “Molto si sarebbe potuto scrivere contro il re e le sue truppe; ma noi ne abbiamo raccontato poco, e non vi abbiamo aggiunto altro, perché il discorso non si facesse troppo lungo” (Marrassini 1993, pp 188, 189).

All the best,
Vita

**Comment by eu-genia** [comment]
thank you, will leave just the English label

**Comment by vitagrazia81** [comment]
Of course, "Chronicle, not "Chronique". Sorry!
