### ISSUE TITLE
transliteration within a quote

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#326]
Dear Vita and Pietro,

Do we encode the transliteration within the quote as in the following entry?
https://betamasaheft.eu/Dillmann/lemma/Lf1472b66d1f54809b1d16c82e7b4f732

Yours 
m

**Comment by PietroLiuzzo** [comment]
from my point of view, you can. perhaps you should decide what to do to remain consistent, and document it in the wiki https://github.com/BetaMasaheft/Dillmann/wiki

**Comment by vitagrazia81** [comment]
Dear Magda, 
actually I wanted to encode it within the quote, but it was not possible (the result was not the one hoped, after I saved the change), So, I encoded the transliteration outside the quote.
How do we do?

**Comment by vitagrazia81** [comment]
So, Magda, since for Pietro it is the same how we decide, we can do as you said (before in the office), that is, we keep the  translitaration within the quote but without the encoding. Is it fine? if yes, we will update the guidelines.

**Comment by MagdaKrzyz** [comment]
Good, alles klar. We have to say a word about it in the guidlines.


pon., 15 kwi 2019 o 14:04 vitagrazia81 <notifications@github.com>
napisał(a):

**Comment by vitagrazia81** [comment]
But, again a doubt:
how we do with a transliteration within an encoded translation? see "śǝyyum of Wāg" in:

https://betamasaheft.eu/Dillmann/lemma/L153553e0e5e0448f9ba1221d2cf70045

**Comment by MagdaKrzyz** [comment]
Vita, we keep it simple just as you did: without encoding the
translaietration within the translation.

pon., 15 kwi 2019 o 14:53 vitagrazia81 <notifications@github.com>
napisał(a):
