### ISSUE TITLE
Names of the days of the week

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#337]
Dear All, 
I am confronted with the following question: are  names of the days of the week and names of the months common nouns or rather proper names (or proper nouns)? Dillmann refers to them as nomen tempor. (days of the week) and nomen mensis, but never as substantives. 
I would tend to consider them as proper names because they refer to a single element within a set. Alternatively, we could treat them in the same way as the names of animals, plans and titles, i.e. as substantives with an additional comment in parentheses (day of the week, month).
What do you think?
Have a good day!
Magda

**Comment by abausi** [comment]
I would treat them like the names of animals etc. that are also single elements within a set - or is also "thumb" e.g. a proper names? is it a finger among other fingers, or not? I see that in the online "Oxford" days of the week are treated like nouns, capital though.

**Comment by SusanneHummel** [comment]
I agree with Alessandro because somehow everything is an element of a bigger set. We consider names of trees, of animals etc as common nouns as thery refer not to a unique element like a specific person, place.

**Comment by MagdaKrzyz** [comment]
Good, thank you!
There are different conventions of capitalizing from language to language
anyway.


śr., 29 maj 2019 o 12:48 SusanneHummel <notifications@github.com>
napisał(a):
