### ISSUE TITLE
Spelling Error for በከየ entry

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Dillmann#341]
the subjunctive of the entry በከየ should read ይብኪ not ይብቢ

**Comment by PietroLiuzzo** [comment]
Could you please give the link to the exact entry?

**Comment by abausi** [comment]
right, we shall correct

**Comment by PietroLiuzzo** [comment]
here 
https://betamasaheft.eu/Dillmann/lemma/L31e56a303ed744d19f1d63c1328ec94d

?

**Comment by Ralph-Lee-UK** [comment]
Pietro

 

You’ll see it here, following ‘Subj.’ 

 

https://betamasaheft.eu/Dillmann/lemma/L31e56a303ed744d19f1d63c1328ec94d

 

Regards

 

Ralph 

 

Ralph Lee

Cambridge, UK

* +44 7906149088 
*  <mailto:ralphlee1965@gmail.com> ralphlee1965@gmail.com

 

 <https://www.facebook.com/ralph.lee.7505>   <skype:ralph_and_sarah?add>

**Comment by PietroLiuzzo** [comment]
Thanks a lot! that should be fine now.
