### ISSUE TITLE
something is strange

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#348]
Dear Pietro, 
would it be possible to have in this entry:
https://betamasaheft.eu/Dillmann/lemma/L6730f7b0a19b42ba9dceae9bf36994e7

the name of the book instead of 'Anon'?
Thanks!
m

**Comment by PietroLiuzzo** [comment]
easy! no, it is not possible, this is how the zotero style behaves. you might wish to look at https://betamasaheft.github.io/bibliography/ to see if the zotero record can be edited in some way to get what your would expect. otherways, if the record is correct, that is the correct result from the common style and should not be altered arbitrarily.

**Comment by PietroLiuzzo** [comment]
eventually, it looks like it even easier.
if you look at this correct one https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/4JENH6QU
you will see immeditely how to correct your record 
https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/T998BJMZ
so that it is also correct
