### ISSUE TITLE
Jean de Nikiou

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#351]
Dear Daria, 
have you come across the word ማኅፈድ in the chronicle? In the meaning 'sign of the zodiac'. It should be somewhere but the reference that I have is not right.
Thanks!
Magda

**Comment by DariaElagina** [comment]
Hi, Magda, sorry, I did not receive any notification whe you opened the issue. I guess, that I indeed came across this word in this meaning. Should I have a look?

**Comment by MagdaKrzyz** [comment]
would be great
Thank you!

**Comment by DariaElagina** [comment]
I could remember at least one example, there might also be more, I will keep you updated.
So, it is in the colophon of the Ethiopic translation, in Zotenberg it is on p. 222, lines 9-10: እንዘ፡ ሀሎ፡ ፀሐይ፡ በማኅፈደ፡ አቅራብ፡ ወወርኀኒ፡ በማኅፈደ፡ ደሉ፤
In Charles translation it is p. 202, 123.6.
I will search in the text once more soon.

**Comment by MagdaKrzyz** [comment]
Thank you very much! Now it is in the dictionary:
https://betamasaheft.eu/Dillmann/lemma/L08617a7ea8ca4f6695392667610a01e6

I don't know if the word appears more time.

**Comment by DariaElagina** [comment]
Thank you,

just a small note, I think there is a typo: "in the sing of Scorpion", should be "sign", I guess.

**Comment by MagdaKrzyz** [comment]
You are right! Thanks
