### ISSUE TITLE
Entry to be modified

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#354]
Dear Vita, 
could you please change the structure of the entry to fit our practice?
Thanks!

https://betamasaheft.eu/Dillmann/lemma/L656cc33f8d954f6983bbd50bfa6c4c88

**Comment by vitagrazia81** [comment]
Dear Magda, 
yes, I have done. It is fine like this? Could you have  a look, please?
https://betamasaheft.eu/Dillmann/lemma/L656cc33f8d954f6983bbd50bfa6c4c88
Thanks.

**Comment by MagdaKrzyz** [comment]
Vita,
it is good but Marrassini disappeared. I tried to manipulate with it but zo
no avail. Could see see once again?
m

śr., 20 lis 2019 o 12:09 vitagrazia81 <notifications@github.com> napisał(a):

**Comment by MagdaKrzyz** [comment]
Vita, sorry there must be a more general problem. Wait for a second.

śr., 20 lis 2019 o 15:01 Magdalena Krzyżanowska <magdalena.krzyz@gmail.com>
napisał(a):

**Comment by MagdaKrzyz** [comment]
Vita, good, now there is full info. There was a problem on the side of the
programme.
Thanks!
m

śr., 20 lis 2019 o 15:01 Magdalena Krzyżanowska <magdalena.krzyz@gmail.com>
napisał(a):
