### ISSUE TITLE
collocations, compounds 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#357]
Dear Editors, 

there is an important issue of how to number and structure compounds and collocations. We record them under the head word. 
My proposal (prompted and consulted with Pietro) is that we number them with Arabic numbers and lower case letters, just as other meanings. Actually, what we mark as A), 1), a) could be both meanings and new forms with their meanings.  Please take a look at the two examples and tell me what you think about them.
https://betamasaheft.eu/Dillmann/lemma/L5a8f34ec396f4cdeb86b39679aa99dd8
https://betamasaheft.eu/Dillmann/lemma/L49035195ba954b20939e04bf0d9cceb2

In both examples the compounds/collocations are referred to the appropriate sens in Dillmann. 
Magda

**Comment by PietroLiuzzo** [comment]
Just to add my two cents, in the new semantic data structure these are all "sense" and "Lexicographical Components". What determines their quality is the content. Thus, while the nesting as normal and suggested above is perfectly fine, I should encourage you to encode within each of these senses their distinctive features.

**Comment by MagdaKrzyz** [comment]
Pietro,

I find the term "lexicographical component" a bit unconventional. What are
they components of? Maybe "lexical units" or "lexicographic units"? But
perhaps in your scientific environment this is a common term.

śr., 20 lis 2019 o 16:59 Pietro Liuzzo <notifications@github.com>
napisał(a):

**Comment by abausi** [comment]
I am sorry, will not be able to follow anything for a week.

Il 20.11.2019 17:25, MagdaKrzyz ha scritto:

**Comment by PietroLiuzzo** [comment]
it was just to support your point :) you decide the name

**Comment by abausi** [comment]
I agree, provided that this is technically in compliance with the regular working flow and does not cause any technical (non-digital) constraint.

**Comment by vitagrazia81** [comment]
Dear Magda, 
I also agree.
