### ISSUE TITLE
vid. requirements

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#359]
Dear Pietro,
there is a problem with cross-referencing to compounds. 
1) In the following case:
https://betamasaheft.eu/Dillmann/lemma/Lad3a0f7a49cf4b92a1626200e954385c

after "vid." one can only go to the first word but not to the whole compound. 

2) In this case (look at meaning b. under TraCES) https://betamasaheft.eu/Dillmann/lemma/L5a8f34ec396f4cdeb86b39679aa99dd8
it is impossible to go straight to ደዌ. I have noticed that this is impossible also in other, newely introduced instances. I can always enter the link but then there is no other option but only to go directly to the entry. Look here (meanings a) and d) under TraCES):
https://betamasaheft.eu/Dillmann/lemma/Lef4ed3d79c8d44339fd73c7283d0123f 
The referent words are underlined.

**Comment by PietroLiuzzo** [comment]
please the missing links should be fixed, it was an issue in the refactored javascript with the popups, thanks for pointing it out

**Comment by PietroLiuzzo** [comment]
I have added also the popup where the link contains text marked as gez

**Comment by PietroLiuzzo** [comment]
you can use vid. and will get the links to each entry of 2 separated by comma
you can link directly and will also have the box with the links
you can use or not the two dots
the compunds are a case for direct link, as are ambiguous lemmas

**Comment by eu-genia** [comment]
is this fixed? if yes please close the issue
