### ISSUE TITLE
Info about the origin of a word

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#362]
Dear All, 
how should we provide info on the origin of a word. Recently we came to the idea that writing labels "am", "ti" ect.  do not work because sometimes we don't know where the word comes from. The info must be given in a more subtle way. 
We have a section within an entry called "Comparative data" in which we don't commit ourselves to the statement whether a given word is foreign or not. See here:
https://betamasaheft.eu/Dillmann/lemma/L4c27a471d77f4049b1788ee61ee7c795

What do we do if the info about an origin is included in the comment, such as here:
https://betamasaheft.eu/Dillmann/lemma/L6d45800b25b14a4bb43817acd378b21a
https://betamasaheft.eu/Dillmann/lemma/L76b2ca51fb344c6eaba35005cbb0289b
Do we leave it as it is or we move it to the section comparative data?

In cases when there is no comment on the origin, such as here:
https://betamasaheft.eu/Dillmann/lemma/Lbd4fc4c929da4ae1aebf907a89ab6803
I suggest that I add section "Comp. data" and write the meaning from Kane. 
What do you think? 

Could you please help me with the last question (about numbering) I asked you?  
Thanks 
Magda

**Comment by abausi** [comment]
We could rename the section "Comparative data" as "Comparative and etymological data". I would in this case repeat or give the relevant information provided by the sources, without deleting it from the occurrence, for the sake of clarity. A section on "Comparative and etymological data" can provide information in a more flexilble form.

**Comment by PietroLiuzzo** [comment]
the section has been renamed (again).
