### ISSUE TITLE
An underline 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#363]
Dear Pietro, 
I have noticed that there appears a short underline in the entries which have a cross-reference. Look at the end of this entry:
https://betamasaheft.eu/Dillmann/lemma/Lb3bf85ee9eea4b76a9a92a5b04ccc14d

Magda

**Comment by eu-genia** [comment]
Can you explain what you mean? Add a snapshot?

**Comment by eu-genia** [comment]
(Please try to be very very very clear and explicit when creating issues, it takes time to try to figure out what the problem is, sometimes longer than the solution)

**Comment by MagdaKrzyz** [comment]
sob., 14 maj 2022 o 02:13 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
It is best if you respond not via email but going directly to github, in this case to https://github.com/BetaMasaheft/Dillmann/issues/363
and in general browse through
https://github.com/BetaMasaheft/Dillmann/issues/

**Comment by MagdaKrzyz** [comment]
![Screenshot 2022-05-16 110432](https://user-images.githubusercontent.com/29131132/168563176-f321d8eb-82a5-49c6-b2f4-213297e4ec20.png)

**Comment by eu-genia** [comment]
This is an error in your encoding, you had an extra round bracket after the link
`( \*gez*የዋህ፡\* )[https://betamasaheft.eu/Dillmann/lemma/L8c0d22702da7408fa4a4265782c1f6b5]) >S>
`
I have removed the bracket
`( \*gez*የዋህ፡\*)[https://betamasaheft.eu/Dillmann/lemma/L8c0d22702da7408fa4a4265782c1f6b5]>S>`

All such cases mean error in your encoding to be fixed case by case, there is nothing wrong with the app

**Comment by MagdaKrzyz** [comment]
I see, this is indeed my mistake - a leftover from the bracketed "TraCES". I checked the other cases, I guess the culprit is the marking "(TraCES)". Take a look at these entries:
https://betamasaheft.eu/Dillmann/lemma/L19e13824b9f44815a976f218cde631c3
https://betamasaheft.eu/Dillmann/lemma/La11f51c2bfb94d42a0639beb51abd548

**Comment by eu-genia** [comment]
I see, the transformation inserts spaces around a foreign word, and if there is a link, it starts before the space and ends after the space, the space which is inside the link gets underlined. i could delete the spaces then all is clean but then there are issues with blank spaces in the text. i will see

**Comment by eu-genia** [comment]
ok, done, added a css style for a clean link
