### ISSUE TITLE
Aresawi

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#367]
Dear Alessandro,

አረሳዊ orignates from Senodos. I forgot that I actually went through 3 editions of yours, not only Libanos. 
There is one word missing in the translation, ካህን. Do you want to add it online?
https://betamasaheft.eu/Dillmann/lemma/Leba689452f4f49d591a4aac005ef4f53

Yours, 
Magda

**Comment by abausi** [comment]
Dear Magda,

I probably dropped the word to avoid a repetition in the translation, but you can certainly insert it in the translation: "lo nominò per primo [sacerdote] era eretico". Also correct the Greek word to: αἵρεσις; and "garantito dale recensioni" to "garantito dalle recensioni"; and "testo etiopico dal graco" to "testo etiopico dal greco". Many thanks.

**Comment by MagdaKrzyz** [comment]
Dear Alesandro,
done,
but አረሳዊ could be a predicative adjective in this sentence, not necessarily
a noun.
Complicated.
Yours,
Magda

śr., 11 gru 2019 o 13:26 Alessandro Bausi <notifications@github.com>
napisał(a):
