### ISSUE TITLE
French typos

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Dillmann#370]
Could you please correct (I have checked Conti Rossini):

https://betamasaheft.eu/Dillmann/lemma/Lc8a858cb658d46fea37e2ff0a0e48c0f
"étrieres" should be **étriers**

https://betamasaheft.eu/Dillmann/lemma/L57b10f54a15e4ab9810cd59bcfca0f21
"que se qu’il avait pris" should be que **ce** qu’il avait pris
"revnaient" should be **revenaient**

https://betamasaheft.eu/Dillmann/lemma/L08617a7ea8ca4f6695392667610a01e6
"bàtir" should be **bâtir**

Sorry if I chose the wrong channel of notification or assignee, please redirect me in this case :)

**Comment by MagdaKrzyz** [comment]
Many thanks!
Done!
m

**Comment by thea-m** [comment]
Merci!
