### ISSUE TITLE
Transliteration of headwords from TraCES

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#372]
Dear All, 

I have already written to you about the incorrect transliteration of the word ማኅፈድ which appears next to the headword and comes from the TraCES annotation.
This is not an isolated example. While working on new lexemes I have encountered some more headwords which received double transliteration (one of them is incorrect), dubious and/or incorrect one. 
Here is a random list of such instances:
https://betamasaheft.eu/Dillmann/lemma/Lb284a617c02042bf978e8cd468993adb
https://betamasaheft.eu/Dillmann/lemma/L906c05c629d2428db50eb8823a47fa9a
https://betamasaheft.eu/Dillmann/lemma/L0b6652da3f904445ac1c002bca86588d (not sure)
https://betamasaheft.eu/Dillmann/lemma/L96fe1c5c8b774bf69dc81057046bd08c
https://betamasaheft.eu/Dillmann/lemma/L91f3eb94dec4403e9b9b530cdcff277f
https://betamasaheft.eu/Dillmann/lemma/L75c8b48a3e2b45e9baa1d1ef9b7f142e
https://betamasaheft.eu/Dillmann/lemma/L9deb04494ef44b519ead379d9650082a
https://betamasaheft.eu/Dillmann/lemma/Lb95178224e4c4309b4197e77385ebaea
https://betamasaheft.eu/Dillmann/lemma/Lcb9878e12e264230b01efc517ee74a4c (there is a hyphen before the last vowel)
https://betamasaheft.eu/Dillmann/lemma/Lfd8203dfff80437480dcc86e64169064
https://betamasaheft.eu/Dillmann/lemma/L01916755ee9346bda61d5d7c0fcba610
https://betamasaheft.eu/Dillmann/lemma/L99f5aea2fc8947488f414e51e89fe0f2
https://betamasaheft.eu/Dillmann/lemma/L9b7ebd24b3b14560ba8030b4f1e2dece (could you check here my transliteration?)

I think that this calls for more control of what flows from TraCES into Dillmann or switching this function off altogether.
Magda

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Dillmann/lemma/Lfb45749ff1a14f9d8879987181e4cf8c
https://betamasaheft.eu/Dillmann/lemma/L35ac34aecb574d29b9129dc1714fa1c6

**Comment by mbulakh** [comment]
As far as I have understood, this is a technical problem: in the present version, the headwords are copied automatically from text transcriptions. If, instead, there were a possibility of inserting the transcription per hand, we could create a useful reference tool for anybody transcribing Geez.

**Comment by eu-genia** [comment]
I understand, it is taken automatically from TraCES data, and does not distinguish between parts of texts that have been corrected by the annotators and parts that have renamed with the automatic GeTa transliteration, both are then shown.
Confusing indeed.
I have now removed the transliteration taken from TraCES data completely, does this help?

**Comment by mbulakh** [comment]
At least the first word I checked remained as it was, with two variants, and one of them definitely wrong: https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%A5%E1%89%A5%E1%8A%95&id=L35ac34aecb574d29b9129dc1714fa1c6

**Comment by mbulakh** [comment]
I think as long as it is taken automatically from anywhere, a lot of wrong transcriptions will remain, and the necessity of correcting them per hand remains an urgent issue.

**Comment by eu-genia** [comment]
now should be gone, sorry, did not comment out everything )

**Comment by eu-genia** [comment]
the function is switched off
