### ISSUE TITLE
PDF transformation improvement

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#374]
Dear Pietro, 

in the pdf files from edited entries generated in Dillmann, the section containing info from Leslau occurs under a nice heading "Leslau". But this is not the case with sections "Comparative and etymological data" and "Cross-references". What comes out is E) and C) respectively. For a wider publicum I think it would be better to have the full names. What say you?
Here for you two entries: one with E) and one with C)
https://betamasaheft.eu/Dillmann/lemma/L8c88b3ecd0644a04b332a23d502e4eae
https://betamasaheft.eu/Dillmann/lemma/L015fb11cc2a74db1816932c3e52e2874
Magda

**Comment by eu-genia** [comment]
fixed
