### ISSUE TITLE
font size of attestations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Dillmann#376]
Is there any possibility to increase the font size in the "text of passage" window? It seems really very small to me.

**Comment by eu-genia** [comment]
where is this window?
In BM attestations?
These do not seem to load after the new release...

**Comment by thea-m** [comment]
I think I meant this:
![image](https://user-images.githubusercontent.com/19650382/168316529-3bb038b4-1eb8-49c9-b1d4-5bddf8c89d26.png)
It doesn't matter much to me now anymore though, I think it can stay as it is.

**Comment by eu-genia** [comment]
easy
