### ISSUE TITLE
No access to passages anymore

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Dillmann#377]
I can no longer access the text of text passages when clicking on the little leaf icon. A pop up window opens asking me to log in (which I already was), and when I do and click ok it just reopens and reopens and reopens.
![image](https://user-images.githubusercontent.com/19650382/87033951-625ba200-c1e7-11ea-9d16-28ce77a595c2.png)

I tried in Chrome and Firefox.

**Comment by PietroLiuzzo** [comment]
could you try again? I have repaired the permissions

**Comment by thea-m** [comment]
works now, thank you!
