### ISSUE TITLE
Fixing transcriptions

### ISSUE THREAD

**Issue by mbulakh** [BetaMasaheft/Dillmann#379]
the entry on እብን 'stone' (https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%8A%A5%E1%89%A5%E1%8A%95&id=L35ac34aecb574d29b9129dc1714fa1c6)
contains the transcription:

እብን፡ ʾǝbn, ʾǝbǝn

Why not leave the correct variant, ʾǝbn, and delete ʾǝbǝn? The variant ʾǝbn would be also in agreement with Leslau's transcription in Comparative Dictionary of Ge'ez.

Regards,
Masha

**Comment by PietroLiuzzo** [comment]
Thanks for the notification.
This is an already known  issue, which is not limited to this instance (thus making the one fix not really worth it) and originates in a conflict of requirements:
- importing transcriptions from Traces annotations
- having the "correct" transcription only
The solution would be to fix the Traces annotations, which I do not see as something which can happen soon. 
A proposal was made some time ago to remove the transcriptions altogether, which I think is a bit drastic and would mean renouncing both the requirements above.

**Comment by mbulakh** [comment]
I see. So the transcriptions are imported automatically from Traces and there is no possibility of changing them directly in the Dillmann online version without touching Traces annotations. Of course removing transcriptions is no solution at all. But it would be good at least to add a window where one could add a comment on the transcription. Because otherwise the "wrong" transcription will be copied in further annotations or in any works using Geez transcription whose authors would be using "Dilmann online".

**Comment by eu-genia** [comment]
Will collect all these in https://github.com/BetaMasaheft/Dillmann/issues/372
Maybe one day they all may be fixed
