### ISSUE TITLE
to correct in the entry one word in the quotation

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Dillmann#381]
correct: ወለይንቱ into ወለዝንቱ

**Comment by PietroLiuzzo** [comment]
in which entry, please?

**Comment by abausi** [comment]
raḥab subst., meaning unknown, ወስምዕዎ፡  ለዝንቱ፡  ረሐብ፡  ወለይንቱ፡  ፍስሓ፡  ወለዝንቱ፡  ተስፋ፡  በተፀምዶ፡  ኅሊና፡
>
raḥab subst., meaning unknown, ወስምዕዎ፡  ለዝንቱ፡  ረሐብ፡  ወለዝንቱ፡  ፍስሓ፡  ወለዝንቱ፡  ተስፋ፡  በተፀምዶ፡  ኅሊና፡
