### ISSUE TITLE
Duplicate valid session cookies

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#387]
When I wnat to confirm changes I receeive a message that I was successful, such as the one below:

![Update_confirmation](https://user-images.githubusercontent.com/29131132/147588541-df26f179-f5f2-45dc-be40-8688aaaa2f35.png)

But when I click on the blue-written entry I receive the following message:
![Error](https://user-images.githubusercontent.com/29131132/147588762-9115fc55-64d9-47ee-a227-c9eac1e68319.png)

Moving on to the home page is not very helpful because the same problem occurs with the next entry.

**Comment by eu-genia** [comment]
Duplicate valid session cookies are usually resolved simply by cleaning your browser cash. Has this error resolved itself?

**Comment by MagdaKrzyz** [comment]
I know and I simply clean them. But I would not like to do it every time I
save new info, that means every 3 minutes.

pt., 13 maj 2022 o 11:01 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
does this error come up every 3 minutes?

**Comment by eu-genia** [comment]
i mean i do get it as well when I work on the backend of the app, but not so often, maybe once a day or two...

**Comment by MagdaKrzyz** [comment]
yes, it appears very often.

pt., 13 maj 2022 o 11:50 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
I have found a nicer solution to the problem: if you are in Chrome you can add the extension https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm/ 
Then if you are in the tab that gives the error you open the Cookie editor and remove the doublet session cookie, it is just one click, and all is fine.

**Comment by MagdaKrzyz** [comment]
Ok, I have added.
