### ISSUE TITLE
label "am" should be removed

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#393]
The label "am" should be removed
https://betamasaheft.eu/Dillmann/lemma/Ldb24de96c82a471ca730fb14f2b62956

**Comment by eu-genia** [comment]
I can have a look into this if you explain clearly where is the label to be removed.
Please close all issues (https://github.com/BetaMasaheft/Dillmann/issues) that have been resolved in the meanwhile.

**Comment by MagdaKrzyz** [comment]
The label is placed to the right from the entry word. This was done by
Pietro, but the whole idea behind it is wrong. There are more words with
this label. Would it be possible to remove them all at once?

pt., 13 maj 2022 o 11:03 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
where does the app take the information from? the language is provided somewhere

**Comment by eu-genia** [comment]
OK I think I found the rule: for all words that are marked as foreign but are not Ge'z the language label appears in superscript.

**Comment by eu-genia** [comment]
removed

**Comment by MagdaKrzyz** [comment]
It used to be entered manually next to the PoS. Then Pietro put the label
to the right of the headword (I remember that when I objected to that you
supported me) I have never used this function. It might be removed from the
app all together.

pt., 13 maj 2022 o 11:48 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
I do not understand what is going on. Why are you commenting via email on very old issues? Even if you get a notification from GitHub please NEVER respond via email. Go to the issue itself. Then you will see that it is an OLD CLOSED ISSUE.

**Comment by eu-genia** [comment]
OK I see then something with GitHub sending around old messages again... Sorry, just ignore!
