### ISSUE TITLE
How to refer to a ms

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#394]
In this entry, in the etymological section I want to give a reference to the Ms D'Abbadie 39. Is it enough if I provide the reference to the ms. in BM, followed by the page/folio number? Or shall I create an entry "manuscript" in Zotero for this particular Ms., give it a tag and proceed as usual by providing the page number and the tag in the entry? Or shall I provide both?
Here is the entry: https://betamasaheft.eu/Dillmann/lemma/L8381cfc270f4437f9ed9d3ea1873e06f

**Comment by eu-genia** [comment]
I would never create Zotero records for manuscripts, only Bm references must be provided. Zotero is not meant for manuscripts.

**Comment by abausi** [comment]
I agree.

Il 13.05.2022 10:44, Eugenia ha scritto:

**Comment by MagdaKrzyz** [comment]
Good!



pt., 13 maj 2022 o 11:46 Alessandro Bausi ***@***.***>
napisał(a):
