### ISSUE TITLE
entries should be encoded as coming from TraCES, not Dillmann

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#397]
The entries should be encoded as coming from TraCES, not Dillmann. Could you change that? I cannot - the system does not allow me. 

https://betamasaheft.eu/Dillmann/lemma/L9ced4122bd0945a39b875906f939d66b
https://betamasaheft.eu/Dillmann/lemma/L16612c0f6b8640d8984f34d2adec4dd9

Masha, some of the entries are faultly structured and much info is lacking. There are guidlines (unter Tutorials, just at the beginning) to follow.

**Comment by eu-genia** [comment]
I have tried to change permissions, are changes possible now? If not I will edit the data on the backend

**Comment by eu-genia** [comment]
In general I think it could be helpful for everyone to not have issues titled "something is wrong" but rather with telling titles )

**Comment by MagdaKrzyz** [comment]
possible

pt., 13 maj 2022 o 11:32 Eugenia ***@***.***> napisał(a):

**Comment by MagdaKrzyz** [comment]
agreed

pt., 13 maj 2022 o 11:33 Eugenia ***@***.***> napisał(a):

**Comment by MagdaKrzyz** [comment]
as you can see I  changed the policy some time ago

pt., 13 maj 2022 o 13:19 Magdalena Krzyżanowska ***@***.***>
napisał(a):

**Comment by eu-genia** [comment]
great then you can edit on your own and i am closing this issue
