### ISSUE TITLE
"remove en meaning" button does not function

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#398]
The "remove en meaning" button does not function. I was not able to delete the following TraCES section

https://betamasaheft.eu/Dillmann/update.html?id=Lef9dacb3f0d64254803b7210483edf71&new=false&sourcela=dillmann&sourceen=traces#

**Comment by eu-genia** [comment]
can you retry? i have tried to fix permissions if that was the problem. if still does not work I will clean it

**Comment by MagdaKrzyz** [comment]
i cannot remove it

pt., 13 maj 2022 o 11:29 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
Just to understand: does the entire section 

`<Sen< #D \*gez*መቅድም፡\* >gez!maqdǝm> \*gez*፩፡ መቅድም፡\* ‘>fr>1 cuvette >’ [page, 13 l. 13-14 (ed.)]bm:ContiRossini1909LiberT, [page, 14 l. 9 (tr.)]bm:ContiRossini1910LiberV <L< \*gez*መቅደም፡\* >gez!maqdam> (L. D.) basin used for washing hands when entering the church; from qdm ‘be in front’, the basin being placed at the front of the entrance to church. [page, 353b]bm:Leslau1987dic >L> >S>`

needs to be removed?

**Comment by MagdaKrzyz** [comment]
Sorry! This is ok. Please do not remove iṯ̣

pt., 13 maj 2022 o 13:42 Eugenia ***@***.***> napisał(a):
