### ISSUE TITLE
Wrong transliteration from TraCES

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#403]
Wrong automatic transliteration: https://betamasaheft.eu/Dillmann/lemma/Lfb45749ff1a14f9d8879987181e4cf8c

**Comment by eu-genia** [comment]
Do you mean an additional rule is needed?
Is this possible for this form?
(NB: rules must be universal. if there may be a rule then next time someone gets into all this it surely can be implemented, but this rule must be very clearly formulated and apply to all such cases)

**Comment by MagdaKrzyz** [comment]
I do not know what is needed, but there is the automatic
transliteration appearing to the right from the headword and it is often
wrong. Sometimes there are two translit.: one from the TraCES annotation
the other automatic. This is confusing. Also one would need to manually
disambiguate some transliterations.

pt., 13 maj 2022 o 11:43 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
Someone has to correct Traces data. 
I believe the disambiguation is provided on hovering.

**Comment by eu-genia** [comment]
The automatic is a different matter.

**Comment by eu-genia** [comment]
What would the correct transcription be? You can use this issue to insert all terms that must be corrected and I will try to see if I can fix them in the TraCES data.
You can also insert the correct version in the record itself.

**Comment by eu-genia** [comment]
OK I see there is already an issue for that
https://github.com/BetaMasaheft/Dillmann/issues/372
no need to open new issues, we shall keep only #372

One problem = one issue
