### ISSUE TITLE
’am" to be deleted 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#407]
https://betamasaheft.eu/Dillmann/lemma/Lf47b474ca0724caaa76fffe1f6a3084c

**Comment by eu-genia** [comment]
should it be Ge'z? or what/where?

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Dillmann/issues/393

**Comment by MagdaKrzyz** [comment]
Zhenia, I think we should abandon the labeling: Geez, Amharic, Tigrinya,
Somali etc. whenever we enter a new word. All words are Geez by default
because they are found in Geez texts.
There is a section "Comparative and etymological date" where we write the
origin of the word. In this way we do not have to judge right away or even
at all whether the word is Geez or Amharic. The more that often it is
impossible to know.

pt., 13 maj 2022 o 11:31 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
Done
