### ISSUE TITLE
online DL Abbrev.: "M. M." & "Lib. Myst." - Mashafa Mistir - which LIT references? help in clarification

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#41]
- there are two abbreviation in printed DL, list of Sigla: 
a) Lib. Myst. = Liber Mysteriorum coeli et terrae, Aeth., Parisiensis, a Ludolfo lectus. 
b) M. M. = Mashafa Mistir. 
These are two distinct works, but to be sure, I would like to ask for clarification. 

- identification of "Lib. Myst." = maybe the Codex N.B. Paris, No. 118 (Zotenberg, Catalogue, pp. 140-141, "Livre des mystères du ciel et de la terre" with a handwritten note by Ludolf) = BM Database: BNFet118 
(lit.: Lusini & Fiaccadori, EAe 3, pp. 945-946)
proposed LIT reference no.: LIT1954Mashaf 
(would this DL abbrev. also be linked to the manuscript entry? or simply the textual unit entry?)

- identification of "M. M." = Mäshafä Mest'ir = maybe Collection Krapf, Codex Tübingen, later Basel, 372 folios (DL Prolegomena IX col. a))
(lit.: Bausi, EAe 3, pp. 941-944)
possible LIT reference nos.: 
a) LIT1951Mashaf (problem: entry underspecified) 
b) LIT1952Mashaf (problem: database entry currently dysfunctional) - this one, yes?

**Comment by thea-m** [comment]
Exactly, Lib. Myst=LIT1954Mashaf and M. M=LIT1952Mashaf 
(I fixed LIT1952Mashaf, please let us know whenever you come across such errors)
