### ISSUE TITLE
part of speech needed 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#412]
Amharic part of speech needs to be aded to the abbreviations, instrumentalis
https://betamasaheft.eu/Dillmann/lemma/L92380b42301b4df2b60562bfdcd550bb

**Comment by eu-genia** [comment]
Do you mean the schema has to be enhanced for all records or is it something local?

**Comment by MagdaKrzyz** [comment]
The schema has to be enhanced.

pt., 13 maj 2022 o 11:40 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
I have added Inst. if that was requested

**Comment by MagdaKrzyz** [comment]
Could you changed into "instr." ? 
We also need to add "particle" to the list of PoS. Could you do that? No abbravaition since there is already "part." for "participium"

**Comment by eu-genia** [comment]
Sure, just to be clear - the list is originally of abbreviations used by Dillmann. It is not a true list of POS, neither it is a grammar description. This has never been done (probably the parser was fed with TraCES POS list, but I have not studied the parser)

**Comment by eu-genia** [comment]
The current list has the only purpose of creating tooltips when you hover over an abbreviation. Nothing else.
