### ISSUE TITLE
Unnecessary data appears in the pdf file of the entry ደጅ

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#415]
In the pdf file of the following entry 
https://betamasaheft.eu/Dillmann/lemma/L8d2461bb67e44df197ad76ef2d4d4574

appears data that do not belong to the entry: 
Cross-references
for ርእሰ፡ ህበይ፡ vid. ርእስ፡

Here is the full pdf version:
ደጅ
TraCES en
daǧǧ, ዴዴ፡ dedde Abbadie 1881, 790 subst.
‘door, doorway, entrance’ Kane 1990, 1826a
a)ደጄ፡ ሰላም፡ daǧǧe salām; ደጀ፡ ሰላም፡ daǧǧa
salām Conti Rossini 1909, 10 n. 12, ደጌ፡ ሰላም፡
dagge salām Conti Rossini 1909, 11 n. 2 main gate
ደጄ፡ ሰላም፡ ዘሥዕለ፡ አንበሳ። ናዕዴር። ላዕላይ፡
ደጄ፡ ሰላም። ወውሣጣይ፡ ደጄ፡ ሰላም፡ ወቤተ፡
ግብር። ‘et la porte principale (daǧē salām) du
seʿela anbasā. ― Le Nāʿdēr [aura soin] de la
partie supérieure (?) du (?) daǧē salām, [du]
daǧē salām intérieur, et [de] la maison réservée
à la préparation des espèces eucharistiques (bēta
geber)’ Conti Rossini 1909, 10 l. 24, 11 l. 1–2 (ed.),
Conti Rossini 1910, 11 l. 9–12 (tr.)
Cross-references
for ደጅ፡ አዝማች፡ vid. አዝማች፡
Comparative and etymological data
from Amharic ደጅ daǧǧ
Cross-references
for ርእሰ፡ ህበይ፡ vid. ርእስ፡
Bibliography
Revisions
- Magdalena Krzyżanowska added variant on 20.5.2022
- Magdalena Krzyżanowska correction on 20.5.2022
- Magdalena Krzyżanowska added variant on 20.5.2022
- Magdalena Krzyżanowska added compound on 19.5.2022
- Magdalena Krzyżanowska added entry on 13.5.2022
- Magdalena Krzyżanowska added pos on 24.1.2022
- Magdalena Krzyżanowska added new word on 10.12.2021

**Comment by eu-genia** [comment]
for some reason this was part of the XML file. cleaned.
