### ISSUE TITLE
Entry ገዜ is unavailabe 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#417]
Entry ገዜ, strangely occuring together with ኅዱግ, doesn't open. 
![Screenshot 2022-05-24 123955](https://user-images.githubusercontent.com/29131132/170015226-5ef04c23-8d53-4e92-89d3-c4ffb57e5b79.png)

**Comment by eu-genia** [comment]
the link points to two entries at the same time, this cannot of course work...

```
err:XPTY0004 cardinality error: sequence with more than one item is not allowed here [at line 967, column 12, source: /db/apps/gez-en/modules/app.xql]
In function:
	app:itemcontent(item()*, item()*) [1086:5:/db/apps/gez-en/modules/app.xql]
	app:showitem(node()*, map(*), xs:string?) [-1:-1:/db/apps/gez-en/modules/app.xql]
```

**Comment by eu-genia** [comment]
ኅዱግ
https://betamasaheft.eu/Dillmann/lemma/Lc169798f4e8c4a9c854be95b36421d15

ገዜ et ኅዱግ
https://betamasaheft.eu/Dillmann/lemma/L0608f1c3bfa94dbb998178bc0acd835d

the second entry must be edited (or deleted and recreated without mixing)

**Comment by MagdaKrzyz** [comment]
When opened for editing the second entry looks perfect. There is nothing to change....
Should I delete it and create a new one? Or you know how to fix it?

**Comment by eu-genia** [comment]
I don't know where the wrong linking was, but I have resaved the entry under a new name and now all seems to be fine

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Dillmann/lemma/L0608f1c3bfa94dbb998178bc0acd835e
