### ISSUE TITLE
Needed additional signs for the subentries - Compounds

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#420]
Zhenia, are you capable of adding signs to mark the subentries? I have used up all the letters of the English alphabet but there are still some subentries left. I wrote a') , b') etc. but the "prim" sign is not encoded. Take a look at this entry towards the end:
https://betamasaheft.eu/Dillmann/lemma/L153553e0e5e0448f9ba1221d2cf70045

The best would be to get rid of the alphabetical signs at all for the compounds and have instead a neutral symbol--- that one does not need to put into an order. For instance ■. 
What do you think? We could also add the general label "Compounds" just like now we have "Leslau", "Cross-references".

**Comment by eu-genia** [comment]
I will look into it but I think the code wants an ASCII symbol. Special characters are a problem.
Why not try aa ab ac ad?

**Comment by MagdaKrzyz** [comment]
I have tried. It does accept aa , bb either. 
How about starting a new compound from a new line? Also a problem?

**Comment by eu-genia** [comment]
The code wants an ID, and a single symbol, 
You do need an ID normally, and a unique one, to be able to refer to an element.
I have now introduced "•" to the set of symbols that may be used (it is an ASCII symbol) and tried it out, it works on the surface. But of course the xml has an error in the sense that if you repeat • it gets several elements with the same ID so one cannot refer to them any more.

**Comment by eu-genia** [comment]
or maybe i could add another alphabet. cyrillic? greek is there anyway, one could use also greek letters for numbering

**Comment by eu-genia** [comment]
added, you can try to use
абвгдежзийклмнопрстуфхцчшщэюя
for compounds

**Comment by eu-genia** [comment]
Under referring I mean pointing, with `#`

**Comment by MagdaKrzyz** [comment]
Good, then we don't need it with compounds.

**Comment by eu-genia** [comment]
when you speak about a "section like Leslau" - what exactly do you mean? you must be very specific.

**Comment by eu-genia** [comment]
I have introduced a subtitle possibility "Compounds", it is called X
check https://betamasaheft.eu/Dillmann/lemma/L153553e0e5e0448f9ba1221d2cf70045
![image](https://user-images.githubusercontent.com/17987728/176382095-cf651050-09f5-4030-a329-4532fd90322f.png)

I have added the n-dash to the symbols that can be used

**Comment by MagdaKrzyz** [comment]
Would it be possible to get rid of the right parenthesis after the n-dash? For esthetic reasons. It is ok how it is now but visually a bit disturbing.

**Comment by eu-genia** [comment]
no, or rather it is not worth it for me - it would be easy to remove it for ALL meanings, but then you would not have it also for the normal a) b) c) etc where you need them

**Comment by eu-genia** [comment]
Here are the entries with the compounds with the n-dash:
https://betamasaheft.eu/Dillmann/lemma/L153553e0e5e0448f9ba1221d2cf70045
https://betamasaheft.eu/Dillmann/lemma/Lef4ed3d79c8d44339fd73c7283d0123f
https://betamasaheft.eu/Dillmann/lemma/L1e32e08f156f4486bc3949b3fca5eeb8
https://betamasaheft.eu/Dillmann/lemma/L968149f7fc1748479a9f8482bc3f49c0
https://betamasaheft.eu/Dillmann/lemma/Lf6d41651ab0449f2ad1c8ebe891cb790
https://betamasaheft.eu/Dillmann/lemma/L5bc9c13e2ade4ff4b36198a957d94102
https://betamasaheft.eu/Dillmann/lemma/L33a2c869e7e343a0859911ef499b9068

**Comment by eu-genia** [comment]
are line breaks ok here? 
or i should have to see if we can get some level of meanings without `xml:id `assigned....

**Comment by MagdaKrzyz** [comment]
Yes, a line break is good. 
I have gone through the guidlines that you sent me. There are examples of dictionaries that use TEI and are quite nicely structured. I understand that they have a bunch of professionals working for the layout, but maybe we could ape sth. things?
The compounds should be under the constituent called: 
[re] (related entry) contains a dictionary entry for a lexical item related to the headword, such as a compound phrase or derived form, embedded inside a larger entry.
In the section dealing with related entries there is an example from the Collins dictionary. As far as I (mis)understood the related entries are encoded as different types:  <re type="derived"> . Would be that an option for us?

**Comment by eu-genia** [comment]
one could but really this is becoming much much much much much work that i am not supposed to be doing.
this is not just a `re `element, if you read and look at examples a `re `is a "subentry" which should have a `form`, a `sense`, etc.; it expects certain elements without which it would be invalid and at the same time many of the elements currently assigned would be invalid within `re`.
It is all possible of course but it requests a whole lot of reprogramming and back-editing.
i also notice that our xml encoding does not really correspond to the guidelines, the examples i see encode a translation as `<def>`, use `<xr>` for cross-references etc etc, (none of these are used in our files), so there is a lot of improvement possible, but this should really be the task of another project, where someone could take care of everything.
I would say I am there only to solve urgent issues and bugs, I am not at all responsible for the dictionary, I just am trying to make your work possible in some way.

I will look at the elements available and try to find a solution for compounds, but it will probably not be the best one, but the easiest for me.

**Comment by MagdaKrzyz** [comment]
If there is green light for the line break I don't need anything more for the moment. As for the compounds I can turned them into subsenses, which is not a bad idea from the lexicographical point of view. Trival compounds should not be included in the dict. at all.

**Comment by eu-genia** [comment]
I think the compounds should be turned to a list of numbered submeaning, with a-b-c- etc, this will solve all problems

**Comment by MagdaKrzyz** [comment]
ok
