### ISSUE TITLE
"Lit." to be put on the list of abbrevations

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#421]
I use the abbraviation of "literally", "lit.", in some entries. Could you please put it on the appropriate list so that the whole name appears while hovering ?
Here is an entry where I use "lit.":
https://betamasaheft.eu/Dillmann/lemma/L8b696905cc3342dfa56b4c3a77f9c8e2

**Comment by eu-genia** [comment]
as far as i can see abbreviations are expanded if they are within the gramGrp element (POS), so adding to the same list where subst. = substantivum is would not bring anything

**Comment by MagdaKrzyz** [comment]
How about "Abbreviations" under "Resources"? There are similar terms included.

**Comment by eu-genia** [comment]
for example?

**Comment by MagdaKrzyz** [comment]
I looked at the list in Dillmann's paper edition. There is a list of abbreviations that include terms similar to my "lit.". I thought they are put, as in the book, together with the abbr. of texts. Apparently not. But in the online dictionary, in the Dillmann's part these similar terms are expanded upon hovering. For instance 
"c." - cum 
"seq" - sequens
"rom" - romae editionis
"ann" annotatio
"cfr." conferas
Perhaps there is a different list that includes them. 
I can see that many abb. that are expanded in the book are not there in the online dictionary. For instance  i.q. Maybe once we could enter them.

**Comment by eu-genia** [comment]
these words are all expanded within PoS grammatical description.
this is what the code does.
if you can show me a different case I can see what I can do.
Sure you can continue the list of Dillmann abbreviations that were missed.

**Comment by MagdaKrzyz** [comment]
Ok, I can see the abbr. included in the list of pos. 
"these words are all expanded within PoS grammatical description." Just for me to know, where you can see them? I have an acces only to the following list and they are not there.
![Screenshot 2022-07-02 000904](https://user-images.githubusercontent.com/29131132/176973247-74697281-9ffa-4649-9386-e2e249ec5e2e.png)

**Comment by eu-genia** [comment]
i see the code, i work in the backend
you can see the code on the github 
there are a list of POS abbreviations expanded already on conversion from the online edit format to xml (https://github.com/BetaMasaheft/Dillmann/blob/master/gez-en-2.6/xslt/upconversion.xsl) and a list of general and works abbreviations https://github.com/BetaMasaheft/Dillmann/blob/master/gez-en-2.6/abbreviaturen.xml, but for some reason adding there alone does not help, will try to explore more

**Comment by eu-genia** [comment]
OK, fixed.
In order for an abbreviation to be expanded it has to be **marked up as an abbreviation** `((abbr.))`
so in this case `((lit.))`
