### ISSUE TITLE
"TraCES" meaning - replace(enhance)?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Dillmann#423]
The meanings added post-Dillmann now appear as
![image](https://user-images.githubusercontent.com/17987728/177303848-eb72e0e8-bf8b-4368-89c1-2eb303b9eeec.png)

But they are not TraCES any more.
I suggest adding the explanation "and follow-up projects" (done)

And possibly even replace TraCES in the viusalization with HLCEES, i.e.
![image](https://user-images.githubusercontent.com/17987728/177304139-c0eec35d-0e1d-424b-8522-09d7ca05c400.png)
@MagdaKrzyz

**Comment by MagdaKrzyz** [comment]
I would go for the second option with the name of HLCEES as a place uniting all those projects .

**Comment by MagdaKrzyz** [comment]
There is one problem with the change into HLCEES (I am sorry for reporting this issue only now). In cross-references I add in paranthesis that a given word is found in the TraCES section, not Dillmann. Take a look here, under Cross-references:
https://betamasaheft.eu/Dillmann/lemma/La11f51c2bfb94d42a0639beb51abd548

By now I have used the label in quite a number of entries. I can change them into HLCEES whenever I come across them while adding new lexemes. What do you think?

**Comment by eu-genia** [comment]
This is up to you to decide.  I can change the label back.

**Comment by MagdaKrzyz** [comment]
Then it is better to go back to the TraCES label with the new explanation.

**Comment by eu-genia** [comment]
done
