### ISSUE TITLE
Encoding Grebaut's Supplement

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#424]
Soon I will start working on copying entries from Grebaut's Supplement. I think it is better to encode the entries in the way we do it with Leslau---as a separate section. Could you introduce the encoding symbols: <G< >G>?

**Comment by eu-genia** [comment]
Should be possible, please try and close if all OK

**Comment by MagdaKrzyz** [comment]
it works well

**Comment by MagdaKrzyz** [comment]
Could you please change "Grebaut" to "Grébaut" as the section label ?

**Comment by eu-genia** [comment]
sure, done
