### ISSUE TITLE
Dillmann entry marked as new

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Dillmann#427]
I noticed that Ld13ede78d0ac40e995e71bf0d9aa7a17 is marked as new even if it is present in Dillmann, probably ND must be removed, and linking checked

**Comment by MagdaKrzyz** [comment]
When you open the entry for editing Dillmann's part is wrongly placed below Traces. On the surface the arrangement is seemingly correct. I have tried to change the order but the problem is deeper.

**Comment by eu-genia** [comment]
the problem is not deeper, you only needed to delete the element `{ND} `which should only be added to new lemmata not in Dillmann

I have now deleted it for you

**Comment by eu-genia** [comment]
(the green NEW badge appears in the same place where for Dillmann you have the PDF link for NEW entries)

**Comment by eu-genia** [comment]
(since the entry is again out of numbered sequence the link to PDF has to be fixed manually by `|{pdf.1234}|`
