### ISSUE TITLE
Empty pointer

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#431]
There is an empty entry in front of https://betamasaheft.eu/Dillmann/lemma/Lf6d41651ab0449f2ad1c8ebe891cb790.

**Comment by eu-genia** [comment]
right, no record n=11324
will try to solve this

**Comment by eu-genia** [comment]
the entry must be deleted... i can move the last entry created ([ሀልዎ](https://betamasaheft.eu/Dillmann/lemma/L6eb57b4154f4410c98848053aaaec9ff)፡ to that spot changing the number from 12896 to 11324
but there are probably many more cases like that

in some very optimistic future, should there be another project to work with the data, one could set up a re-sorting according to an established alphabetical order and rearrangement of records according to that new order, but this is possibly never going to happen
