### ISSUE TITLE
Entry ሠፈጠ to be linked to page 1394.

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#432]
The entry ሠፈጠ should be linked to page 1394. The referencing code put inside the entry does not work

https://betamasaheft.eu/Dillmann/lemma/Le297611adc574a0b90febcc58a2c7ce3

**Comment by eu-genia** [comment]
what is it that does not work? when I click I get 1393/1394

**Comment by MagdaKrzyz** [comment]
it should be ONLY page/column 1394, and not 1393/1394.

**Comment by eu-genia** [comment]
I guess this was one of the entries I had already previously introduced a `cb`, have removed it
