### ISSUE TITLE
Link to an ms. in Bm 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#433]
Grebaut refers often to ms. d'Abbadie 217. Now it is also available in Bm. May I link the entry in DL with that in Bm in the following way?
Could you check that?
https://betamasaheft.eu/Dillmann/lemma/L9348ae3144f54e8cb1722df729aba65e

**Comment by eu-genia** [comment]
why not

**Comment by MagdaKrzyz** [comment]
ok
