### ISSUE TITLE
empty entry after ሰሰወ

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#434]
There is an empty entry after the following one:
https://betamasaheft.eu/Dillmann/lemma/L9fc6a6384ea04b80a31e36e8aebda59c

In the empty place there should be the lemma ሰቀመ --- it is missing. 

Afterwards comes:  https://betamasaheft.eu/Dillmann/lemma/L07a7baefa5624978a818aa8351c50184

**Comment by eu-genia** [comment]
so you have n="12074" and n="12076", entry n="12075" must have been deleted at some point.
whenever the sequence is broken the pointers are empty

**Comment by eu-genia** [comment]
It would be good to keep all these cases in one issue, as it is one and the same problem as https://github.com/BetaMasaheft/Dillmann/issues/431 and https://github.com/BetaMasaheft/Dillmann/issues/425#issuecomment-1211041719, and not open a new one every time you find a missing entry.

**Comment by eu-genia** [comment]
I could not find 12075 or ሰቀመ among deleted files; if the entry is relevant it probably should be created, then I can assign number 12075 to it fixing the sequence

**Comment by MagdaKrzyz** [comment]
Here is the entry ሰቀመ
https://betamasaheft.eu/Dillmann/lemma/L7cd75298b09c4f61a5de66240950244f
Could you assign it number 12075?

**Comment by eu-genia** [comment]
done
