### ISSUE TITLE
Page break ---- necessary?

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#435]
There is a page break indicated in the following entry:
https://betamasaheft.eu/Dillmann/lemma/L429dbafa332c4676bd607da2871233e3

What does the red encircled number mean? That a new page begins in the next entry (see the screenshot)? 
The present entry is wholly contained on p. 1396 so to my mind there is no reason to indicate 1396/1397. But someone thought of it differently, maybe there is sth. to it?
![Screenshot 2022-08-29 141903](https://user-images.githubusercontent.com/29131132/187200347-bafec266-b24a-4df6-b594-c59c186ecc38.png)

**Comment by eu-genia** [comment]
this is the result of the initial conversion from the doc file by Andreas to xml
Andreas marked page numbers in his doc file, they were converted as page breaks

**Comment by eu-genia** [comment]
(you will find such page break in every record for a lemma which is the last one in the column I assume)

**Comment by MagdaKrzyz** [comment]
Thank you!
