### ISSUE TITLE
Unaccesible entry 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#437]
There is an unaccessible entry after : 
https://betamasaheft.eu/Dillmann/lemma/L7cdd0c1ecf1341d69b232fdf7fb6d8e1

**Comment by eu-genia** [comment]
the deleted 12600 is followed by 12601, which is L19d7451928994b4a954e66283d60d603

**Comment by eu-genia** [comment]
I have now batch solved all those issues, if the next/previous entry is missing, then the following one is shown
If a deleted entry should be recreated back this is up to you

**Comment by MagdaKrzyz** [comment]
I understand the problem well so no need to explain it to me again. 
I understood the problem with the deletion some time ago and so I don't do it any more. In fact I cannot delete entries because this function is inactive for me. That is why I asked you last time to delete a meaning. The existing deletions happended much earlier --- Pietro forgot to warn me that it disturbed the counting. 
I am asking you only for fixing the numbers so that there is no empty pointer.

**Comment by eu-genia** [comment]
As I wrote above, the issue is solved and closed, the app shows the next entry available
