### ISSUE TITLE
a wrong LLA page is attached to an entry

### ISSUE THREAD

**Issue by mbulakh** [BetaMasaheft/Dillmann#438]
Entry [ኤክስድር] (https://betamasaheft.eu/Dillmann/lemma/Ldc6ca702575a4275af3ebb14a4c28d54) 
leads to page 1424, whereas the correct page is 1405

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Dillmann/issues/425

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Dillmann/issues/425#issuecomment-1211247701
