### ISSUE TITLE
PoS to be added 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#439]
Could you please add "pass. part." with the extension "passive participle” to the list of parts of speech?

**Comment by MagdaKrzyz** [comment]
Could you also add “act. part.“ with the extension “active participle”?

**Comment by eu-genia** [comment]
in parallel to #429 I added `act. particle` and `pass. particle`

**Comment by MagdaKrzyz** [comment]
"Participle" is an English equivalent of "participium". I asked for the extension "participle" because it is Leslau's term. I think "pass. part." and "act. part." will be treated as one so they do not interfere with the single "part". Am I right?

**Comment by eu-genia** [comment]
ok let us try
