### ISSUE TITLE
Roman number II does not appear correctly

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#440]
In the following entry, Dillmann's part, the Roman number II does not appear correctly on the surface:
https://betamasaheft.eu/Dillmann/lemma/Le4d650c370464996939e7bfb43dd6444.

I've looked at another entry with Roman II, and there the same encoding works well. 
https://betamasaheft.eu/Dillmann/lemma/L22c2e71ac6c0443e8f05d480b3ac9e85

**Comment by eu-genia** [comment]
fixed in XML, hope remains stable
