### ISSUE TITLE
something is wrong

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Dillmann#443]
It seems like the entry for "ቅኔ" in Online Dillmann has somehow also swallowed the entry for "ቅንየት". I think they should be two separate entries.

https://betamasaheft.eu/Dillmann/?mode=none&q=ቅንየት&id=Ld0b618365d854d66a520ba121afd986e

**Comment by MagdaKrzyz** [comment]
Yes, indeed. They are two separate entries that have conflated. It is a technical problem that perhaps only Zhenia can solve. 
The next entry for "ቅንየት" beginns after page brake |{DiL.0449}|.

**Comment by eu-genia** [comment]
well not purely technical, it happened obviously on automatic conversion, but can be edited also by the users. I can do it too of course but I must understand more.

where does this https://betamasaheft.eu/Dillmann/lemma/L9da6996b869249dcac020e9ea68ed33a belong? should everything after the page break go into here or is this a separate entry?

(NB if you or I create a new entry it will be as always out of the alphabetical sequence)

**Comment by eu-genia** [comment]
i checked the pdf, it is a separate entry. so a new one simply should be created for the merged ቅንየት. 

one should simply cut out what does not belong
` \*gez*ቅንየት፡\* et \*gez*ቅኔት፡\* [[ +n. act.+ ]] et [[ +subst.+ ]], ((Pl.)) \*gez*ቅንየታት፡\* et \*gez*ቅኔታት፡\* >3> <1< >la> dominatio >, >la> dominium >, >la> possessio >: \*gez*ቅንየትከ፡ ወምልክናከ፡ ኵሎ፡\* \*grc*τὸ πάντων σε δεσπόξειν\* *Sap.|12,16*; \*gez*ቅንየት፡ ወምልክና፡\* *F.N.|40*; \*gez*እመ፡ አኀዝ፡\* (pignus) \*gez*ኢወፅአ፡ እምእዴሁ፡ ኀበ፡ ቅንየተ፡ ካልኡ፡\* *F.N.|27*.>1> <2< >la> actus subjiciendi > vel >la> subjugandi >: \*gez*እስከ፡ ትቀንይዋ፡ ለሀገር፡ እስመ፡ ቀርበ፡ ቅንየታ፡\* *Jsp.|304.*p.| >2> <3< >la> servitus >, \*grc*δουλεία\* *Esth.|7,4*; *Ex.|6,6*; \*gez*ቤተ፡ ቅንየት፡\* *Ex.|13,3*; *Ex.|13,14*; *Lev.|26,45*; *Deut.|5,6*; *Deut.|6,12*; *Deut.|7,8*; *Lit.|173,1*.>3> <4< >la> creatura serva > *Hen.|75,3* ((c.)) ((var.)); \*gez*ባሕር፡ አመቱ፡ ወወሓይዝተ፡ አፍላግ፡ ቅንየታቲሁ፡\* Lit. Epiph.>4>`
and paste it to a new entry

**Comment by MagdaKrzyz** [comment]
Good, I can do it . 
I thought that zou might be able to restore the order. Otherwise I can easly do it.

**Comment by eu-genia** [comment]
no, the ordering numbers were created on the initial conversion and entries are arranged according to these numbers, you cannot insert a number between 3522 and 3523.
you can of course replace the content of https://betamasaheft.eu/Dillmann/lemma/L9da6996b869249dcac020e9ea68ed33a with the pasted one (then this one will be 3523), and create a new entry for `subst.servitus: ቅንያተ፡ መሪር፡  Ssal. Req ` instead, then the latter will be out of sequence
