### ISSUE TITLE
Grébaut's name does not appear in full in pdf

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#445]
If you make a pdf file from an entry that contains info from Grébaut's dictionary, his name does not occur in full but in the form of  'G)'. See also the attachment.
[L587eb5d26737452fb7b285865544c427.pdf](https://github.com/BetaMasaheft/Dillmann/files/10207776/L587eb5d26737452fb7b285865544c427.pdf)

This is different with other subsections, such as Leslau, Cross references etc. 
Here a few links for your trials:
https://betamasaheft.eu/Dillmann/lemma/Lcb52890bdbb2413a8d8f9a55f928e6da
https://betamasaheft.eu/Dillmann/lemma/L587eb5d26737452fb7b285865544c427
https://betamasaheft.eu/Dillmann/lemma/L224e119ea8c249cbaffaf84a6e919e7b
https://betamasaheft.eu/Dillmann/lemma/Lb50d964f757f4f0b8c6720bd52c2261c

**Comment by eu-genia** [comment]
better now?

**Comment by MagdaKrzyz** [comment]
yes! 
Thank you!
