### ISSUE TITLE
Two entries merged 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#446]
I wrote an entry over a diffrent entry (I doubled it by chance) and when I look for አሕላሊ I can still see it in the overwritten entry. 
Here is the entry : 
https://betamasaheft.eu/Dillmann/lemma/L291aa1fd5d984a9db6ee9a1ef132fd36. 
Could you please fix it ? Thank you in advance !

**Comment by MagdaKrzyz** [comment]
If one looks for the entry አሕላሊ one can see that the word occurs also in the entry ሕሉል (see the snapshot, in red). This is wrong. If one opens the entry ሕሉል there is nothing about አሕላሊ, which is correct. For some reason the content of the entry አሕላሊ occurs within ሕሉል but only in the searching mode. It should be removed from the entry ሕሉል 
Link to ሕሉል https://betamasaheft.eu/Dillmann/lemma/L291aa1fd5d984a9db6ee9a1ef132fd36.
Link to አሕላሊ https://betamasaheft.eu/Dillmann/lemma/L3b2a9b42d0fe4bc9905c6ff12558078b.
Is it clear now?
![አሕላሊ](https://user-images.githubusercontent.com/29131132/210837474-d3faa7d0-fabc-4139-be36-84e9f3601c93.png)

**Comment by eu-genia** [comment]
done
