### ISSUE TITLE
Cannot log in to DL

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#447]
I receive the following message while trying to log in to DL.

An error has occurred
An error has been generated by the application.

exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Database is read-only [at line 38, column 5]
In function:
	log:add-log-message(xs:string, xs:string, xs:string) [283:4:/db/apps/gez-en/modules/log.xqm]
	app:logging(node(), map(*)) [-1:-1:/db/apps/gez-en/modules/app.xql]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [428:17:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*) [230:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [133:51:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [90:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:apply(node()+, function(*), map(*)?, map(*)?) [41:5:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]

**Comment by eu-genia** [comment]
@duncdrum @line-o  this morning the app became unresponsive. The server did not seem to react properly. I rebooted it, but there was  this error - some permissions gone awry, and I could not find where.
I have tried to restart again but Exist does not start (it appears in `top `on and off with 0.3 cpu and then disappears again). It looks like we urgently need help.

**Comment by eu-genia** [comment]
Thank you! I have deleted some of the backups and this seems to have solved it for now. I have to see if I can increase the disk space...
