### ISSUE TITLE
No new IDs available?

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#449]
The programme refuses to save new entries. I receive the following info 
![Screenshot 2023-01-30 130241](https://user-images.githubusercontent.com/29131132/215472207-f65dcc25-c658-4dcb-aa41-698715331d4c.png)
It seems to fail to assign new IDs. Could it be?

**Comment by eu-genia** [comment]
yes see https://github.com/BetaMasaheft/Dillmann/issues/428

**Comment by eu-genia** [comment]
I have tried to add some, please retry and close if all OK
