### ISSUE TITLE
online DL Abbrev.: converge abbrev. "Genb." and "Sx. Genb." 

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#45]
- the abbreviation "Genb." as such is not attested in printed DL Sigla. 
- it occurs with the abbreviation for Synaxary as: "Sx. Genb." meaning "Synaxary entry for the month of Genbot/Gembot" (ca. 220 entries) 
- exception: "Genb." as single occurence without "Sx." in front of it: online DL entry for ብልኅ
http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/L7f65bc9141384c2b81f48c86f5ff6542 
(where in fact the context of the lemma entry suggests that it is also taken from a synaxary entry) 
- hence: please unify entries

**Comment by PietroLiuzzo** [comment]
what does Enc. means? e.g. in Sx._Enc._Sen. ?

**Comment by PietroLiuzzo** [comment]
fixed L7f65bc9141384c2b81f48c86f5ff6542

I think we need an abbreviation entry for each, as we have one for each letter of Paul, for example.

Sx. alone occurs only 3 times, not clear why.

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.aai.uni-hamburg.de/Dillmann/search.html?ref=ref&q=Sx.

**Comment by fitawari** [comment]
The abbreviation "Enc." is given in printed DL list of Sigla as:"Encomia Synaxarii, Actis singulorum dierum addita; citantur secundum menses et dies, vid. Sx."The structure of the abbreviation "Sx. Enc. Sen." is like: [Synaxary] [Praise of Saints] [month of Sené]. 
The ideal case for normalization would be this: 
Sx. Enc. Sen. 19, 5 = Synaxary entry for the 19th of the month of Sené, line 5. 

 


      Von: Pietro Liuzzo <notifications@github.com>
 An: SChAth/dillmann <dillmann@noreply.github.com> 
CC: fitawari <fitawari@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 10:05 Montag, 3.April 2017
 Betreff: Re: [SChAth/dillmann] online DL Abbrev.: converge abbrev. "Genb." and "Sx. Genb." (#45)
   
what does Enc. means? e.g. in Sx._Enc._Sen. ?—
