### ISSUE TITLE
Mistakes in the layout

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#450]
There are some mistakes how the entry has been layouted at the beginning. https://betamasaheft.eu/Dillmann/lemma/L5c4d1bc34abb4e71a039d8923b4e22d2

There should be only one headword; the second word goes down to the body of the entry. '1' followed by a parenthesis go up (it is not here a separate meaning nr 1 ) as well as the rest of the entry. See the screenshot.
![Screenshot 2023-02-10 133533](https://user-images.githubusercontent.com/29131132/218094648-8afce7f0-f578-4a96-a545-f2e40d3dece5.png)

**Comment by eu-genia** [comment]
it seems that you have tried to fix it?

**Comment by eu-genia** [comment]
but the lemma itself is doubled now

**Comment by MagdaKrzyz** [comment]
yes, but I cannot fix the headword. Could you do that ?

**Comment by eu-genia** [comment]
done
