### ISSUE TITLE
Wrong location of the entry?

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#453]
There is some problem with the location of the following entry in the sequence of newly added entries. I could not save it, it saved somehow, but it shows that there is no previous entry.  https://betamasaheft.eu/Dillmann/lemma/L111vu7ss7k96hg7oogza85payazcdilp
Screenshot in any case 
![Mallahi](https://github.com/BetaMasaheft/Dillmann/assets/29131132/5b209f0e-c486-4f7a-8c2a-17c10e4d7b6b)

**Comment by eu-genia** [comment]
this is because each new one is added with a new incremental number, and if there is an empty record then you see an empty screen. if you go further back then there is a couple more of empty "test"s...

**Comment by MagdaKrzyz** [comment]
I saw it but this is rather unusual.
![Erroṟmessage](https://github.com/BetaMasaheft/Dillmann/assets/29131132/9c89a879-d065-4004-bcb5-bcdef1b7d52e)
 And I cannot save an entry without getting an error message. Here it is

**Comment by eu-genia** [comment]
If you do not want to have an arrow into an empty place then the records you should edit/fill are https://betamasaheft.eu/Dillmann/lemma/L111pporg6nsauwdewb5vu2go8zvarvsn
https://betamasaheft.eu/Dillmann/lemma/L111qri1y39t6u4pgu5anm3p4jtt9xgfw
https://betamasaheft.eu/Dillmann/lemma/L1111g4gjgwse0uhf6vbwetfytest5hi2
https://betamasaheft.eu/Dillmann/lemma/L111j0m1v77fds7qynv79wee76jx62ae1
does neither work?

there is also something strange going on in XML with senses G and L appearing twice, have to explore how frequent that is and why...

**Comment by eu-genia** [comment]
I am going through all lemmatas of the last batch (starting with L111) removing the double senses (I still have to explore why they are transformed twice, it did not happen before!) and see more empty or test records (created but not filled)
could be filled
L1111g4gjgwse0uhf6vbwetfytest5hi2
L111j0m1v77fds7qynv79wee76jx62ae1
L111qri1y39t6u4pgu5anm3p4jtt9xgfw

**Comment by eu-genia** [comment]
@MagdaKrzyz wrote here https://github.com/BetaMasaheft/Dillmann/issues/454#issuecomment-1761172959
> * I have tried to use the four empty records. Twice I was successful, twice I could not write the headword for the records:
>   https://betamasaheft.eu/Dillmann/lemma/L1111g4gjgwse0uhf6vbwetfytest5hi2
>   https://betamasaheft.eu/Dillmann/lemma/L111pporg6nsauwdewb5vu2go8zvarvsn

i tried in the XML, but somehow the headword does not show still, have to explore more

**Comment by eu-genia** [comment]
Ok seems OK now, please check that all correct

**Comment by MagdaKrzyz** [comment]
These entries were already used up. 

L1111g4gjgwse0uhf6vbwetfytest5hi2
L111j0m1v77fds7qynv79wee76jx62ae1
L111qri1y39t6u4pgu5anm3p4jtt9xgfw
