### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Dillmann#456]
I have created a new entry L111zyobc8eg4fwg7xt8fmqjvgvc0owrv but it does not display, instead there is an error message (the same is with the entry above) 
![Screenshot 2023-10-23 101952](https://github.com/BetaMasaheft/Dillmann/assets/29131132/621e4470-f4ef-432a-a420-a77b8c7577a6)

_Originally posted by @MagdaKrzyz in https://github.com/BetaMasaheft/Dillmann/issues/454#issuecomment-1774671361_

**Comment by eu-genia** [comment]
I do not know what happened, I deleted the problematic record and recreated it as https://betamasaheft.eu/Dillmann/lemma/L111agn75taaxknby2e16rcwwvs20fcg8 

I have noticed that you tried again to create a record with a G subsense. Please can you try to NOT do so as long as this issue has not been solved? 

As I have written above https://github.com/BetaMasaheft/Dillmann/issues/454#issuecomment-1761125973 
"
I suggest that until I have discovered the problem you try to create entries without the sub-senses, save them, and then edit. I know this is an extra step but maybe this way we can at least do something."

I have tried again and created again an all new empty entry https://betamasaheft.eu/Dillmann/lemma/L111kjgyaxq3tav01sb62iqx2n7b0uc7o and it seems to be all OK so I do not know what caused the error. Please edit L111kjgyaxq3tav01sb62iqx2n7b0uc7o with new content and let us hope it works.

For each new type of error please open a new issue as it may be confusing otherwise.

**Comment by MagdaKrzyz** [comment]
I cannot access the record that you have re-created "https://betamasaheft.eu/Dillmann/lemma/L111agn75taaxknby2e16rcwwvs20fcg8". There is an error message

"I have noticed that you tried again to create a record with a G subsense. Please can you try to NOT do so as long as this issue has not been solved?" I am sorry. It must have been by mistake, I don't use it at all. If this is of no use at all I suggest that you remove all the new items and leave only Dillmann and Traces. Otherwise it is confusing. 

"For each new type of error please open a new issue as it may be confusing otherwise." --- I will

**Comment by MagdaKrzyz** [comment]
Ok, I see there is only TRaces and Other. What is the function of "Other"?

**Comment by eu-genia** [comment]
Very strange, as I have no error message at all.

The second question belongs to another issue. Please keep one issue = one topic. https://github.com/BetaMasaheft/Dillmann/issues/448

**Comment by eu-genia** [comment]
I can open https://betamasaheft.eu/Dillmann/lemma/L111agn75taaxknby2e16rcwwvs20fcg8 and as you can see it has the Grébaut subsense (created in the traditional way) - this is exactly what I am asking to not do. You should not use `<<G>> ` when creating. (You could use the new Grébaut option I had created and now again suppressed, but not the  `<<G>> `, the subsenses are only for editing, not for creating)

**Comment by MagdaKrzyz** [comment]
I cannot see the entry but received an error message 
![Screenshot 2023-10-23 131842](https://github.com/BetaMasaheft/Dillmann/assets/29131132/172e92b0-8057-4796-a7b1-c5ace6266a40)
I have done with the subsenses as you said (you meant the subsensed embedded in the entry), it works 
Thanks

**Comment by eu-genia** [comment]
I can access both records without any errors, I have tried out two browsers...
https://betamasaheft.eu/Dillmann/lemma/L111yla308cshntizuuvlll22drwqlt7s
looks to me to have the same content as 
https://betamasaheft.eu/Dillmann/lemma/L111j0pu5c8ifl64kigt97rqdkmpdkbrj
or am I wrong?

**Comment by MagdaKrzyz** [comment]
I cannot see the entries I will try tomorrow in the office. 
Yes, the same, as I wnated to correct the first one it saved as another entry. I will replace one of them

**Comment by eu-genia** [comment]
can you edit the doublet and close the issue? thank you!

**Comment by eu-genia** [comment]
It was again a UserManager issue, the permissions in `db/system/security/exist/accounts/Magda.xml` were off
