### ISSUE TITLE
Guidlines 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#457]
The guidlines for the Lexicon have disappeared from its usual place.
My suggestion was to make them more visible, more accessible because the rest of the tutorial is (poorly) styled in very large letters. 
My intention was not to get rid of them at all from the website, if this is what happened.

**Comment by eu-genia** [comment]
Very strange, I never did anything with the guidelines...

**Comment by eu-genia** [comment]
Do you mean this page? the guidelines for the user? https://betamasaheft.eu/Dillmann/tutorialextended.html 
I do not think there ever were guidelines for contributors apart from the shortcuts guide you see when you edit or create

**Comment by MagdaKrzyz** [comment]
"I do not think there ever were guidelines for contributors apart from the shortcuts guide you see when you edit or create"

You are right. I meant this shortcut. I am logged in and I cannot see it. It has disappeared. 
![Screenshot 2023-11-29 205758](https://github.com/BetaMasaheft/Dillmann/assets/29131132/ec60bdc6-3bcf-4b72-940d-e60ae5c22fd5)

**Comment by eu-genia** [comment]
![image](https://github.com/BetaMasaheft/Dillmann/assets/17987728/6839f087-6a4f-47b3-bcd9-342fe056fabe)
most probably you are not fully logged in, try to log out and log in

**Comment by MagdaKrzyz** [comment]
I was fulkly logged because I could edit entries. But indeed, now I can see it.... Thanks!
