### ISSUE TITLE
Old data appears while searching

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#459]
Could you please remove anything that belongs to the entry marrād (in the attachement) in the following entry:

https://betamasaheft.eu/Dillmann/lemma/L111lk76t88o268vlzesdaa2prtmvjfc7 

![marrad](https://github.com/BetaMasaheft/Dillmann/assets/29131132/08276a2f-004a-474e-b5a0-365bd338d228)

Thank you!

**Comment by eu-genia** [comment]
Like this? Close if OK

**Comment by MagdaKrzyz** [comment]
Just like this
