### ISSUE TITLE
Not able to save new entries

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#461]
I am not able to save new entries. I receive the following message:
![Error_message](https://github.com/BetaMasaheft/Dillmann/assets/29131132/a7e9cc65-6fa1-4f18-9011-a10f234e5d11)

The problem has already occured once and was fixed, as far as I remember, by reseting my login. 
Here is the related issue:  #454
Thanks for fixing it!

**Comment by eu-genia** [comment]
It did not want to inflect from next-id for some reason, but now seems to work

I have created 
L111sflhjty7p72p69muth1sgy4x3wk7p (testing my login)
and
L1114p83x5ctvax2qe4f5o1aofkjqbx6s (from your login)
please edit/fill

Hopefully should be OK for now

**Comment by MagdaKrzyz** [comment]
It works. The new entries have been edited.
Many thanks!

**Comment by MagdaKrzyz** [comment]
I cannot save a new entry. 
I have tried to save it without subsenses: 
<Sen< >gez!mǝʿǝrʿāre>
\*gez*ምዕርዓሬ፡\* >gez!mǝʿǝrʿāre> >fr>douceur> (de miel). Formation abstraite provenant du qualificatif quinquilittère
\*gez*መዐርዒር፡\*. Forme abstraite voisine: ((vid.)) \*gez*ምዕርዕርና፡\*. Texte und référence: \*gez*ጕርኤከ፡ ዘቦቱ፡ ምዕርዓሬ።\* Vatican City, Biblioteca Apostolica Vaticana, Aeth. 18, fol. 173v. 
{LB} [p., 106]bm:Grebaut1952SuppLexicon 
  {ND} >S>
An error message appears in the same vain as in the issue above: 
![Error_13_02](https://github.com/BetaMasaheft/Dillmann/assets/29131132/ada7c6ea-98f7-461d-891a-1fd6cf036d8a)

**Comment by MagdaKrzyz** [comment]
but this is a different matter. I followed the work flow but as you can see there is no way to create a new entry.

**Comment by eu-genia** [comment]
if the problem is as before then it is something with next-id.xml
retry

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Dillmann/lemma/L111yn9gxr17wzhmnm68km91htn2bczk2 looks ok to me
sometimes taking IDs from next-id.xml gets blocked (maybe ID already used somewhere)

you can reopen if the error repeats and I will refix

**Comment by eu-genia** [comment]
I have just created L111sf33bngq8coq9dbtxxrxn4p7a2d3c without any problem

https://betamasaheft.eu/Dillmann/lemma/L111sf33bngq8coq9dbtxxrxn4p7a2d3c
@MagdaKrzyz you can edit this ID and then see if you can create a new one
