### ISSUE TITLE
problems with creating a new entry

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#469]
When I try to create a new entry I receive this message :

Dear Magda, unfortunately L111tzcu57oqizg1u1fzwltjxjcaph0fx already exists! Please, hit the button below and try a different id.

It recalls the last new entry that I|ve created and does not give a new ID.

**Comment by eu-genia** [comment]
for some reason the app would not delete the used id from the list. i have deleted it manually, please let me know if the error persists with the next one

**Comment by MagdaKrzyz** [comment]
Yes, the error reoccurs. I have got the same message with a different id: 
Dear Magda, unfortunately L111wumnyb9gjw4zcwuj9k34f12lur03h already exists! Please, hit the button below and try a different id.

**Comment by eu-genia** [comment]
for some reason the code line `let $remove-used-id :=  update delete doc($next-id-file-path)/data/id[1]
` is ignored

**Comment by MagdaKrzyz** [comment]
than you, no hurry, I can add new entries later

**Comment by eu-genia** [comment]
seems all good after reboot, please check

**Comment by MagdaKrzyz** [comment]
I cannot create a new entry. The following message occurs: 
![errormessage](https://github.com/BetaMasaheft/Dillmann/assets/29131132/a53024ca-a921-43ed-9131-a539a3c22c81)

**Comment by eu-genia** [comment]
this error belongs to this issue https://github.com/BetaMasaheft/Dillmann/issues/461

I have now created https://betamasaheft.eu/Dillmann/lemma/L111ryfl4lvwg7p2zlf6emzkkmt6mmm0x which did work, please use it to fill data; when the xml:id error persists or reappears please use https://github.com/BetaMasaheft/Dillmann/issues/461, this issue is for a different type of error

**Comment by MagdaKrzyz** [comment]
No change, I receive the same message with a different ID

**Comment by eu-genia** [comment]
because you did create it you simply clicked twice 
I can see https://betamasaheft.eu/Dillmann/lemma/L111izpt0g37cc6niwkvfkibvnvkmx77x

**Comment by eu-genia** [comment]
I also created as a test https://betamasaheft.eu/Dillmann/lemma/L111izpt0g37cc6niwkvfkibvnvkmx78x for some reason when you create for a moment it seems that nothing happens but the lemma is created, so when you click again this message appears

**Comment by eu-genia** [comment]
Also https://betamasaheft.eu/Dillmann/lemma/L111m8v9k3w1wwezwp43qp4uykjbgvacl already exists, the app tells the truth

**Comment by MagdaKrzyz** [comment]
I do not deny it, only that there is something wrong with saving the entries. I hit the buttion "save", it is saving slowly and finally it gives me a message : this entry already exists ! And this happens every time I want to save a new word.  I do not click twice. 
It seems the app had a temporary crisis. Now all works well. Thanks

**Comment by MagdaKrzyz** [comment]
I tried to overwrite the entry under L111izpt0g37cc6niwkvfkibvnvkmx78x but I got this message : 
<exception>
<path>/db/apps/gez-en/edit/edit.xq</path>
<message>exerr:ERROR User 'Magda' does not have permission to write to the document '/db/apps/DillmannData/new/L111izpt0g37cc6niwkvfkibvnvkmx78x.xml'! [at line 170, column 37]</message>
</exception>

**Comment by eu-genia** [comment]
sorry forgot to chmod, now should be ok

**Comment by MagdaKrzyz** [comment]
Again the same problem with entering a new word. 
It does not take a new ID for the new word but gives me a message: "Dear Magda, unfortunately L111yvfpvqbfkh60pttk49brgb45udpgf already exists! Please, hit the button below and try a different id."
And that is right --- this ID is already occupied. 
Is there any way for me to take the next free ID?

**Comment by eu-genia** [comment]
Try again

Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian and Eritrean Studies
Universität Hamburg
Alsterterrasse 1
20354 Hamburg
+49 40 42838 7777
***@***.***
________________________________
Von: MagdaKrzyz ***@***.***>
Gesendet: Freitag, 19. Juli 2024 17:44:34
An: BetaMasaheft/Dillmann
Cc: Sokolinski, Eugenia; Assign
Betreff: Re: [BetaMasaheft/Dillmann] problems with creating a new entry (Issue #469)


Again the same problem with entering a new word.
It does not take a new ID for the new word but gives me a message: "Dear Magda, unfortunately L111yvfpvqbfkh60pttk49brgb45udpgf already exists! Please, hit the button below and try a different id."
And that is right --- this ID is already occupied.
Is there any way for me to take the next free ID?

**Comment by MagdaKrzyz** [comment]
I have managed to enter the word but with the next new word the situation repeats. It is stuck with the last ID that I used and does not take the next one.

**Comment by eu-genia** [comment]
As you.know I am on vacation and only have my mobile. My possibilities are limited, it is not possible for me to test the app. I have removed one more ID, maybe it helps this time. If not I can create several empty records for you to fill.
________________________________
Von: MagdaKrzyz ***@***.***>
Gesendet: Freitag, 19. Juli 2024 21:51:35
An: BetaMasaheft/Dillmann
Cc: Sokolinski, Eugenia; Assign
Betreff: Re: [BetaMasaheft/Dillmann] problems with creating a new entry (Issue #469)


I have managed to enter the word but with the next new word the situation repeats. It is stuck with the last ID that I used and does not take the next one.

**Comment by MagdaKrzyz** [comment]
I know that you are on vacation so no claims and complaints on my side. I am grateful that you attend to it anyway.
The removal helped to enter one word but with the next one the sitution repeated. 
Also there is one empty ID between two new entries; I tried to filled it in but got a message that I am not permitted to do that.
Here the link: https://betamasaheft.eu/Dillmann/lemma/L1111f11iim1dw7tw5c75guxq1j7717eh.

Maybe, as you suggested, it would be good if you created some new ids and I would not have to bother you again?

**Comment by eu-genia** [comment]
I have fixed permissions and updated the next I'd, should work for at least 1 more, I will try to see if I manage to create new records.
________________________________
Von: MagdaKrzyz ***@***.***>
Gesendet: Montag, 22. Juli 2024 09:14:28
An: BetaMasaheft/Dillmann
Cc: Sokolinski, Eugenia; Assign
Betreff: Re: [BetaMasaheft/Dillmann] problems with creating a new entry (Issue #469)


I know that you are on vacation so no claims and complaints on my side. I am grateful that you attend to it anyway.
The removal helped to enter one word but with the next one the sitution repeated.
Also there is one empty ID between two new entries; I tried to filled it in but got a message that I am not permitted to do that.
Here the link: https://betamasaheft.eu/Dillmann/lemma/L1111f11iim1dw7tw5c75guxq1j7717eh.

Maybe, as you suggested, it would be good if you created some new ids and I would not have to bother you again?

**Comment by MagdaKrzyz** [comment]
Indeed it worked for one new entry but for the next it failed. The same problem. You can try to create some new IDs but if it does not work I will simply prepare new entries in a word-document.

**Comment by eu-genia** [comment]
I have created stubs for
L111unkkqptebx2xorwyo1h04i77wd062 
L111s82f4em92kq3ce3radcxemd9rj8ew
L111cj96oxsaywslg9dt3hwe49ofzl9ms

I have not yet figured out why the module for saving goes in tilt and does not complete

**Comment by eu-genia** [comment]
Ok it tried to send an email message and fails and did not proceed to follow up with the remaining functions (delete used ID, chmod for access etc)

I have for now disabled the messaging, if we do need it back in the future I will try to see how to restore it. It could be connected with the new firewall of the uni servers so that the app cannot use the uni mailserv.

Please edit the 9 files I created and then proceed as normal.

**Comment by MagdaKrzyz** [comment]
I have successfully edited the 9 lemmata and added new entries. I could not add the following entry:
<Sen< >gez!ʾastarāwaṣa>
\*gez*አስተራወጸ፡\* >gez!ʾastarāwaṣa> ^IV,3^, manque dans le bm:Dillmann1865Lexicon. Le sens de cette forme verbale est: >fr>faire courir en s’entremêlant>. Texte et référence: \*gez*አስተራውጾሙ፡ ከመ፡ አድግ።\* Ms. (BM)[BAVet244] (amulette attachée à ce manuscrit).  {LB} [p., 157]bm:Grebaut1952SuppLexicon 
\*gez*አስተራወጸ\* >gez!ʾastarāwaṣa> ([p., 157]bm:Grebaut1952SuppLexicon) >en>make run by intermixing> [p., 477b]bm:Leslau1987dic 
  {ND} >S> 

and got a message:

<exception>
<path>/db/apps/gez-en/edit/save-new-entity.xql</path>
<message>exerr:ERROR The actual return type does not match the sequence type declared in the function's signature: app:upconvertSense(item()*) node(). Expected cardinality: exactly one, got 30. [at line 1358, column 36, source: /db/apps/gez-en/edit/save-new-entity.xql] In function: app:upconvertSense(item()*) [33:1:/db/apps/gez-en/modules/app.xql]</message>
</exception>

Do you understand what is here wrong?

I was not able to edit this file: 
https://betamasaheft.eu/Dillmann/lemma/L1111f11iim1dw7tw5c75guxq1j7717eh

**Comment by eu-genia** [comment]
I have inserted the content please check

**Comment by eu-genia** [comment]
if all is OK then close the issue

**Comment by MagdaKrzyz** [comment]
I have problems with creating a new entry. I receive this message :
![Screenshot 2024-10-18 131134](https://github.com/user-attachments/assets/04568d7e-7299-4f75-a4ee-caaf2c19b9a7)

**Comment by eu-genia** [comment]
the error you post is not relevant for this issue but for this one https://github.com/BetaMasaheft/Dillmann/issues/461 (one type of error = one issue, this issue was opened for ID already taken error)
