### ISSUE TITLE
Ms. Griaule 

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#470]
Could you please identify Ms. Griaule 227? Is it now Bibliothèque nationale de France? Has it been described in BM?

https://betamasaheft.eu/Dillmann/lemma/L1112gmfkyvk4vl5gvts47jnzbhoia3oo

**Comment by DenisNosnitsin1970** [comment]
It is Ms Ethiopien 535 - Griaule 227, not yet described in Bm, but I am making a stub (BNFet535).

**Comment by MagdaKrzyz** [comment]
Denis, could you do the same for Griaule 46? I need identification and a stub

https://betamasaheft.eu/Dillmann/lemma/L111i6cqy0bkkfsu24b3w96ua8dvuwfhh

**Comment by DenisNosnitsin1970** [comment]
ok.

    Am Donnerstag, 4. April 2024 um 13:21:54 MESZ hat MagdaKrzyz ***@***.***> Folgendes geschrieben:  
 
 


Denis, could you do the same for Griaule 46? I need identification and a stub

https://betamasaheft.eu/Dillmann/lemma/L111i6cqy0bkkfsu24b3w96ua8dvuwfhh
