### ISSUE TITLE
Needed stub for d’Abbadie 110

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#472]
Could you please make a stub for d’Abbadie 110? Thanks !

**Comment by MagdaKrzyz** [comment]
I need it for this entry 
https://betamasaheft.eu/Dillmann/lemma/Lf9a5bc9fab7e448aae0391a6c0dfd5e7

**Comment by eu-genia** [comment]
BNFabb110 exists already
