### ISSUE TITLE
citing new entries

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Dillmann#479]
Sorry for the question, but I did not see on Dillmann whether the answer is stated somewhere online. Is there a canonical way to cite new entries in Dillmann online? I would like to refer to https://betamasaheft.eu/Dillmann/lemma/L0608f56fddb64116b616299691671347
(I could also offer one more attestation, but only in Sǝnkǝssār manuscripts, no edition)
Thank you :)

**Comment by MagdaKrzyz** [comment]
What kind of an answer do you have in mind?

**Comment by MagdaKrzyz** [comment]
I do not think that there is any guidline on how to cite the dictionary.

**Comment by thea-m** [comment]
I meant something like the suggested citation information of Bm entries
![image](https://github.com/BetaMasaheft/Dillmann/assets/19650382/9d2a8a17-893d-4bc6-8c97-abef9740ff7f)

**Comment by eu-genia** [comment]
I was typing the same - we probably should add to the footnote like we have on Bm. 
Do you have a suggestion?

**Comment by eu-genia** [comment]
So in this case something like 
'እልኅቡስ' (lemma contributed to Magdalena Krzyzanowska to the Online _Lexicon Linguae Aethiopicae_, ed. Alessandro Bausi, last modified  21.11.2019, https://betamasaheft.eu/Dillmann/lemma/L0608f56fddb64116b616299691671347, accessed on 2024-05-07)

**Comment by eu-genia** [comment]
https://askus.library.wwu.edu/faq/190729#:~:text=A%20reference%20for%20a%20dictionary,a%20paper%20from%20Merriam%2DWebster.

**Comment by thea-m** [comment]
That looks good to me and really helpful for users

**Comment by eu-genia** [comment]
normally for dictionaries, unlike for encyclopaedias, authors for specific entries are not quoted in bibliographies, so it is a bit tricky

**Comment by MagdaKrzyz** [comment]
Yes, that is right but now dictionaries are a team work with many people involved. If we quote a one-man work (e.g. d'Abbadie) then we write his name. In our case I do the bulk of the work. I do not know whether Alessandro really edits it (does he?). So the citation without my name does credit to Alessandro but not to me. What do you think?

**Comment by MagdaKrzyz** [comment]
Dorothea, you add the new witness by giving the bibliography of the Ms, there is no problem. When you enter it, I can check it.

**Comment by eu-genia** [comment]
there is now a button, next to Revisions

![image](https://github.com/BetaMasaheft/Dillmann/assets/17987728/a8850be7-0f91-4e13-ac9c-8fa4a6e86707)

**Comment by eu-genia** [comment]
@thea-m if you are happy you can close the issue.

**Comment by thea-m** [comment]
Thank you!
