### ISSUE TITLE
Pages from 1424 not accessible

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#480]
Could you please check if you can access and entries from page 1424 to 1434? These are pages with Addenda et Corrigienda.

Here the link to the page https://www.tau.ac.il/~hacohen/Lexicon/pp1425.html 

Some entries: ተሀከየ፣ ሐንዘር፣ ሤረየ፣ ደዌ

**Comment by eu-genia** [comment]
I am sorry I cannot understand your question. You have to be a bit more specific as to what you are looking for exactly. 
I can see the PDF and I can search for the lemmata you listed but I am not in the position to check that the content is what you are expecting.
https://betamasaheft.eu/Dillmann/lemma/L9c964540b8684e868bdbfcc6a5a4351c
https://betamasaheft.eu/Dillmann/lemma/L5d3d97940bd14c33bd2b2d3fba4ea399
https://betamasaheft.eu/Dillmann/lemma/L571cddcc8bc94340a89b04720fbf3fff
etc

If there are Dillmann's corrections to be added to the main lemmata I doubt that it has been done, but I am not behind this at all.

**Comment by MagdaKrzyz** [comment]
The links that you have given are to the main entries, but these same entries appear also on pages 1424—1434 and I cannot access them. 
You suggest that these pages were not taken to the online version ?

**Comment by eu-genia** [comment]
I do not know, I am not behind the creation of the dictionary. Maybe @abausi knows how it was conceived.
But it clearly goes against any principle that there are two IDs for the same entity. Unless these are additional lemmata the corrections must go with the main record.

**Comment by eu-genia** [comment]
The app does not offer a possibility to link to two distinct pages in the Dillmann PDF file, but maybe the reference can be added as if it were an additional source.

**Comment by MagdaKrzyz** [comment]
But maybe it has to do with the confusion mention in issue 425? Many entries from the appendices were link to page 1424.

**Comment by MagdaKrzyz** [comment]
No, the addenda starts from 1425

**Comment by eu-genia** [comment]
please check in the initial data used for creation (https://drive.google.com/file/d/1s10-J397oIzMHaiW9y8PIgk8kzn0zKpL/view?usp=sharing I will remove the file later today)

**Comment by eu-genia** [comment]
I suggest that corrections to lemmata, if these are not **new** words, should be incorporated with the main entries

**Comment by MagdaKrzyz** [comment]
Ok, I have compared the entries, indeed they were incorporated into the main entry within curly brackets.
