### ISSUE TITLE
Ms. Graiule 127 and other mss.

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#482]
Let us look together for Griaule 127
https://betamasaheft.eu/Dillmann/lemma/L111e7yuidua1lgonzujdab6bx8xifp43

Ms. Vatican Borgia 2

Ms. Griaule 44 

I need a stub for d ' Abbadie 131

**Comment by DenisNosnitsin1970** [comment]
- Eth. 435 = Griaule 127 is a scroll, online, [](https://gallica.bnf.fr/ark:/12148/btv1b531192159/f2.item.r=%22Ethiopien%20435%22), I will make a stub. 
- Ms. Vatican Borgia 2 - a stub is there, BAVborget2, [](https://betamasaheft.eu/manuscripts/BAVborget2/main).
- Eth. 348 =  Griaule 44 "Dersane Raguel" is not accessible online, I can only make a stub, but the manuscript was used in the edition of Dersane Raguel, [(https://www.persee.fr/doc/ethio_0066-2127_1957_num_2_1_1261)], A. Caquot in Annales d'Ethiopie, 2, 1957, online.  Maybe the passage you need can be retrieved from there?
- Stub for Abb. 131 will appear soon.

**Comment by DenisNosnitsin1970** [comment]
[(https://gallica.bnf.fr/ark:/12148/btv1b531192159/f2.item.r=%22Ethiopien%20435%22)]
[(https://betamasaheft.eu/manuscripts/BAVborget2/main)]

**Comment by DenisNosnitsin1970** [comment]
done.

**Comment by MagdaKrzyz** [comment]
The stub for Abb 131 is needed for this entry:

https://betamasaheft.eu/Dillmann/lemma/L58ad98780f564233af6d5316b1fdda9d

**Comment by MagdaKrzyz** [comment]
Eth. 348 = Griaule 44 "Dersane Raguel" is not accessible online, I can only make a stub, but the manuscript was used in the edition of Dersane Raguel, [(https://www.persee.fr/doc/ethio_0066-2127_1957_num_2_1_1261)], A. Caquot in Annales d'Ethiopie, 2, 1957, online. Maybe the passage you need can be retrieved from thereI do not need a passage 
I would need a stub anyway and there perhaps you make an note about the edition.

**Comment by DenisNosnitsin1970** [comment]
The stubs/descriptions are online already, I will introduce the biblio reference soon. 
[(https://betamasaheft.eu/manuscripts/BNFabb131/main)]
[(https://betamasaheft.eu/manuscripts/BNFet348/main)]
[(https://betamasaheft.eu/manuscripts/BNFet435/main)]

**Comment by MagdaKrzyz** [comment]
Great !
