### ISSUE TITLE
Ms. Vatican 166

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#483]
I would need a stub for Vat. 166 for this entry: 
https://betamasaheft.eu/Dillmann/lemma/L1c2425da340d40959dd2d41dba089c82

**Comment by thea-m** [comment]
Thank you, I am not working on this for the duration of my scholarship :) 
@eu-genia has the best overview who is best suited to which tasks

**Comment by eu-genia** [comment]
@karljonaskarlsson can take care of this, thank you @karljonaskarlsson

**Comment by karljonaskarlsson** [comment]
It seems like there already exists a record for this manuscript: https://betamasaheft.eu/manuscripts/BAVet166/main?hi

@MagdaKrzyz, please correct me if I am misunderstanding something! :)

**Comment by MagdaKrzyz** [comment]
Ups! I am sorry  for bothering you. I have not checked because I thought Dorothea was not so far.
