### ISSUE TITLE
Cannot enter a new word

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#486]
Zhenia, I keep receiving this message when I creat a new entry. 

Dear Magda, unfortunately L111m8v9k3w1wwezwp43qp4uykjbgvacl already exists! Please, hit the button below and try a different id.

When I check whether the id really  exists, I get a message that it cannot be found.

**Comment by eu-genia** [comment]
The issue already exists https://github.com/BetaMasaheft/Dillmann/issues/469 use the existing ones for the same error. I have resaved the next-id list please check

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Dillmann/lemma/L111m8v9k3w1wwezwp43qp4uykjbgvacl indeed exists
