### ISSUE TITLE
Stub for Vat. 212

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#487]
I would need a stub for ms. Vatican 212 for this entry:
https://betamasaheft.eu/Dillmann/lemma/L111j0yqubs0bq13e215r7tsw22xviamf

**Comment by karljonaskarlsson** [comment]
Done (more or less)! https://github.com/BetaMasaheft/Manuscripts/pull/2518

**Comment by karljonaskarlsson** [comment]
I double-checked Grébaut, just to be on the safe side, and I think he transcribed the manuscript as having ቀራንዩ rather than ቀራንዮ

**Comment by MagdaKrzyz** [comment]
Thank you for the correction!
