### ISSUE TITLE
Griaule 315

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#491]
Could you identify for me Graiule 315 for the following entry:
 https://betamasaheft.eu/Dillmann/lemma/L26888ffc8559445184f2c04c8b1e2378

**Comment by DenisNosnitsin1970** [comment]
Stub created.

**Comment by MagdaKrzyz** [comment]
could you send me the link to BM?

**Comment by DenisNosnitsin1970** [comment]
https://www.betamasaheft.eu/manuscripts/BNFet623/main
