### ISSUE TITLE
Needed stub for Ms. Vatican 165

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Dillmann#501]
I would need a stub for Ms. Vatican 165 for the following entry : 
https://betamasaheft.eu/Dillmann/lemma/L96c5d8fd425544fd976ff01440532502

**Comment by MassimoVilla** [comment]
Hi Magda. I am a bit overwhelmed with many tasks these days, I'll create the stub asap. Thank you

**Comment by MagdaKrzyz** [comment]
Hi Massimo, no problem! Take your time!

**Comment by MagdaKrzyz** [comment]
I guess this can be closed now
