### ISSUE TITLE
Cod. Laur.

### ISSUE THREAD

**Issue by AndreasEllwardt** [BetaMasaheft/Dillmann#56]

**Comment by AndreasEllwardt** [comment]
Prophetæ Veteres Pseudepigraphi : partim ex abyssinico vel hebraico sermonibus latine versi ; Ascensio Isaiae vatis ... / Edente A. F. Gfrœrer, Bibliothecae regiae, quae Stuttgardiae est, praefecto Gfrörer, August Friedrich, 1803-1861 [Hrsg.]

**Comment by AndreasEllwardt** [comment]
http://reader.digitale-sammlungen.de/de/fs1/object/display/bsb11346933_00005.html

**Comment by AndreasEllwardt** [comment]
alles falsch: https://www.tau.ac.il/~hacohen/Jesaia/JesaiaVorbemerkung.pdf

**Comment by PietroLiuzzo** [comment]
also was nun soll ich mit Cod. Laur. machen?
