### ISSUE TITLE
DL Abbr.: streamline "Abb. Cat. p." = d’Abbadie Cat. = "d'Abb. Cat." (as in printed DL list of Sigla)

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#7]
Lcd43b546c26341479b79d258b3f18b25 

- this is a mss. catalogue: can it get a "LIT"-ID - no, right? what kind of other ID? 
- why is "p." added in online DL? doesn't is simply refer to "pagina"/"page" and should thus be neglected? 
- link to work online: http://gallica.bnf.fr/ark:/12148/bpt6k1044499

**Comment by PietroLiuzzo** [comment]
change in data to bibliographical pointers, preserving the text and harmonizing it

**Comment by PietroLiuzzo** [comment]
bm:Abbadie1859Cat

**Comment by PietroLiuzzo** [comment]
replacing with `<bibl><ptr target="bm:Abbadie1859Cat"/><citedRange unit="page">210</citedRange></bibl>`

**Comment by PietroLiuzzo** [comment]
there are also cases like d’Abbadie <ref cRef="Cat." loc="99">Cat. p. 99</ref>

**Comment by PietroLiuzzo** [comment]
fixed around 100 instances, residual cases should be hand fixed
