### ISSUE TITLE
unknown abbreviations found in Dillmann

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#73]
hieroz?
Did.?
amh.?
c.? construitur cum? 
Abb.?
Isenb.?
Rosenm.?
Comm.?
Pl. Pl.?
term. adj.
c. term.?

**Comment by PietroLiuzzo** [comment]
@AndreasEllwardt

**Comment by AndreasEllwardt** [comment]
Bochart Hieroz. muß ich im Gesenius nachschauen;
Did. steht im Abkürzungsverzeichnis: Did.	Didascalia Apostolorum; numerus significat capita.;
c. ist nicht eindeutig, kann cum heißen, oder columna oder caput - meistens heißt es wohl cum;
Abb. sollte d'Abbadie sein;
Isenb. ist Isenberg, muß aber immer korrekt dekliniert werden (Wolfgang!);
Rosenm. ist der Herausgeber von Hieroz., s.o.;
Comm. scheint immer Ludolfs Kommentar zu sein;
Pl. Pl. ist, wie gesagt, der Plural des Plurals, eine typisch südsemitische, also im Wesentlichen arabische und äthiopische, Form;
(c.) term. adj. ist meistens part. c. term. adj., also Partizip mit Adjektivendung;

Ich werde Wolfgang bitten, das Ganze in schönes Latein zu kleiden.

**Comment by AndreasEllwardt** [comment]
Bochart Hieroz. muß ich im Gesenius nachschauen;
Did. steht im Abkürzungsverzeichnis: Did.	Didascalia Apostolorum; numerus significat capita.;
c. ist nicht eindeutig, kann cum heißen, oder columna oder caput - meistens heißt es wohl cum;
Abb. sollte d'Abbadie sein;
Isenb. ist Isenberg, muß aber immer korrekt dekliniert werden (Wolfgang!);
Rosenm. ist der Herausgeber von Hieroz., s.o.;
Comm. scheint immer Ludolfs Kommentar zu sein;
Pl. Pl. ist, wie gesagt, der Plural des Plurals, eine typisch südsemitische, also im Wesentlichen arabische und äthiopische, Form;
(c.) term. adj. ist meistens part. c. term. adj., also Partizip mit Adjektivendung;

Ich werde Wolfgang bitten, das Ganze in schönes Latein zu kleiden.

**Comment by AndreasEllwardt** [comment]
https://opacplus.bsb-muenchen.de/metaopac/search?oclcno=163507908&db=100

**Comment by abausi** [comment]
hieroz? = (refers to the following work:) Samuel Bochart, Hierozoicon, Sive Bipertitum Opus De Animalibus S. Scripturae: Cum Indice Septuplici, I. Locorum Sac. Scr. II. Authorum, qui citantur. III. Vocum Hebr. Chald. Syriac. Samaritani et Aethiopici Sermonis. De Avibus, Serpentibus, Insectis, Aquaticis, & Fabulosis Animalibus, I-II (Frankfurt am Main: Zunner, 1675; repr. 1692)

Did. = Didascalia apostolorum

amh.? = amharice, amharicum (i.e. "in Amharic, Amharic")

c.? (in "construitur cum") = cum (""construitur cum", i.e. "it is constructed with")

Abb.? = d’Abbadie

Isenb.? = Isenberg

Rosenm.? = I have to check the occurrences

Comm.? = Commentarius ad suam Historiam Aethiopicam antehac editam ()by Ludolf)

Pl. Pl.? = Pluralis pluralis ("plural of the plural")

term. adj. = terminatio adjectivi (see below)

c. term.? = cum terminatione (usually: "c. term. adj." i.e. "cum terminatione adjectivi", i.e. "with an adjectival ending")

**Comment by abausi** [comment]
I have (re)solved all the points: please, someone has to insert them at 
the right place and then we can close this issue.

Il 14.09.2019 10:04, Pietro Liuzzo ha scritto:
