### ISSUE TITLE
DL Abbr.: introduce "II Abt." in online DL for "Abt." 

### ISSUE THREAD

**Issue by fitawari** [BetaMasaheft/Dillmann#8]
L821471830385413d80d36f15a4385c6b 

- numeral II not marked-up
- reference in EAE Vol 1., p. 50: abt'elis = part of Senodos (canonic collection) 
- one "umbrella ID" for all parts of the Senodos or not? (LIT2317Senodo) 
- DL Sigla differentiates "Abt." and "II Abt." (= 2nd recension of Abt.) = does each one gets it own ID? 
- same issue with "Abtel. Ap." (in online DL, not in list of Sigla)

**Comment by PietroLiuzzo** [comment]
the id used for II Abt. i the example is wrong, should be LIT2678ACAbt2, not LIT2678ACABt2, to be fixed in abbreviation list, checking the other options are also available as described above
