### ISSUE TITLE
wrong order of entries

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Dillmann#93]
The 21 omitted entries generate a gap in the consecutive numbering. where do they need to be inserted? the numeration after the last entry before the now restored lacuna need all to be incremented by 21 and the 21 record added need to be manually updated in the XML

**Comment by PietroLiuzzo** [comment]
the entries from n. 12203 are the fehelende lemmata in the collection.
their real position is after n. 9773. 

the fehelende lemmata need to be renumbered from 9774 onwards and all the entries after them need to be renumbered from the last one of them onwards.

it will be a mess and it is by no means a priority yet.

**Comment by PietroLiuzzo** [comment]
thanks @LeonardBahr

**Comment by PietroLiuzzo** [comment]
The entries have been reordered

**Comment by LeonardBahr** [comment]
Dear Pietro, 

I have checked them. Good to know their order is fixed. Thank you very much. 

Yours,
Leonardo
